gac_sb/objects/AppATctn__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>Annee__c</fullName>
        <label>Année</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCMIP1__c</fullName>
        <label>CCM IP1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP2__c</fullName>
        <label>CCM IP2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP3__c</fullName>
        <label>CCM IP3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP4__c</fullName>
        <label>CCM IP4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT1__c</fullName>
        <label>CCM IT1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT2__c</fullName>
        <label>CCM IT2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT3__c</fullName>
        <label>CCM IT3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT4__c</fullName>
        <label>CCM IT4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT5__c</fullName>
        <label>CCM IT5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT6__c</fullName>
        <label>CCM IT6</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TypeCTN__c</fullName>
        <label>Type CTN</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>BAM</fullName>
                </value>
                <value>
                    <fullName>BGO</fullName>
                </value>
                <value>
                    <fullName>BSO</fullName>
                </value>
                <value>
                    <fullName>BSS</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>DD</fullName>
                </value>
                <value>
                    <fullName>EE</fullName>
                </value>
                <value>
                    <fullName>FF</fullName>
                </value>
                <value>
                    <fullName>GG</fullName>
                </value>
                <value>
                    <fullName>HH</fullName>
                </value>
                <value>
                    <fullName>II</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CTN</label>
    <nameField>
        <label>Nom de CTN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/AppATetablissement__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mission__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>TAT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Etablissements</relationshipLabel>
        <relationshipName>EtablissementsConcernes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SIRET__c</fullName>
        <label>SIRET</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Etablissement</label>
    <nameField>
        <label>Nom de l&apos;Etablissement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etablissements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppATfeuilleCalcul__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>AnneeFeuilleCalcul__c</fullName>
        <label>Année de la feuille de calcul</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCMIT1_N_2__c</fullName>
        <label>CCM IT1 N-2</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT1_N_3__c</fullName>
        <label>CCM IT1 N-3</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT1_N_4__c</fullName>
        <label>CCM IT1 N-4</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charges__c</fullName>
        <formula>Majoration__r.Charges__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Compensation__c</fullName>
        <formula>Majoration__r.Compensation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Compensation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Effectif__c</fullName>
        <label>Effectif</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EtablissementConcerne__c</fullName>
        <label>Etablissement concerné</label>
        <referenceTo>AppATetablissement__c</referenceTo>
        <relationshipLabel>Feuilles de calcul</relationshipLabel>
        <relationshipName>FeuillesCalcul</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MajorationForfaitaireRisqueTrajet__c</fullName>
        <formula>Majoration__r.MajorationForfaitaireRisqueTrajet__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Majoration Forfaitaire Risque Trajet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Majoration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Majoration</label>
        <referenceTo>AppATmajoration__c</referenceTo>
        <relationshipLabel>Feuilles de calcul</relationshipLabel>
        <relationshipName>Feuilles_de_calcul</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <formula>HYPERLINK( EtablissementConcerne__r.Mission__c , EtablissementConcerne__r.Mission__r.Name , &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mission</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Penibilite__c</fullName>
        <formula>Majoration__r.Penibilite__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pénibilité</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_de_feuille_de_calcul__c</fullName>
        <label>Type de feuille de calcul</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initiale</fullName>
                </value>
                <value>
                    <fullName>Rectifiée</fullName>
                </value>
                <value>
                    <fullName>Simulée</fullName>
                </value>
                <value>
                    <fullName>Refacturation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Feuille de calcul</label>
    <nameField>
        <label>Nom de la feuille de calcul</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feuilles de calcul</pluralLabel>
    <recordTypes>
        <fullName>TauxReel</fullName>
        <active>true</active>
        <label>Taux Réel</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppATmajoration__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>Annee__c</fullName>
        <label>Année</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charges__c</fullName>
        <label>Charges</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Compensation__c</fullName>
        <label>Compensation</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CoutRisque__c</fullName>
        <label>Coût du risque</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MajorationForfaitaireRisqueTrajet__c</fullName>
        <label>Majoration forfaitaire risque trajet</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Majoration__c</fullName>
        <label>Majoration</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Penibilite__c</fullName>
        <label>Pénibilité</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Majoration</label>
    <nameField>
        <label>Nom de Majoration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Majorations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/AppATmasseSalariale__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>Annee__c</fullName>
        <label>Année</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effectif__c</fullName>
        <label>Effectif</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EtablissementConcerne__c</fullName>
        <label>Etablissement concerné</label>
        <referenceTo>AppATetablissement__c</referenceTo>
        <relationshipLabel>Masses salariales</relationshipLabel>
        <relationshipName>MassesSalariales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MasseSalariale__c</fullName>
        <label>Masse Salariale</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <formula>HYPERLINK( EtablissementConcerne__r.Mission__c , EtablissementConcerne__r.Mission__r.Name, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mission</label>
        <type>Text</type>
    </fields>
    <label>Masse salariale</label>
    <nameField>
        <label>Nom de la masse salariale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Masses salariales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <recordTypes>
        <fullName>TAT</fullName>
        <active>true</active>
        <description>Mission TAT</description>
        <label>TAT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/AppATfeuilleCalculCtrl_Test.cls
@isTest
private class AppATfeuilleCalculCtrl_Test {

	private static testMethod void testAppATfeuilleCalculCtrl() {
		//Création d'une mission en réutilisant le code de FactuTestBase
        FactuTestBase.Init();
        Mission__c missionAT;
        for(Mission__c m : FactuTestBase.Missions){
            if(m.RecordType.developerName == 'TAT'){
                missionAT = m;
                break;
            }
        }
        
        
        //Création d'un établissement
        AppATetablissement__c etab = new AppATetablissement__c(Mission__c = missionAT.Id, SIRET__c = '147 852 369 52369');
        insert etab;
        
        //Création d'un CTN
        AppATctn__c ctn = new AppATctn__c(Annee__c = '2015', TypeCTN__c = 'AA', CCMIP1__c = 100, CCMIP2__c = 100, CCMIP3__c = 100, CCMIP4__c = 100, CCMIT1__c = 100, CCMIT2__c = 100, CCMIT3__c = 100, CCMIT4__c = 100, CCMIT5__c = 100, CCMIT6__c = 100);
		insert ctn;
		
		//Création des masses salariales
		List<AppATmasseSalariale__c> ms = new List<AppATmasseSalariale__c>{new AppATmasseSalariale__c(Annee__c = '2014', EtablissementConcerne__c = etab.Id, Effectif__c = 10, MasseSalariale__c = 1000),
																			new AppATmasseSalariale__c(Annee__c = '2013', EtablissementConcerne__c = etab.Id, Effectif__c = 10, MasseSalariale__c = 1000),
																			new AppATmasseSalariale__c(Annee__c = '2012', EtablissementConcerne__c = etab.Id, Effectif__c = 10, MasseSalariale__c = 1000),
																			new AppATmasseSalariale__c(Annee__c = '2011', EtablissementConcerne__c = etab.Id, Effectif__c = 10, MasseSalariale__c = 1000)};
        insert ms;
        
        //Création d'une majoration
        AppATmajoration__c major = new AppATmajoration__c(Annee__c = '2015', Charges__c = 50, Compensation__c = 50, CoutRisque__c = 5000, Majoration__c = 50, MajorationForfaitaireRisqueTrajet__c = 50, Penibilite__c = 50);
        insert major;
        
        
        Test.startTest();
        //Initialisation de la feuille de calcul
        Id RecordTypeIdFCtauxReel = [SELECT Id FROM RecordType WHERE SObjectType = 'AppATfeuilleCalcul__c' AND DeveloperName = 'TauxReel' LIMIT 1][0].Id;
        
        AppATfeuilleCalcul__c fc = new AppATfeuilleCalcul__c(EtablissementConcerne__c = etab.Id, RecordTypeId = RecordTypeIdFCtauxReel);
        
        ApexPages.standardController stdCtrl = new ApexPages.standardController(fc);
        AppATfeuilleCalculCtrl ctrl = new AppATfeuilleCalculCtrl(stdCtrl);
        
        fc.AnneeFeuilleCalcul__c = '2015';
        fc.Type_de_feuille_de_calcul__c = 'AA';
        ctrl.selectedCTNtype = 'AA';
        
        ctrl.create();
        fc.CCMIT1_N_4__c = 1;
        fc.CCMIT1_N_3__c = 2;
        fc.CCMIT1_N_2__c = 4;
        stdCtrl.save();
        
        //system.assertEquals('lkj', fc.Id);
        //Test du clonage
        PageReference clonePage = Page.AppATfeuilleCalculEdit;
        clonePage.getParameters().put('clone', '1');
        clonePage.getParameters().put('id',  fc.Id);
        Test.setCurrentPage(clonePage);
        stdCtrl = new ApexPages.standardController(fc);
        ctrl = new AppATfeuilleCalculCtrl(stdCtrl);
        fc.AnneeFeuilleCalcul__c = '2016';
        fc.Type_de_feuille_de_calcul__c = 'Simulée';
        ctrl.create();
        
        
        //Vérifie ques les CCM IT/IP se sont bien décalés d'une année
       /* system.assertEquals(2, fc.CCMIT1_N_4__c);
        system.assertEquals(3, fc.CCMIT1_N_3__c);
        system.assertEquals(null, fc.CCMIT1_N_2__c);*/
        
        Test.stopTest();
	}

}