gac_sb/objects/AppATdossiersSalaries__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>DateSinistre__c</fullName>
        <label>Date du sinistre</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Dossiers Salariés</relationshipLabel>
        <relationshipName>DossiersSalaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nom__c</fullName>
        <label>Nom</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumeroSecuriteSociale__c</fullName>
        <label>Numéro de sécurité sociale</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demandé</fullName>
                </value>
                <value>
                    <fullName>Audit en cours</fullName>
                </value>
                <value>
                    <fullName>Contestation en cours</fullName>
                </value>
                <value>
                    <fullName>Instruction en cours</fullName>
                </value>
                <value>
                    <fullName>Aucune piste identifiée</fullName>
                </value>
                <value>
                    <fullName>Refus de prise en charge</fullName>
                </value>
                <value>
                    <fullName>Classement du dossier</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dossier Salarié</label>
    <nameField>
        <label>Nom du Dossier Salarié</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dossiers Salariés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppATorganisme__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>NombreRecoursGagnes__c</fullName>
        <label>Nombre de recours gagnés</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NombreTotalRecours__c</fullName>
        <label>Nombre total de recours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Organisme</label>
    <nameField>
        <label>Nom de l&apos;organisme</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organismes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/AppATrecours__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>DossierSalarie__c</fullName>
        <label>Dossier Salarié</label>
        <referenceTo>AppATdossiersSalaries__c</referenceTo>
        <relationshipLabel>Recours</relationshipLabel>
        <relationshipName>Recours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Recours</relationshipLabel>
        <relationshipName>Recours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrganismeJuridiction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisme/Juridiction</label>
        <referenceTo>AppATorganisme__c</referenceTo>
        <relationshipLabel>Recours</relationshipLabel>
        <relationshipName>Recours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En cours</fullName>
                </value>
                <value>
                    <fullName>Accord</fullName>
                </value>
                <value>
                    <fullName>Rejet</fullName>
                </value>
                <value>
                    <fullName>Désistement</fullName>
                </value>
                <value>
                    <fullName>Abandon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recours</label>
    <nameField>
        <label>Nom du recours</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <recordTypes>
        <fullName>TAT</fullName>
        <active>true</active>
        <description>Mission TAT</description>
        <label>TAT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/AppATRecoursTrigger_Test.cls
@isTest
public class AppATRecoursTrigger_Test {

    @isTest public static void testAppATRecoursTrigger(){
        
        //Création d'une mission en réutilisant le code de FactuTestBase
        FactuTestBase.Init();
        Mission__c missionAT;
        for(Mission__c m : FactuTestBase.Missions){
            if(m.RecordType.developerName == 'TAT'){
                missionAT = m;
                break;
            }
        }
        
        
        //Création organisme
        AppATorganisme__c org = new AppATorganisme__c(Name = 'organisme test');
        insert org;
        
        //Création dossier salarié
        AppATdossiersSalaries__c sal = new AppATdossiersSalaries__c(Name = 'dossier salarié test', Nom__c = 'dossier salarié test', DateSinistre__c = system.today(), Mission__c = missionAT.Id, NumeroSecuriteSociale__c = '1234567891234');
        insert sal;        
        
        test.startTest();

        List<AppATrecours__c> recToInsert = new List<AppATrecours__c> ();
        AppATrecours__c recour1 = new AppATrecours__c(OrganismeJuridiction__c = org.Id, DossierSalarie__c = sal.Id, Statut__c = 'Rejet');
        recToInsert.add(recour1);
        
        AppATrecours__c recour2 = new AppATrecours__c(OrganismeJuridiction__c = org.Id, DossierSalarie__c = sal.Id, Statut__c = 'Accord');
        recToInsert.add(recour2);
        
        insert recToInsert;
        
        org = [SELECT Id, NombreTotalRecours__c, NombreRecoursGagnes__c FROM AppATorganisme__c WHERE Id = :org.Id][0];
        
        system.assertEquals(2, org.NombreTotalRecours__c);
        system.assertEquals(1, org.NombreRecoursGagnes__c);
        
        
        test.stopTest();
    }
}