gac_sb/objects/AppATdossiersSalaries__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>EtablissementConcerne__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Etablissement concerné</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AppATetablissement__c.Mission__c</field>
                <operation>equals</operation>
                <valueField>$Source.Mission__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AppATetablissement__c</referenceTo>
        <relationshipLabel>Dossiers Salariés</relationshipLabel>
        <relationshipName>DossiersSalaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Dossiers Salariés</relationshipLabel>
        <relationshipName>DossiersSalaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nom__c</fullName>
        <label>Nom</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demandé</fullName>
                </value>
                <value>
                    <fullName>Audit en cours</fullName>
                </value>
                <value>
                    <fullName>Contestation en cours</fullName>
                </value>
                <value>
                    <fullName>Instruction en cours</fullName>
                </value>
                <value>
                    <fullName>Aucune piste identifiée</fullName>
                </value>
                <value>
                    <fullName>Refus de prise en charge</fullName>
                </value>
                <value>
                    <fullName>Classement du dossier</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dossier Salarié</label>
    <nameField>
        <label>Nom du Dossier Salarié</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dossiers Salariés</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppATetablissement__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mission__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>TAT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Etablissements</relationshipLabel>
        <relationshipName>EtablissementsConcernes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SIRET__c</fullName>
        <label>SIRET</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Etablissement</label>
    <nameField>
        <label>Nom de l&apos;Etablissement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etablissements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppATformationPortail__c.object
<CustomObject>
    <description>Application AT</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Formation Portail</label>
    <nameField>
        <label>Titre de la formation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formations Portail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/Facture__c.object
<CustomObject>
    <description>SF CONSULTING - permet de créer des factures</description>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Factures</relationshipLabel>
        <relationshipName>Factures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Montant_HT__c</fullName>
        <description>(Facture)</description>
        <label>Montant HT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SIRET__c</fullName>
        <formula>Contrat__r.Account.SIRET__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SIRET</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En attente</fullName>
                    <default>true</default>
                    <label>En attente</label>
                </value>
                <value>
                    <fullName>Validée</fullName>
                </value>
                <value>
                    <fullName>Envoyée</fullName>
                </value>
                <value>
                    <fullName>Soldée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Facture</label>
    <nameField>
        <label>N° Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <fields>
        <fullName>Compte__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <recordTypes>
        <fullName>TAT</fullName>
        <active>true</active>
        <description>Mission TAT</description>
        <label>TAT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/Prevision_de_facturation__c.object
<CustomObject>
    <description>SF CONSULTING - permet de saisir des planifications de facturation</description>
    <fields>
        <fullName>Date_prevue__c</fullName>
        <label>Date prévue</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facture associée</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Mission__c</field>
                <operation>equals</operation>
                <valueField>Facture__c.Mission__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facture__c</referenceTo>
        <relationshipLabel>Planifications de facturation liées</relationshipLabel>
        <relationshipName>Planificiations_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mission__c.Contrat__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contrat__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>Planifications_de_facturation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Motif_attente_facturation__c</fullName>
        <label>Motif attente facturation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Appel CPAM</fullName>
                </value>
                <value>
                    <fullName>Attente FDA</fullName>
                </value>
                <value>
                    <fullName>Attente rectification des taux</fullName>
                </value>
                <value>
                    <fullName>Écrêtement</fullName>
                </value>
                <value>
                    <fullName>Prescription URSSAF</fullName>
                </value>
                <value>
                    <fullName>Prêt à facturer</fullName>
                </value>
                <value>
                    <fullName>Valorisation non remise au client</fullName>
                </value>
                <value>
                    <fullName>Dossier non remis</fullName>
                </value>
                <value>
                    <fullName>CERFA pas encore remis au client</fullName>
                </value>
                <value>
                    <fullName>Dépôt du CERFA pas encore effectué</fullName>
                </value>
                <value>
                    <fullName>Attente remboursement</fullName>
                </value>
                <value>
                    <fullName>Heures CRT non communiqués</fullName>
                </value>
                <value>
                    <fullName>Attente cotisation</fullName>
                </value>
                <value>
                    <fullName>Attente vérification</fullName>
                </value>
                <value>
                    <fullName>Facturé</fullName>
                </value>
                <value>
                    <fullName>Attente obtention agrément</fullName>
                </value>
                <value>
                    <fullName>Attente négociation client</fullName>
                </value>
                <value>
                    <fullName>Appel</fullName>
                </value>
                <value>
                    <fullName>Dépôt du dossier d’agrément</fullName>
                </value>
                <value>
                    <fullName>Dépôt du dossier JEI</fullName>
                </value>
                <value>
                    <fullName>Obtention du statut JEI</fullName>
                </value>
                <value>
                    <fullName>Attente économie réalisé lié au statut JEI</fullName>
                </value>
                <value>
                    <fullName>Réception de la notification du CF</fullName>
                </value>
                <value>
                    <fullName>Mission non lancée</fullName>
                </value>
                <value>
                    <fullName>Rapport d’audit à remettre</fullName>
                </value>
                <value>
                    <fullName>Attente du 1er chiffrage</fullName>
                </value>
                <value>
                    <fullName>Attente de la remise des éléments financiers</fullName>
                </value>
                <value>
                    <fullName>Attente confirmation TR</fullName>
                </value>
                <value>
                    <fullName>Attente reconduction de contrat</fullName>
                </value>
                <value>
                    <fullName>Agrément provisoire CIJV pas encore obtenu</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prevision_HT__c</fullName>
        <label>Prévision HT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Facturée</fullName>
                </value>
                <value>
                    <fullName>Prévue</fullName>
                </value>
                <value>
                    <fullName>HGNF</fullName>
                </value>
                <value>
                    <fullName>Rejetée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Planification de facturation</label>
    <nameField>
        <displayFormat>Planif-{000000}</displayFormat>
        <label>N° Planification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planifications de facturation</pluralLabel>
    <recordTypes>
        <fullName>TAT</fullName>
        <active>true</active>
        <description>Prévision de facturation TAT</description>
        <label>TAT</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/PortailATctrl_Test.cls
@isTest
private class PortailATctrl_Test {

	private static testMethod void test() {
		
		Account acc = new Account(Name = 'Synefo');
		insert acc;
		
		Contact cont = new Contact(LastName = 'weber', AccountId = acc.Id);
		insert cont;
		
		Mission__c mission = new Mission__c(Name = 'Synefo', Compte__c = acc.Id, RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Mission__c' AND DeveloperName = 'TAT'][0].Id);
		insert mission;
		
		AppATetablissement__c etab = new AppATetablissement__c(Name = 'Synefo', Mission__c = mission.Id, SIRET__c = '12345678912345');
		insert etab;
		
		AppATdossiersSalaries__c dossier = new AppATdossiersSalaries__c(Name = 'Weber', Nom__c = 'Weber', Mission__c = mission.Id, EtablissementConcerne__c = etab.Id);
		insert dossier;
		
		insert new Prevision_de_facturation__c(Mission__c = mission.Id, Statut__c = 'Prévue', Prevision_HT__c = 1000, Motif_attente_facturation__c = 'Prêt à facturer', Date_prevue__c = System.today());
		
		insert new Facture__c(Mission__c = mission.Id, Montant_HT__c = 2000, Statut__c = 'Envoyée');
		
		AppATformationPortail__c formation = new AppATformationPortail__c(Name = 'Portail AT', Active__c = true);
		insert formation;
		
		AppATdateFormationPortail__c dateFormation = new AppATdateFormationPortail__c(Formation__c = formation.Id, Date__c = System.today(), Lieu__c = 'Synefo', CodePostalFormation__c = '92310', RueFormation__c='1 avenue de la cristalerie' , VilleFormation__c='Sèvres');
		insert dateFormation; 
		
		insert new AppATespaceDocument__c(Name = 'Synefo', LienSite__c = 'www.synefo.fr');
		
		User portalUser = new User(Alias = 'weber', Email = 'tweber@synefo.fr', EmailEncodingKey = 'UTF-8', ContactId = cont.Id, LastName = 'Weber', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = [SELECT Id FROM Profile WHERE Name = 'ZZ - EXT - Portail AT'][0].Id, TimeZoneSidKey = 'Europe/Paris', UserName = 'tweber@synefo.fr');
		
		
		
		Test.startTest();
		
		System.runAs(portalUser){
			
			PortailATctrl ctrl = new PortailATctrl();
			
			System.assertEquals(ctrl.myContact.Id, cont.Id);
			
			System.assert(ctrl.getDossiersJSON().contains(dossier.Id));
			
			System.assertEquals(1, ctrl.getEtablissements().size());
			
			System.assertEquals(etab.Id, PortailATctrl.getEtablissementDetails(etab.Id).Id);
			
			PortailATctrl.getEtablissementChartData(etab.Id);
			
			System.assertEquals(1, ctrl.getPrevisionsFactures().size());
			
			System.assertEquals(1, ctrl.getFactures().size());
			
			System.assertEquals(1, ctrl.getDatesFormations().size());
			
			System.assertEquals(1, ctrl.getFormations().size());
			
			ctrl.inscriptionSelectedFormation = dateFormation.Id;
			ctrl.sendInscriptionEmail();
			
			System.assertEquals(1, ctrl.getDocuments().size());
			
		}
		
		Test.stopTest();
	}

}