gac_sb/objects/AppATctn__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>Annee__c</fullName>
        <label>Année</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeCTN__c</fullName>
        <label>Type CTN</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>BAM</fullName>
                </value>
                <value>
                    <fullName>BGO</fullName>
                </value>
                <value>
                    <fullName>BSO</fullName>
                </value>
                <value>
                    <fullName>BSS</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>DD</fullName>
                </value>
                <value>
                    <fullName>EE</fullName>
                </value>
                <value>
                    <fullName>FF</fullName>
                </value>
                <value>
                    <fullName>GG</fullName>
                </value>
                <value>
                    <fullName>HH</fullName>
                </value>
                <value>
                    <fullName>II</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CTN</label>
    <nameField>
        <label>Nom de CTN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CTN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/AppATetablissement__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>AlsaceMoselle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Alsace Moselle ?</label>
        <type>Checkbox</type>
    </fields>
    <label>Etablissement</label>
    <nameField>
        <label>Nom de l&apos;Etablissement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etablissements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppATfeuilleCalcul__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>AlsaceMoselle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Alsace Moselle ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AnneeFeuilleCalcul__c</fullName>
        <label>Année de la feuille de calcul</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCMIP1_N_2__c</fullName>
        <label>CCM IP1 N-2</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP1_N_3__c</fullName>
        <label>CCM IP1 N-3</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP1_N_4__c</fullName>
        <label>CCM IP1 N-4</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP2_N_2__c</fullName>
        <label>CCM IP2 N-2</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP2_N_3__c</fullName>
        <label>CCM IP2 N-3</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP2_N_4__c</fullName>
        <label>CCM IP2 N-4</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP3_N_2__c</fullName>
        <label>CCM IP3 N-2</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP3_N_3__c</fullName>
        <label>CCM IP3 N-3</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP3_N_4__c</fullName>
        <label>CCM IP3 N-4</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP4_N_2__c</fullName>
        <label>CCM IP4 N-2</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP4_N_3__c</fullName>
        <label>CCM IP4 N-3</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIP4_N_4__c</fullName>
        <label>CCM IP4 N-4</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT1_N_2__c</fullName>
        <label>CCM IT1 N-2</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT1_N_3__c</fullName>
        <label>CCM IT1 N-3</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT1_N_4__c</fullName>
        <label>CCM IT1 N-4</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT2_N_2__c</fullName>
        <label>CCM IT2 N-2</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT2_N_3__c</fullName>
        <label>CCM IT2 N-3</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT2_N_4__c</fullName>
        <label>CCM IT2 N-4</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT3_N_2__c</fullName>
        <label>CCM IT3 N-2</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT3_N_3__c</fullName>
        <label>CCM IT3 N-3</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT3_N_4__c</fullName>
        <label>CCM IT3 N-4</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT4_N_2__c</fullName>
        <label>CCM IT4 N-2</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT4_N_3__c</fullName>
        <label>CCM IT4 N-3</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT4_N_4__c</fullName>
        <label>CCM IT4 N-4</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT5_N_2__c</fullName>
        <label>CCM IT5 N-2</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT5_N_3__c</fullName>
        <label>CCM IT5 N-3</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT5_N_4__c</fullName>
        <label>CCM IT5 N-4</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT6_N_2__c</fullName>
        <label>CCM IT6 N-2</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT6_N_3__c</fullName>
        <label>CCM IT6 N-3</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCMIT6_N_4__c</fullName>
        <label>CCM IT6 N-4</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CTN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CTN</label>
        <referenceTo>AppATctn__c</referenceTo>
        <relationshipLabel>Feuilles de calcul</relationshipLabel>
        <relationshipName>Feuilles_de_calcul</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EtablissementConcerne__c</fullName>
        <label>Etablissement concerné</label>
        <referenceTo>AppATetablissement__c</referenceTo>
        <relationshipLabel>Feuilles de calcul</relationshipLabel>
        <relationshipName>FeuillesCalcul</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Majoration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Majoration</label>
        <referenceTo>AppATmajoration__c</referenceTo>
        <relationshipLabel>Feuilles de calcul</relationshipLabel>
        <relationshipName>Feuilles_de_calcul</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MasseSalarialeAnneeN_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Masse salariale Année N-2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AppATmasseSalariale__c.EtablissementConcerne__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.EtablissementConcerne__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AppATmasseSalariale__c</referenceTo>
        <relationshipLabel>Feuilles de calcul (Masse salariale N-2)</relationshipLabel>
        <relationshipName>Feuilles_de_calcul1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MasseSalarialeAnneeN_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Masse salariale Année N-3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AppATmasseSalariale__c.EtablissementConcerne__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.EtablissementConcerne__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AppATmasseSalariale__c</referenceTo>
        <relationshipLabel>Feuilles de calcul (Masse salariale N-3)</relationshipLabel>
        <relationshipName>Feuilles_de_calcul2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MasseSalarialeAnneeN_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Masse salariale Année N-4</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AppATmasseSalariale__c.EtablissementConcerne__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.EtablissementConcerne__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AppATmasseSalariale__c</referenceTo>
        <relationshipLabel>Feuilles de calcul (Masse salariale N-4)</relationshipLabel>
        <relationshipName>Feuilles_de_calcul</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_de_feuille_de_calcul__c</fullName>
        <label>Type de feuille de calcul</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initiale</fullName>
                </value>
                <value>
                    <fullName>Rectifiée</fullName>
                </value>
                <value>
                    <fullName>Simulée</fullName>
                </value>
                <value>
                    <fullName>Refacturation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Feuille de calcul</label>
    <nameField>
        <label>Nom de la feuille de calcul</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feuilles de calcul</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppATmajoration__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>Annee__c</fullName>
        <label>Année</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Majoration__c</fullName>
        <label>Majoration</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>Majoration</label>
    <nameField>
        <label>Nom de Majoration</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Majorations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/AppATmasseSalariale__c.object
<CustomObject>
    <description>APPLICATION AT</description>
    <fields>
        <fullName>Annee__c</fullName>
        <label>Année</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EtablissementConcerne__c</fullName>
        <label>Etablissement concerné</label>
        <referenceTo>AppATetablissement__c</referenceTo>
        <relationshipLabel>Masses salariales</relationshipLabel>
        <relationshipName>MassesSalariales</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Masse salariale</label>
    <nameField>
        <label>Nom de la masse salariale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Masses salariales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/AppATfeuilleCalculCtrl.cls
public class AppATfeuilleCalculCtrl {

    private AppATfeuilleCalcul__c feuilleCalcul;
    
    public List<SelectOption> CTNtypes {get; set;}
    public String selectedCTNtype {get; set;}
    
    public String clonedFromYear {get; set;}
    
/*  public List<SelectOption> recordTypes {get; set;}
    public String selectedRecordType {get; set;}
    */
    public AppATfeuilleCalculCtrl(ApexPages.standardController stdCtrl){
        
        this.feuilleCalcul = (AppATfeuilleCalcul__c) stdCtrl.getRecord();
        
        
        if(ApexPages.currentPage().getParameters().get('clone') == '1'){
                this.feuilleCalcul.Id = null;
                this.selectedCTNtype = this.feuilleCalcul.CTN__r.TypeCTN__c;
                this.feuilleCalcul.CTN__c = null;
                this.feuilleCalcul.Majoration__c = null;
                this.clonedFromYear = this.feuilleCalcul.AnneeFeuilleCalcul__c;
                
        }
        else{
            AppATetablissement__c etab = [SELECT Id, AlsaceMoselle__c FROM AppATetablissement__c WHERE Id = :this.feuilleCalcul.EtablissementConcerne__c][0];
                
            this.feuilleCalcul.AlsaceMoselle__c = etab.AlsaceMoselle__c;
        }
        
        if(this.feuilleCalcul.Id == null){
            this.initFCnew();
        }
    }
    
    
    private void initFCnew(){

        //Initialise le menu déroulant des Type de CTN
        this.CTNtypes = new List<SelectOption>();
        for(Schema.PicklistEntry pe : AppATctn__c.TypeCTN__c.getDescribe().getPicklistValues())
            this.CTNtypes.add( new SelectOption(pe.getValue(), pe.getLabel()) );
            
    

    }
    
    public PageReference create(){
        
        
        //Récupération du CTN
        List<AppATctn__c> CTNs = [SELECT Id, Annee__c FROM AppATctn__c WHERE Annee__c <= :this.feuilleCalcul.AnneeFeuilleCalcul__c AND TypeCTN__c = :this.selectedCTNtype ORDER BY Annee__c DESC LIMIT 1];
        
        //Cherche un CTN de l'année de la feuille de calcul, Si c'est une feuille Simulée, alors on accepte de prendre le dernier CTN en date même si l'année est inférieure
        if(!CTNs.isEmpty() && (CTNs[0].Annee__c == this.feuilleCalcul.AnneeFeuilleCalcul__c || this.feuilleCalcul.Type_de_feuille_de_calcul__c == 'Simulée')){
                this.feuilleCalcul.CTN__c = CTNs[0].Id;
        }
        else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Aucun CTN trouvé pour le type "' + this.selectedCTNtype + '"'));
                return null;
        }
        
        
        //Récupération des masses salariales
        Integer annee = Integer.valueOf(this.feuilleCalcul.AnneeFeuilleCalcul__c);
        for(AppATmasseSalariale__c ms : [SELECT Id, Annee__c FROM AppATmasseSalariale__c WHERE EtablissementConcerne__c = :this.feuilleCalcul.EtablissementConcerne__c]){
            if(ms.Annee__c == String.valueOf( annee - 2 ))
                this.feuilleCalcul.MasseSalarialeAnneeN_2__c = ms.Id;
            else if(ms.Annee__c == String.valueOf( annee - 3 ))
                this.feuilleCalcul.MasseSalarialeAnneeN_3__c = ms.Id;
            else if(ms.Annee__c == String.valueOf( annee - 4 ))
                this.feuilleCalcul.MasseSalarialeAnneeN_4__c = ms.Id;
        }
        if(this.feuilleCalcul.MasseSalarialeAnneeN_2__c == null || this.feuilleCalcul.MasseSalarialeAnneeN_3__c == null || this.feuilleCalcul.MasseSalarialeAnneeN_4__c == null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Une ou plusieurs masses salariales sont manquantes'));
            return null;
        }
        
        
        //Récupération de la majoration
        List<AppATmajoration__c> majorations = [SELECT Id, Annee__c FROM AppATmajoration__c WHERE Annee__c <= :this.feuilleCalcul.AnneeFeuilleCalcul__c ORDER BY Annee__c DESC LIMIT 1];
        
        //Cherche une Majoration de l'année de la feuille de calcul, Si c'est une feuille Simulée, alors on accepte de prendre la derniere Majoration en date même si l'année est inférieure
        if(!majorations.isEmpty() && (majorations[0].Annee__c == this.feuilleCalcul.AnneeFeuilleCalcul__c || this.feuilleCalcul.Type_de_feuille_de_calcul__c == 'Simulée')){
                this.feuilleCalcul.Majoration__c = majorations[0].Id;
        }
        else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Aucune majoration trouvée'));
                return null;
        }
        
        
        system.debug(this.clonedFromYear);
        system.debug(this.feuilleCalcul.AnneeFeuilleCalcul__c);
        
                //Si on fait un clone en choisissant l'année suivante: On décale tous les CCM IP/IT d'une année        
        if(this.clonedFromYear != null && Integer.valueOf(this.clonedFromYear) == Integer.valueOf(this.feuilleCalcul.AnneeFeuilleCalcul__c) - 1){
                this.shiftCCM();
        }
        
        try{
                insert feuilleCalcul;
                PageReference retPage = Page.AppATfeuilleCalculEdit;
                retPage.getParameters().put('id', feuilleCalcul.Id);
                retPage.setRedirect(true);
                return retPage;
        }
        catch(System.DmlException e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, e.getDmlMessage(0)));
                return null;
        }
        
       
    }
    
    
    
    /**
     * Décales tous les CCM IT/IP d'une année (N-3 récupère les valeurs de N-4, N-3 récupère les valeurs de N-2, N-2 est vidée)
     */
    private void shiftCCM(){
        
        this.feuilleCalcul.CCMIT1_N_4__c = this.feuilleCalcul.CCMIT1_N_3__c;
        this.feuilleCalcul.CCMIT2_N_4__c = this.feuilleCalcul.CCMIT2_N_3__c;
        this.feuilleCalcul.CCMIT3_N_4__c = this.feuilleCalcul.CCMIT3_N_3__c;
        this.feuilleCalcul.CCMIT4_N_4__c = this.feuilleCalcul.CCMIT4_N_3__c;
        this.feuilleCalcul.CCMIT5_N_4__c = this.feuilleCalcul.CCMIT5_N_3__c;
        this.feuilleCalcul.CCMIT6_N_4__c = this.feuilleCalcul.CCMIT6_N_3__c;
        this.feuilleCalcul.CCMIP1_N_4__c = this.feuilleCalcul.CCMIP1_N_3__c;
        this.feuilleCalcul.CCMIP2_N_4__c = this.feuilleCalcul.CCMIP2_N_3__c;
        this.feuilleCalcul.CCMIP3_N_4__c = this.feuilleCalcul.CCMIP3_N_3__c;
        this.feuilleCalcul.CCMIP4_N_4__c = this.feuilleCalcul.CCMIP4_N_3__c;
        
        this.feuilleCalcul.CCMIT1_N_3__c = this.feuilleCalcul.CCMIT1_N_2__c;
                this.feuilleCalcul.CCMIT2_N_3__c = this.feuilleCalcul.CCMIT2_N_2__c;
                this.feuilleCalcul.CCMIT3_N_3__c = this.feuilleCalcul.CCMIT3_N_2__c;
                this.feuilleCalcul.CCMIT4_N_3__c = this.feuilleCalcul.CCMIT4_N_2__c;
                this.feuilleCalcul.CCMIT5_N_3__c = this.feuilleCalcul.CCMIT5_N_2__c;
                this.feuilleCalcul.CCMIT6_N_3__c = this.feuilleCalcul.CCMIT6_N_2__c;
                this.feuilleCalcul.CCMIP1_N_3__c = this.feuilleCalcul.CCMIP1_N_2__c;
                this.feuilleCalcul.CCMIP2_N_3__c = this.feuilleCalcul.CCMIP2_N_2__c;
                this.feuilleCalcul.CCMIP3_N_3__c = this.feuilleCalcul.CCMIP3_N_2__c;
                this.feuilleCalcul.CCMIP4_N_3__c = this.feuilleCalcul.CCMIP4_N_2__c;
                
                this.feuilleCalcul.CCMIT1_N_2__c = null;
                this.feuilleCalcul.CCMIT2_N_2__c = null;
                this.feuilleCalcul.CCMIT3_N_2__c = null;
                this.feuilleCalcul.CCMIT4_N_2__c = null;
                this.feuilleCalcul.CCMIT5_N_2__c = null;
                this.feuilleCalcul.CCMIT6_N_2__c = null;
                this.feuilleCalcul.CCMIP1_N_2__c = null;
                this.feuilleCalcul.CCMIP2_N_2__c = null;
                this.feuilleCalcul.CCMIP3_N_2__c = null;
                this.feuilleCalcul.CCMIP4_N_2__c = null;
    }
    
}