gac_sb/objects/AppCIRmission__c.object
<CustomObject>
    <description>APPLICATION CIR - Les missions CIR d&apos;un client</description>
    <fields>
        <fullName>Date_facturation_GAC__c</fullName>
        <label>Date facturation GAC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Montant_remuneration_final__c</fullName>
        <label>Chiffre d&apos;affaire</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>CASE( Phase__c , &apos;Inactif / en attente de renouvellement&apos;, &apos;Inactive&apos;, &apos;Inactif / en attente de lancement&apos;, &apos;Inactive&apos;, &apos;Terminée&apos;, &apos;Terminée&apos;, &apos;Terminée - Dossier à 0&apos;, &apos;Terminée&apos;, &apos;Active&apos;)</formula>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <label>[OLD] Mission CIR</label>
    <nameField>
        <label>Nom de la mission CIR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>[OLD] Missions CIR</pluralLabel>
    <recordTypes>
        <fullName>AS</fullName>
        <active>true</active>
        <label>AS</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/Facture__c.object
<CustomObject>
    <description>SF CONSULTING - permet de créer des factures</description>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Factures</relationshipLabel>
        <relationshipName>Factures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Date de facture</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En attente</fullName>
                    <default>true</default>
                    <label>En attente</label>
                </value>
                <value>
                    <fullName>Validée</fullName>
                </value>
                <value>
                    <fullName>Envoyée</fullName>
                </value>
                <value>
                    <fullName>Soldée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Facture</label>
    <nameField>
        <label>N° Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOvalo__c.object
<CustomObject>
    <fields>
        <fullName>ChiffreAffaire__c</fullName>
        <label>Chiffre d&apos;affaire</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_facturation_GAC__c</fullName>
        <label>Date facturation GAC</label>
        <type>Date</type>
    </fields>
    <label>Valorisation</label>
    <nameField>
        <label>Nom de la valorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valorisations</pluralLabel>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Prevision_de_facturation__c.object
<CustomObject>
    <description>SF CONSULTING - permet de saisir des planifications de facturation</description>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>Planificiations_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_prevue__c</fullName>
        <label>Date prévue</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dossier_rejete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Permet d&apos;identifier les planifications de facturation CANADA dont les dossiers ont été rejetés.</description>
        <inlineHelpText>Pour cocher cette case, la prévision HT doit être égale à &quot; 0 &quot; et le type de prévision doit être égale à &quot; Prévision de facturation &quot;</inlineHelpText>
        <label>Dossier rejeté</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Etape__c</fullName>
        <label>Etape</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Demande des documents en cours</fullName>
                </value>
                <value>
                    <fullName>Analyse des documents en cours</fullName>
                </value>
                <value>
                    <fullName>Attente validation client</fullName>
                </value>
                <value>
                    <fullName>Avis de crédit obtenu</fullName>
                </value>
                <value>
                    <fullName>Blocage client</fullName>
                </value>
                <value>
                    <fullName>Calcul en cours</fullName>
                </value>
                <value>
                    <fullName>Contrôle à venir</fullName>
                </value>
                <value>
                    <fullName>Contrôle en cours</fullName>
                </value>
                <value>
                    <fullName>Déduction réalisée</fullName>
                </value>
                <value>
                    <fullName>Envoi du projet de réclamation au client</fullName>
                </value>
                <value>
                    <fullName>Préparation de la réclamation</fullName>
                </value>
                <value>
                    <fullName>Dépôt de la réclamation</fullName>
                </value>
                <value>
                    <fullName>Documents à collecter</fullName>
                </value>
                <value>
                    <fullName>Dossier transmis aux organismes</fullName>
                </value>
                <value>
                    <fullName>Mémoire adressé au TA</fullName>
                </value>
                <value>
                    <fullName>En cours d’instruction</fullName>
                </value>
                <value>
                    <fullName>Mise en oeuvre à valider</fullName>
                </value>
                <value>
                    <fullName>Paramétrage en cours</fullName>
                </value>
                <value>
                    <fullName>Paramétré</fullName>
                </value>
                <value>
                    <fullName>Passage en CRA</fullName>
                </value>
                <value>
                    <fullName>Passage en TASS</fullName>
                </value>
                <value>
                    <fullName>Projet de mémoire TA adressé au client</fullName>
                </value>
                <value>
                    <fullName>Projet de mémoire TA validé par le client</fullName>
                </value>
                <value>
                    <fullName>Proposition de saisine du TA envoyée au client</fullName>
                </value>
                <value>
                    <fullName>Refusée</fullName>
                </value>
                <value>
                    <fullName>Validation de la saisine du TA par le client</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
                <value>
                    <fullName>Dossier à 0</fullName>
                </value>
                <value>
                    <fullName>Autres</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facture associée</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Mission__c</field>
                <operation>equals</operation>
                <valueField>Facture__c.Mission__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facture__c</referenceTo>
        <relationshipLabel>Planifications de facturation liées</relationshipLabel>
        <relationshipName>Planificiations_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HGNF_comptabilise__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Case permettant de remplir les champs date d&apos;HGNF et montant HGNF</description>
        <label>HGNF comptabilisé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mission_Inno_Advance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Permet de relier la prévision de facturation avec la mission Inno-AD correspondante</inlineHelpText>
        <label>Mission Inno-Advance</label>
        <referenceTo>AppCIRmission__c</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>Planifications_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prevision_HT__c</fullName>
        <label>Prévision HT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Facturée</fullName>
                </value>
                <value>
                    <fullName>Prévue</fullName>
                </value>
                <value>
                    <fullName>HGNF</fullName>
                </value>
                <value>
                    <fullName>Rejetée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Statut_facture__c</fullName>
        <description>Champ pour aider le récap de cumul a dire si la facture est émise ou non</description>
        <formula>TEXT(Facture__r.Statut__c)</formula>
        <label>Statut facture</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValoINNOadvance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Valorisation INNO Advance</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>PlanificationsFacturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Planification de facturation</label>
    <nameField>
        <displayFormat>Planif-{000000}</displayFormat>
        <label>N° Planification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planifications de facturation</pluralLabel>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <description>Prévision de facturation CIR</description>
        <label>CIR</label>
    </recordTypes>
    <recordTypes>
        <fullName>IL</fullName>
        <active>true</active>
        <label>IL</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/Prevision_de_facturationHandler.cls
public with sharing class Prevision_de_facturationHandler implements ITrigger{

	/*
	*  La liste des Id de contrat impactés
	*  Pour mettre à jour la date de 1ère planif
	*/
	private List<Id> contractToUpdateIds = new List<Id>();
	
	/*
	*  La liste des Id de planif delete à ne pas utiliser
	*  Pour mettre à jour la date de 1ère planif
	*/
	private List<Id> planifDeletedIds = new List<Id>();
	
	private static map<id,Map<string,decimal>> insertedPrevisionsTotals;
	
	private id[] factureToUp = new List<Id>();

    /*
    *	@deprecated
    *   La liste des Id Mission CIR (INNO Advance) impactés
    *   Pour mettre à jour le Montant rémunération brut et la Date de facturation GAC
    private Set<Id> missionsCirIds = new Set<Id>(); 
    */
    
    /*
    *   La liste des Id de Valo CIR (INNO Advance) impactés
    *   Pour mettre à jour le Chiffre d'affaire et la Date de facturation GAC
    */
    private Set<Id> valosCirIds = new Set<Id>();
    
    

    //Si isActive est a false, on ne fera pas de mise a jour à vide des facture associés à ces planifs
    //Sert pour éviter la récursivité aevc Facture HANDLER
	public static boolean isActive;

	static{
		isActive = true;
		if(insertedPrevisionsTotals == null)
			insertedPrevisionsTotals = new map<id,Map<string,decimal>>();
	}

    public Prevision_de_facturationHandler(){
    }
    
    public void bulkBefore(){
    }
    
    public void bulkAfter(){
    }
        
    /**
    */
    public void beforeInsert(SObject so){
		Prevision_de_facturation__c planif = (Prevision_de_facturation__c) so;
		// 012D0000000kP3i = IL
		planif.Statut__c = getPlanifStatus(planif);
		//EDIT DIDIER 18/10/13
		if(!insertedPrevisionsTotals.containsKey( planif.contrat__c)){
			insertedPrevisionsTotals.put( planif.contrat__c,new Map<string,decimal>{'Prévue'=>0,'Facturée'=>0});
		}
        
        
        //On fait le ca facturé
		if(planif.Statut__c == 'Prévue' || ( planif.Statut__c == 'Facturée' && planif.statut_facture__c != 'En attente' )  ) //On fait le CA facturé réel
			insertedPrevisionsTotals.get( planif.contrat__c ).put(planif.Statut__c, insertedPrevisionsTotals.get(planif.contrat__c).get(planif.Statut__c) * 1 + 1 * planif.Prevision_HT__c);
        //Fin edit
    }
    
    public void beforeUpdate(SObject oldSo, SObject so){
		Prevision_de_facturation__c planif = (Prevision_de_facturation__c) so;
		// 012D0000000kP3i = IL
		planif.Statut__c = getPlanifStatus(planif);
		if(planif.Date_prevue__c != planif.Facture__r.Date__c && planif.Facture__r.Date__c != null)
			planif.Date_prevue__c = planif.Facture__r.Date__c;
    }
    
    public void beforeDelete(SObject so){
    }
    
    
    
    public void afterInsert(SObject so){
		Prevision_de_facturation__c planif = (Prevision_de_facturation__c) so;
		
		this.contractToUpdateIds.add(planif.Contrat__c);
		
		if(so.get('facture__c') != null)
			factureToUp.add(planif.facture__c);
		
		// @deprecated
		// if(planif.Mission_Inno_Advance__c != null)
		// 	missionsCirIds.add(planif.Mission_Inno_Advance__c);
			
		if(planif.ValoINNOadvance__c != null)
			valosCirIds.add(planif.ValoINNOadvance__c);
    }
    
    
    
    public void afterUpdate(SObject oldSo, SObject so){
      
		Prevision_de_facturation__c oldPlanif = (Prevision_de_facturation__c) oldSo;
		Prevision_de_facturation__c planif = (Prevision_de_facturation__c) so;
		
		this.contractToUpdateIds.add(planif.Contrat__c);
		
		if(oldPlanif.facture__c != null)
			factureToUp.add(oldPlanif.facture__c);
		if(planif.facture__c != null)
			factureToUp.add(planif.facture__c);
		
		if(oldPlanif.Contrat__c != planif.Contrat__c)
			this.contractToUpdateIds.add(oldPlanif.Contrat__c);
		
		// @deprecated
		// if(planif.Mission_Inno_Advance__c != null)
		// 	missionsCirIds.add(planif.Mission_Inno_Advance__c);
		// if(oldPlanif.Mission_Inno_Advance__c != null)
		// 	missionsCirIds.add(oldPlanif.Mission_Inno_Advance__c);
			
		if(planif.ValoINNOadvance__c != null)
			valosCirIds.add(planif.ValoINNOadvance__c);
			
		if(oldPlanif.ValoINNOadvance__c != null)
			valosCirIds.add(oldPlanif.ValoINNOadvance__c);
            
    }
    
    
    
    
    public void afterDelete(SObject so){
      
		Prevision_de_facturation__c planif = (Prevision_de_facturation__c) so;
		
		if(planif.Date_prevue__c != null){
			this.contractToUpdateIds.add(planif.Contrat__c);
			this.planifDeletedIds.add(planif.Id);
		}

		
		if(planif.Facture__c != null)
			factureToUp.add(planif.facture__c);

    	// @deprecated
		// if(planif.Mission_Inno_Advance__c != null)
		// 	missionsCirIds.add(planif.Mission_Inno_Advance__c);
			
		if(planif.ValoINNOadvance__c != null)
			valosCirIds.add(planif.ValoINNOadvance__c);
    }
    
    
    
    
    /**
     * andFinally
     *
     * This method is called once all records have been processed by the trigger. Use this 
     * method to accomplish any final operations such as creation or updates of other records.
     */
    public void andFinally(){
		System.debug('###IN Prev de facturation handler');
		system.debug(insertedPrevisionsTotals);
		/*
		*  Récupère tous les contrats dont il faut recalculer la date de 1ere planif
		*/
		List<Contract> contratsToMaj = [SELECT Id,
												Date_1ere_planification__c,
												CA_Facture__c,
												CA_Reste_a_facturer__c,
												(SELECT Id,
													Date_prevue__c,
													statut__c,
													Prevision_HT__c,
													statut_facture__c
												FROM Planificiations_de_facturation__r 
												WHERE Id NOT IN :this.planifDeletedIds)
											FROM Contract 
											WHERE Id IN :this.contractToUpdateIds];
											
		for(Contract contrat : contratsToMaj){
			contrat.Date_1ere_planification__c = null;
			/*
			EDIT DIDIER 18/10/13 MAJ des totaux de facturation sur le contrat
			*/
			Decimal CA_Facture = 0 ;
			Decimal CA_resteafacturer = 0;
			if(insertedPrevisionsTotals.containsKey(contrat.id)){
				CA_Facture = insertedPrevisionsTotals.get(contrat.id).get('Facturée');
				CA_resteafacturer = insertedPrevisionsTotals.get(contrat.id).get('Prévue');
			}
			/*
			FIN EDIT DIDIER 18/10/13 MAJ des totaux de facturation sur le contrat
			*/
			for(Prevision_de_facturation__c pr : contrat.Planificiations_de_facturation__r){
				
				/*
				EDIT DIDIER 18/10/13 MAJ des totaux de facturation sur le contrat
				*/
				if(pr.Statut__c == 'Prévue')
					CA_resteafacturer += pr.Prevision_HT__c;
				else if(pr.Statut_facture__c != 'En attente') //On prend le facturé réel
					CA_Facture += pr.Prevision_HT__c;
				/*
				Fin EDIT DIDIER
				*/
				if(contrat.Date_1ere_planification__c == null)
					contrat.Date_1ere_planification__c = pr.Date_prevue__c;
				if(contrat.Date_1ere_planification__c != null){
					if(pr.Date_prevue__c < contrat.Date_1ere_planification__c)
						contrat.Date_1ere_planification__c = pr.Date_prevue__c;
				}
			}
			/*
			EDIT DIDIER 18/10/13 MAJ des totaux de facturation sur le contrat
			*/
			contrat.CA_Facture__c = CA_Facture;
			contrat.CA_Reste_a_facturer__c = CA_resteafacturer;
			/*
			Fin EDIT DIDIER
			*/
		}
		//Mise a jour des contrats liés
		if(contratsToMaj.size() > 0)
			update contratsToMaj;
		
		//Mise a jour des factures de la planif (champs prestataire)
		if(!factureToUp.isEmpty() && isActive){
			try{
				update [select id from facture__c where id in : factureToUp];
			}
			catch(Exception e){
				String Message = e.getMessage();
				if(Message.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION,')){
					Message = Message.replaceAll('.*FIELD_CUSTOM_VALIDATION_EXCEPTION,','');
				}
				trigger.new.get(0).addError('Une erreur est survenue sur la facture liée. '+Message);
			}
		}
		
		
		/*
		*	@deprecated
		*   Mises à jour des missions CIR d'INNO Advance, champs:
		*   - Montant rémunération brut
		*   - Date de facturation GAC
		*
		
		//Création des copies des missions CIR à updater
		Map<Id, AppCIRmission__c> missionsCirRecords = new Map<Id, AppCIRmission__c>();
		
		for(Id missionId : this.missionsCirIds){
			missionsCirRecords.put(missionId, new AppCIRmission__c( Id = missionId, 
			Montant_remuneration_final__c = 0,
			Date_facturation_GAC__c = null
			));
		}
		
		//Recupère toutes les planifs rattachés aux missionsIds
		AppCIRmission__c missionCIR;
		for(Prevision_de_facturation__c planif : [SELECT Id, Mission_Inno_Advance__c, Prevision_HT__c, Date_prevue__c FROM Prevision_de_facturation__c WHERE Mission_Inno_Advance__c IN :missionsCirIds AND RecordType.DeveloperName = 'CIR' order by Date_prevue__c]){
		
			missionCIR = missionsCirRecords.get(planif.Mission_Inno_Advance__c);
			
			//MAJ du champ Montant rémunération brut
			missionCIR.Montant_remuneration_final__c += planif.Prevision_HT__c;
			
			//MAJ du champ Date de facturation GAC (à la date de la 1ere planif)
			if(missionCIR.Date_facturation_GAC__c == null)
				missionCIR.Date_facturation_GAC__c = planif.Date_prevue__c;
			
		}
		
		//Update des missions CIR
		update missionsCirRecords.values();
		*/
		
		
		/*
		*   Mises à jour des valorisation CIR d'INNO Advance, champs:
		*   - Chiffre d'affaire
		*   - Date de facturation GAC
		*/
		
		//Création des copies des missions CIR à updater
		Map<Id, INNOvalo__c> valosCirRecords = new Map<Id, INNOvalo__c>();
		
		for(Id valoId : this.valosCirIds){
			valosCirRecords.put(valoId, new INNOvalo__c( Id = valoId, 
														ChiffreAffaire__c = 0,
														Date_facturation_GAC__c = null
			));
		}
		
		//Recupère toutes les planifs rattachés aux missionsIds
		INNOvalo__c valoCIR;
		for(Prevision_de_facturation__c planif : [SELECT Id, ValoINNOadvance__c, Prevision_HT__c, Date_prevue__c FROM Prevision_de_facturation__c WHERE ValoINNOadvance__c IN :valosCirIds AND RecordType.DeveloperName = 'CIR' order by Date_prevue__c]){
		
			valoCIR = valosCirRecords.get(planif.ValoINNOadvance__c);
			
			//MAJ du champ Montant rémunération brut
			valoCIR.ChiffreAffaire__c += planif.Prevision_HT__c;
			
			//MAJ du champ Date de facturation GAC (à la date de la 1ere planif)
			if(valoCIR.Date_facturation_GAC__c == null)
				valoCIR.Date_facturation_GAC__c = planif.Date_prevue__c;
			
		}
		
		//Update des valos CIR
		update valosCirRecords.values();
		
		
		system.debug('###OUT Prevision de facturationhandler');
    }
    
    
    
	private static String getPlanifStatus(Prevision_de_facturation__c planif){
		
		if(planif.Facture__c != null)
			return 'Facturée';
		else if(planif.Dossier_rejete__c && planif.RecordTypeId == '012D0000000kZ4L')       //Recordtype CIR CANADA
			return 'Rejetée';
		else if(planif.HGNF_comptabilise__c)
			return 'HGNF';
		else if (planif.Etape__c == 'Dossier à 0' && planif.RecordTypeId == '012D0000000kP3i')      //Recordtype IL, Ne pas fusionner avec le "else if(planif.Dossier_rejete__c)" car l'ordre a son importance, on doit d'abord vérifier si HGNF
			return 'Rejetée';
		else
			return 'Prévue';
	
	}
}