gac_sb/objects/AppCIRdepensePersonnel__c.object
<CustomObject>
    <description>APPLICATION CIR - Les dépenses de prestation de l&apos;application CIR. Comprend les Salariés, les Jeunes docteurs, les Mises à dispositions, les Normalisations et les Veilles (de type dépense de personnel)</description>
    <fields>
        <fullName>Heures_RD_option1__c</fullName>
        <label>Heures R&amp;D option 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option2__c</fullName>
        <label>Heures R&amp;D option 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option3__c</fullName>
        <label>Heures R&amp;D option 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>[OLD] Dépense de personnel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses de personnel</pluralLabel>
    <recordTypes>
        <fullName>salarie</fullName>
        <active>true</active>
        <label>Salariés</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppCIRpersonnelToProjet__c.object
<CustomObject>
    <description>APPLICATION CIR - Permet de saisir les heures travaillées par le personnel sur les différents projet ainsi que sur la veille, la prise et maintenance de brevet et la normalisation</description>
    <fields>
        <fullName>Depense_de_personnel__c</fullName>
        <label>Dépense de personnel</label>
        <referenceTo>AppCIRdepensePersonnel__c</referenceTo>
        <relationshipName>Depenses_de_personnel_to_projets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option1__c</fullName>
        <label>Heures R&amp;D option 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option2__c</fullName>
        <label>Heures R&amp;D option 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option3__c</fullName>
        <label>Heures R&amp;D option 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projet__c</fullName>
        <label>Projet</label>
        <referenceTo>AppCIRprojet__c</referenceTo>
        <relationshipName>Depenses_de_personnel_to_projets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>[OLD] Dépense de personnel to projet</label>
    <nameField>
        <displayFormat>PtP-{000000000}</displayFormat>
        <label>Nom de AppCIRpersonnelToProjet</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dépenses de personnel to projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppCIRprojet__c.object
<CustomObject>
    <description>APPLICATION CIR - Les projets CIR d&apos;une mission</description>
    <fields>
        <fullName>Heures_RD_option1__c</fullName>
        <description>Calculé automatiquement en fonction des dépenses de personnel rattachées au projet</description>
        <label>Heures R&amp;D option 1</label>
        <summarizedField>AppCIRpersonnelToProjet__c.Heures_RD_option1__c</summarizedField>
        <summaryFilterItems>
            <field>AppCIRpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryForeignKey>AppCIRpersonnelToProjet__c.Projet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option2__c</fullName>
        <description>Calculé automatiquement en fonction des dépenses de personnel rattachées au projet</description>
        <label>Heures R&amp;D option 2</label>
        <summarizedField>AppCIRpersonnelToProjet__c.Heures_RD_option2__c</summarizedField>
        <summaryFilterItems>
            <field>AppCIRpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryForeignKey>AppCIRpersonnelToProjet__c.Projet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option3__c</fullName>
        <description>Calculé automatiquement en fonction des dépenses de personnel rattachées au projet</description>
        <label>Heures R&amp;D option 3</label>
        <summarizedField>AppCIRpersonnelToProjet__c.Heures_RD_option3__c</summarizedField>
        <summaryFilterItems>
            <field>AppCIRpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryForeignKey>AppCIRpersonnelToProjet__c.Projet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Champ invisible pour l&apos;utilisateur, permet de savoir si l&apos;enregistrement est un &quot;vrai&quot; projet ou si c&apos;est un enregistrement qui est la juste pour rattacher des dépenses de personnel aux veilles, PM de brevet ou normalisation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>projet</fullName>
                    <default>true</default>
                    <label>projet</label>
                </value>
                <value>
                    <fullName>veille</fullName>
                </value>
                <value>
                    <fullName>brevetPM</fullName>
                </value>
                <value>
                    <fullName>normalisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>[OLD] Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOdepensePersonnel__c.object
<CustomObject>
    <fields>
        <fullName>Heures_RD_option1__c</fullName>
        <label>Heures R&amp;D option 1</label>
        <summarizedField>INNOpersonnelToProjet__c.Heures_RD_option1__c</summarizedField>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryForeignKey>INNOpersonnelToProjet__c.Depense_de_personnel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option2__c</fullName>
        <label>Heures R&amp;D option 2</label>
        <summarizedField>INNOpersonnelToProjet__c.Heures_RD_option2__c</summarizedField>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryForeignKey>INNOpersonnelToProjet__c.Depense_de_personnel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option3__c</fullName>
        <label>Heures R&amp;D option 3</label>
        <summarizedField>INNOpersonnelToProjet__c.Heures_RD_option3__c</summarizedField>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryForeignKey>INNOpersonnelToProjet__c.Depense_de_personnel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Depenses_de_personnel</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dépense de personnel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses de personnel</pluralLabel>
    <recordTypes>
        <fullName>salarie</fullName>
        <active>true</active>
        <label>Salariés</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOpersonnelToProjet__c.object
<CustomObject>
    <fields>
        <fullName>Depense_de_personnel__c</fullName>
        <label>Dépense de personnel</label>
        <referenceTo>INNOdepensePersonnel__c</referenceTo>
        <relationshipName>Depenses_de_personnel_to_projets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option1__c</fullName>
        <label>Heures R&amp;D option 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option2__c</fullName>
        <label>Heures R&amp;D option 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option3__c</fullName>
        <label>Heures R&amp;D option 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projet__c</fullName>
        <label>Projet</label>
        <referenceTo>INNOprojet__c</referenceTo>
        <relationshipName>Depenses_de_personnel_to_projets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dépense de personnel to projet</label>
    <nameField>
        <displayFormat>PtP-{000000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dépenses de personnel to projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOprojet__c.object
<CustomObject>
    <fields>
        <fullName>Heures_RD_option1__c</fullName>
        <description>Calculé automatiquement en fonction des dépenses de personnel rattachées au projet</description>
        <label>Heures R&amp;D option 1</label>
        <summarizedField>INNOpersonnelToProjet__c.Heures_RD_option1__c</summarizedField>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.UniteTempsDepensesPersonnel2__c</field>
            <operation>equals</operation>
            <value>Heures</value>
        </summaryFilterItems>
        <summaryForeignKey>INNOpersonnelToProjet__c.Projet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option2__c</fullName>
        <description>Calculé automatiquement en fonction des dépenses de personnel rattachées au projet</description>
        <label>Heures R&amp;D option 2</label>
        <summarizedField>INNOpersonnelToProjet__c.Heures_RD_option2__c</summarizedField>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.UniteTempsDepensesPersonnel2__c</field>
            <operation>equals</operation>
            <value>Heures</value>
        </summaryFilterItems>
        <summaryForeignKey>INNOpersonnelToProjet__c.Projet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option3__c</fullName>
        <description>Calculé automatiquement en fonction des dépenses de personnel rattachées au projet</description>
        <label>Heures R&amp;D option 3</label>
        <summarizedField>INNOpersonnelToProjet__c.Heures_RD_option3__c</summarizedField>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.UniteTempsDepensesPersonnel2__c</field>
            <operation>equals</operation>
            <value>Heures</value>
        </summaryFilterItems>
        <summaryForeignKey>INNOpersonnelToProjet__c.Projet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Champ invisible pour l&apos;utilisateur, permet de savoir si l&apos;enregistrement est un &quot;vrai&quot; projet ou si c&apos;est un enregistrement qui est la juste pour rattacher des dépenses de personnel aux veilles, PM de brevet ou normalisation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>projet</fullName>
                    <default>true</default>
                    <label>projet</label>
                </value>
                <value>
                    <fullName>veille</fullName>
                </value>
                <value>
                    <fullName>brevetPM</fullName>
                </value>
                <value>
                    <fullName>normalisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOdepensePersonnelCtrl.cls
public with sharing class INNOdepensePersonnelCtrl extends INNOmissionBaseCtrl {

	private ApexPages.standardController stdCtrl;

	
	public String tab {get; set;}
	
	
	//Les temps passé sur chaque projet par le salarié
	public INNOdepensePersonnelListCtrl.personnelProjets personnelProjets {get; set;}
	
	//La clé est IdDuSalarié_IdDuProjet
	private transient Map<String, INNOpersonnelToProjet__c> personnelsToProjet;
	
	//Tous les projets de la mission
	public Map<Id, INNOprojet__c> allProjects {get; set;}
	
	//Utile pour pouvoir boucler correctement dans la page par ca ne fonctionne pas correctement quand on boucle sur "projets" (car static)
	public List<Id> projetsIds {get; set;}
	
	public String listPageURL {get; set;}
	
	

	public INNOdepensePersonnelCtrl(ApexPages.standardController stdCtrl){
		this.stdCtrl = stdCtrl;
		
		this.tab = ApexPages.currentPage().getParameters().get('tab');

		if(this.tab == null)
			this.tab = 'salarie';
			
		
		this.personnelsToProjet = new Map<String, INNOpersonnelToProjet__c>();
		
		INNOdepensePersonnel__c depensePersonnel = (INNOdepensePersonnel__c) this.stdCtrl.getRecord();
		
		this.initAllProjets();
		
		if( ApexPages.currentPage().getUrl().startsWith('/apex/INNOdepensePersonnelEdit') ){
				
			///Si c'est une NOUVELLE depense de personnel
			if(depensePersonnel.Id == null){
				depensePersonnel.Valorisation__c = this.valoId;		
				depensePersonnel.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'INNOdepensePersonnel__c' AND DeveloperName = :this.tab LIMIT 1][0].Id;
			}
			
			//On initialise le menu deroulant des departements
			this.initDepartements();

		}
		
		//En cas d'update (pas à l'insert)
		if(depensePersonnel.Id != null){
			
			//On initialise pesonnelsToProjet
			for(INNOpersonnelToProjet__c pp : [SELECT Id, Name, Heures_RD_option1__c, Heures_RD_option2__c, Heures_RD_option3__c, Projet__c, Depense_de_personnel__c FROM INNOpersonnelToProjet__c WHERE Projet__r.Valorisation__c = :this.valoId AND Depense_de_personnel__c = :this.stdCtrl.getId()]){
				this.personnelsToProjet.put(pp.Depense_de_personnel__c + '_' + pp.Projet__c, pp);
			}
		}
		
		
		this.personnelProjets = new INNOdepensePersonnelListCtrl.personnelProjets(false, depensePersonnel, this.allProjects, this.personnelsToProjet);
		
		
		if(this.tab == 'brevetPM' || this.tab == 'veille')
			this.listPageURL = '/apex/INNOdepensePrestationPersonnelList';
		else
			this.listPageURL = '/apex/INNOdepensePersonnelList';
			
	}
	
	
	
	
	
	
	/**
	*	Effectue un save de la dépense de personnel mais aussi des heures travaillées sur les projets
	*	Pout la page Edit uniquement
	*/
	public PageReference savePersonnelEtHeuresTravaillees(){
		this.stdCtrl.save();

		List<INNOpersonnelToProjet__c> ptpToUpsert = new List<INNOpersonnelToProjet__c>();
		List<INNOpersonnelToProjet__c> ptpToDelete = new List<INNOpersonnelToProjet__c>();
		
		for(INNOpersonnelToProjet__c ptp : personnelProjets.projetsHeures.values()){

			//Si le depense de personnel to projet n'existait pas
			if(ptp.Id == null){
				if( (ptp.Heures_RD_option1__c == null ? 0 : ptp.Heures_RD_option1__c) + (ptp.Heures_RD_option2__c == null ? 0 : ptp.Heures_RD_option2__c) + (ptp.Heures_RD_option3__c == null ? 0 : ptp.Heures_RD_option3__c) > 0){
					ptp.Depense_de_personnel__c = this.stdCtrl.getId();
					ptpToUpsert.add(ptp);
				}
			}
			else{
				if((ptp.Heures_RD_option1__c == null ? 0 : ptp.Heures_RD_option1__c) + (ptp.Heures_RD_option2__c == null ? 0 : ptp.Heures_RD_option2__c) + (ptp.Heures_RD_option3__c == null ? 0 : ptp.Heures_RD_option3__c) > 0)
					ptpToUpsert.add(ptp);
				else
					ptpToDelete.add(ptp);
				
			}
		}
				
		
		upsert ptpToUpsert;
		delete ptpToDelete;
		
		
		PageReference retPage = new pageReference( '/apex/INNOdepensePersonnelView' );
		retPage.getParameters().put('id', this.stdCtrl.getId());
		retPage.getParameters().put('valoId', this.valoId);
		retPage.getParameters().put('tab', this.tab);
		retPage.setRedirect(true);
		return retPage; 
	}
	
	
	/**
	*	Supprime une depense de personnel et redirige vers la page de liste des projets
	*/
	public PageReference deleteAndRedirect(){
		Database.delete(this.stdCtrl.getId());
		
		PageReference retPage = new pageReference( this.listPageURL );
		retPage.getParameters().put('id', this.valoId);
		retPage.getParameters().put('valoId', this.valoId);
		retPage.getParameters().put('tab', this.tab);
		retPage.setRedirect(true);
		return retPage; 
	}
	
	
	/**
	*	Initialise la liste des projets de la mission, des "faux projets" de type PM brevet, Normalisation et Veille sont aussi à la fin de cette liste
	*/
	private void initAllProjets(){
		
		//Contiendra les "projets" de type veille, PM brevet et normalisation pour pouvoir les ajouter en fin de liste
		List<Id> projetsSpeciaux = new List<Id>();
		
		//On initialise les projets
		this.allProjects = new Map<Id, INNOprojet__c>();
		this.projetsIds = new List<Id>();
		for(INNOprojet__c p : [SELECT Id, Name, Type__c FROM INNOprojet__c WHERE Valorisation__c = :this.valoId ORDER BY Name]){
			this.allProjects.put(p.Id, p);
			
			if(p.Type__c == 'projet')
				this.projetsIds.add(p.Id);
			else
				projetsSpeciaux.add(p.Id);
		}
		//Rajoute les projets spéciaux (veille, PM brevet et normalisation) en fin de liste, sauf si on est sur les jeunes docteurs
		this.projetsIds.addAll(projetsSpeciaux);
		
	}
	
	
	
	
	
	/**
	*	Inner class correspondant à un salarié avec ses heures travaillées sur les projets
	*/
	// public class personnelProjets{
		
	// 	public Id salarieId {get; set;}
		
	// 	public String salarieName {get; set;}
		
	// 	//Les heures travaillées avec l'id du projet en clé
	// 	public Map<Id, AppCIRpersonnelToProjet__c> projetsHeures {get; set;}
		
	// 	public Decimal totalHeuresProjetsOptions1 {get; set;}
	// 	public Decimal totalHeuresProjetsOptions2 {get; set;}
	// 	public Decimal totalHeuresProjetsOptions3 {get; set;}
		
	// 	public Decimal totalHeuresOptions1 {get; set;}
	// 	public Decimal totalHeuresOptions2 {get; set;}
	// 	public Decimal totalHeuresOptions3 {get; set;}




	// 	//Constructeur		
	// 	public personnelProjets(AppCIRdepensePersonnel__c pers){
	// 		this.salarieId = pers.Id;
	// 		this.salarieName = pers.Name;
	// 		this.init();
	// 	}
		
	// 	//Constructeur
	// 	public personnelProjets(Id salarieId, String salarieName){
	// 		this.salarieId = salarieId;
	// 		this.salarieName = salarieName;
	// 		this.init();
	// 	}
		
		
		
	// 	public void init(){
			
	// 		AppCIRpersonnelToProjet__c persToProjetTemp;
			
	// 		this.projetsHeures = new Map<Id, AppCIRpersonnelToProjet__c>();
			
	// 		for(Id projetId : projets.keySet()){
	// 			persToProjetTemp = personnelsToProjet.get(this.salarieId + '_' + projetId);
				
	// 			if(persToProjetTemp != null){
	// 				this.projetsHeures.put(projetId, persToProjetTemp);
	// 			}
	// 			else{
	// 				this.projetsHeures.put(projetId, new AppCIRpersonnelToProjet__c(Projet__c = projetId, Depense_de_personnel__c = this.salarieId));
	// 			}
	// 		}
			
	// 		this.refreshTotauxHeures();
	// 	}
		
		
	// 	/**
	// 	*	Recalcul les colonnes de totaux des heures travaillées
	// 	*/
	// 	private void refreshTotauxHeures(){
	// 		this.totalHeuresOptions1 = this.totalHeuresOptions2 = this.totalHeuresOptions3 = this.totalHeuresProjetsOptions1 = this.totalHeuresProjetsOptions2 = this.totalHeuresProjetsOptions3 = 0;

	// 		for(AppCIRpersonnelToProjet__c ptp : this.projetsHeures.values()){
	// 			this.totalHeuresOptions1 += ptp.Heures_RD_option1__c != null ? ptp.Heures_RD_option1__c : 0;
	// 			this.totalHeuresOptions2 += ptp.Heures_RD_option2__c != null ? ptp.Heures_RD_option2__c : 0;
	// 			this.totalHeuresOptions3 += ptp.Heures_RD_option3__c != null ? ptp.Heures_RD_option3__c : 0;
				
	// 			if(projets.get(ptp.Projet__c).get('Type__c') == 'projet'){
	// 				this.totalHeuresProjetsOptions1 += ptp.Heures_RD_option1__c != null ? ptp.Heures_RD_option1__c : 0;
	// 				this.totalHeuresProjetsOptions2 += ptp.Heures_RD_option2__c != null ? ptp.Heures_RD_option2__c : 0;
	// 				this.totalHeuresProjetsOptions3 += ptp.Heures_RD_option3__c != null ? ptp.Heures_RD_option3__c : 0;
	// 			}
	// 		}
	// 	}
	// }
	

}