gac_sb/objects/AppCIRmission__c.object
<CustomObject>
    <description>APPLICATION CIR - Les missions CIR d&apos;un client</description>
    <fields>
        <fullName>Nombre_jours_theoriques_Audit__c</fullName>
        <label>Nombre de jours théoriques - Audit</label>
        <summarizedField>AppCIRequipeConsulting__c.Nombre_jours_theoriques_Audit__c</summarizedField>
        <summaryForeignKey>AppCIRequipeConsulting__c.Mission_CIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Controle__c</fullName>
        <label>Nombre de jours théoriques - Contrôle</label>
        <summarizedField>AppCIRequipeConsulting__c.Nombre_jours_theoriques_Controle__c</summarizedField>
        <summaryForeignKey>AppCIRequipeConsulting__c.Mission_CIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Justification__c</fullName>
        <label>Nombre de jours théoriques - Justif</label>
        <summarizedField>AppCIRequipeConsulting__c.Nombre_jours_theoriques_Justification__c</summarizedField>
        <summaryForeignKey>AppCIRequipeConsulting__c.Mission_CIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Valorisation__c</fullName>
        <label>Nombre de jours théoriques - Valo</label>
        <summarizedField>AppCIRequipeConsulting__c.Nombre_jours_theoriques_Valorisation__c</summarizedField>
        <summaryForeignKey>AppCIRequipeConsulting__c.Mission_CIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TempsTheoriquePlafond__c</fullName>
        <formula>IF(Entite__r.Contrat__r.Opportunite__r.renta_Total_jours_estimes_force__c != 0,
Entite__r.Contrat__r.Opportunite__r.renta_Total_jours_estimes_force__c,
Entite__r.Contrat__r.Opportunite__r.Total_jours_retenus__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Temps théorique plafond</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>[OLD] Mission CIR</label>
    <nameField>
        <label>Nom de la mission CIR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>[OLD] Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Audit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Audit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Controle__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Contrôle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Justification__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Justif</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Valorisation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Valo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Rôle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Consultant scientifique</fullName>
                    <default>true</default>
                    <label>Consultant scientifique</label>
                </value>
                <value>
                    <fullName>Consultant fiscaliste</fullName>
                </value>
                <value>
                    <fullName>Consultant extérieur</fullName>
                </value>
                <value>
                    <fullName>Rédacteur scientifique</fullName>
                </value>
                <value>
                    <fullName>Redacteur scientifique RO</fullName>
                    <label>Rédacteur scientifique RO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Nombre_jours_theoriques_Audit__c</fullName>
        <label>Nombre de jours théoriques - Audit</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Audit__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Controle__c</fullName>
        <label>Nombre de jours théoriques - Contrôle</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Controle__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Justification__c</fullName>
        <label>Nombre de jours théoriques - Justif</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Justification__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Valorisation__c</fullName>
        <label>Nombre de jours théoriques - Valo</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Valorisation__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TempsTheoriquePlafond__c</fullName>
        <formula>IF(Contrat__r.Opportunite__r.renta_Total_jours_estimes_force__c != 0,
Contrat__r.Opportunite__r.renta_Total_jours_estimes_force__c,
Contrat__r.Opportunite__r.Total_jours_retenus__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Temps théorique plafond</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/INNOequipeConsultingWithoutSharingCtrl.cls
public without sharing class INNOequipeConsultingWithoutSharingCtrl extends INNOmissionBaseCtrl{

	private INNOequipeConsulting__c membre;
	
	
	public Boolean isNew {get; set;}
	
	// public AppCIRmission__c mission {get; set;}
	
	//Le role qu'avait le membre avant la modification (dans le cas d'un update uniquement)
	private String previousRole = null;
	// private String previousUser = null;
	
	public Boolean erreurTempsTheorique {get; set;}
	
	
	
	public INNOequipeConsultingWithoutSharingCtrl(ApexPages.standardController stdCtrl){
		
		this.membre = (INNOequipeConsulting__c) stdCtrl.getRecord();
		
		this.isNew = (this.membre.Id == null);
		
		this.erreurTempsTheorique = false;
		
		if(this.isNew)
			this.membre.MissionCIR__c = ApexPages.currentPage().getParameters().get('missionId');
		else{
			this.previousRole = this.membre.Role__c;
		}
		
		this.mission = [SELECT Id, OwnerId, recordType.DeveloperName, TempsTheoriquePlafond__c FROM INNOmission__c WHERE Id = :this.membre.MissionCIR__c LIMIT 1][0];
	}
	
	
	
	public pageReference saveAndRedirect(){
		
		
		
		//Si le role d'avant était superviseur/manager et qu'il ne l'est plus, il faut vérifier qu'il reste encore au moins 1 superviseur/manager sur la mission
		if( !this.isNew && (this.previousRole == 'Superviseur' || this.previousRole == 'Superviseur/Consultant' || this.previousRole == 'Manager') && (this.membre.Role__c != 'Superviseur' && this.membre.Role__c != 'Superviseur/Consultant' && this.membre.Role__c != 'Manager')){
			//si il n'y a pas d'autres superviseur/manager sur la mission => erreur
			if([SELECT Id FROM INNOequipeConsulting__c WHERE MissionCIR__c = :this.mission.Id
														AND (Role__c = 'Superviseur' OR Role__c = 'Superviseur/Consultant' OR Role__c = 'Manager')
														AND Id != :this.membre.Id].size() == 0){
				this.membre.Role__c.addError('Il doit rester au moins 1 superviseur ou manager sur la mission');
				return null;
			}
		}
		
		//Si on essai d'inserer un membre qui est deja membre de l'equipe consulting de la mission => erreur
		if(this.isNew && [SELECT Id FROM INNOequipeConsulting__c WHERE MissionCIR__c = :this.mission.Id
																	AND Utilisateur__c = :this.membre.Utilisateur__c].size() > 0){
			
			this.membre.Utilisateur__c.addError('Cet utilisateur fait déjà parti de l\'équipe consulting de la mission');
			return null;
		}
		
		
		//Vérification que la somme des temps théoriques de l'équipe ne dépasse pas le temps théorique de la mission
		Decimal sommeTemps = 0;
		//somme de tous les autres membres
		for(AggregateResult aggr : [SELECT SUM(Nombre_jours_theoriques_Audit__c) audit, 
											SUM(Nombre_jours_theoriques_Valorisation__c) valo, 
											SUM(Nombre_jours_theoriques_Justification__c) justif, 
											SUM(Nombre_jours_theoriques_Controle__c) ctrl
									FROM INNOequipeConsulting__c 
									WHERE MissionCIR__c = :this.mission.Id
										AND Utilisateur__c != :this.membre.Utilisateur__c
									GROUP BY MissionCIR__c]){
										
			sommeTemps += this.getNotNullValue((Decimal) aggr.get('audit')) + this.getNotNullValue((Decimal) aggr.get('valo')) + this.getNotNullValue((Decimal) aggr.get('justif')) + this.getNotNullValue((Decimal) aggr.get('ctrl'));
        }
        //+ somme du membre courant
        sommeTemps += this.getNotNullValue(this.membre.Nombre_jours_theoriques_Audit__c) + this.getNotNullValue(this.membre.Nombre_jours_theoriques_Valorisation__c) + this.getNotNullValue(this.membre.Nombre_jours_theoriques_Justification__c) + this.getNotNullValue(this.membre.Nombre_jours_theoriques_Controle__c);

        if((sommeTemps > this.mission.TempsTheoriquePlafond__c || this.mission.TempsTheoriquePlafond__c == null) && !this.erreurTempsTheorique){
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Le nombre de jours théoriques de l\'ensemble de l\'équipe (' + sommeTemps + ') est supérieur à celui estimé sur l\'opportunité (' + this.mission.TempsTheoriquePlafond__c + ').<br /><strong>Vous pouvez forcer ce blocage en recliquant sur le bouton enregistrer.</strong>'));
            this.erreurTempsTheorique  = true;
    		return null;  
        }
        
		upsert this.membre;
		
		

		PageReference retPage;
		retPage = new PageReference('/apex/INNOmissionView');
		retPage.getParameters().put('id', this.mission.Id);
		retPage.getParameters().put('missionId', this.mission.Id);
		retPage.getParameters().put('sharingRecalc', '1');
		retPage.setRedirect(true);
		
		return retPage;
	}
	
	
	private Decimal getNotNullValue(Decimal value){
		return value == null ? 0 : value;
	}
	
	
}