gac_sb/objects/AppCIRdepartement__c.object
<CustomObject>
    <description>APPLICATION CIR - Les départements d&apos;une entité de l&apos;application CIR pour les consultants</description>
    <label>[OLD] Département</label>
    <nameField>
        <label>Nom du département</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Départements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppCIRinterlocuteur__c.object
<CustomObject>
    <description>APPLICATION CIR - Les interlocuteurs d&apos;une entité d&apos;un contrat CIR</description>
    <label>[OLD] Interlocuteur</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interlocuteurs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppCIRmission__c.object
<CustomObject>
    <description>APPLICATION CIR - Les missions CIR d&apos;un client</description>
    <fields>
        <fullName>Annee_CIR__c</fullName>
        <label>Année CIR</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>[OLD] Mission CIR</label>
    <nameField>
        <label>Nom de la mission CIR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>[OLD] Missions CIR</pluralLabel>
    <recordTypes>
        <fullName>AS</fullName>
        <active>true</active>
        <label>AS</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIN</fullName>
        <active>true</active>
        <label>CIN</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Annee_CIR__c</fullName>
        <label>Année CIR</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <recordTypes>
        <fullName>AS</fullName>
        <active>true</active>
        <label>AS</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIN</fullName>
        <active>true</active>
        <label>CIN</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOvalo__c.object
<CustomObject>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipLabel>Valorisations</relationshipLabel>
        <relationshipName>Valorisations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Valorisation</label>
    <nameField>
        <label>Nom de la valorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valorisations</pluralLabel>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOvalorisationCtrl.cls
public with sharing class INNOvalorisationCtrl extends INNOmissionBaseCtrl{

    //La mission INNO advance
    private INNOvalo__c valo {get; set;}
    
    //Le controller standard de la mission
    private ApexPages.standardController stdCtrl;
    
    //True si mission CIR, false sinon (AS,CIN)
    public Boolean isCir {get; set;}
    
    
  //  //Ce controller sert à la fois pour la page AppCIRmissionView et AppCIRmissionEdit, donc c'est pour savoir dans quelle cas on est
  //  private Boolean isEditMode;
    
  //  //True si l'utilisateur a le droit de créer une nouvelle entité (il faut qu'il soit superviseur/manager dans au moins 1 mission du client)
  //  public Boolean userCanCreateEntite {get; set;}
    
    
  //  //Le contrat dans un objet custom pour que les consultant avec des licences Force.com puissent y accéder
  //  public AppCIRcontrat contrat {get; set;}

  //  //La liste des interlocuteurs de l'entité
  //  public AppCIRinterlocuteur__c[] interlocuteurs {get; set;}
    
  //  //La liste des départements de l'entité
  //  public AppCIRdepartement__c[] departements {get; set;}

  //  //La liste des autres missions de l'entité
  //  public AppCIRmission__c[] missionsSoeurs {get; set;}
    
  //  //L'id de l'entité de la mission
  //  private Id entiteId;

    
    
      
    public PageReference checkParams(){
  
        if( this.stdCtrl.getId() != null && ApexPages.currentPage().getParameters().get('valoId') == null){
        	PageReference retPage = new PageReference('/apex/INNOvalorisationView');
	        retPage.getParameters().put('id', this.stdCtrl.getId());
	        retPage.getParameters().put('valoId', this.stdCtrl.getId());
	        retPage.setRedirect(true);
        	return retPage;
        }
        
        return null;
    }
    

    /**
    *   Constructeur
    */
    public INNOvalorisationCtrl(ApexPages.standardController stdCtrl){
        
        if(!Test.isRunningTest())
        	stdCtrl.addFields(new List<String> {'MissionCIR__r.OwnerId','MissionCIR__r.RecordType.DeveloperName','MissionCIR__r.Annee_CIR__c'});
        	
        this.valo = (INNOvalo__c) stdCtrl.getRecord();
        
        this.isCir = this.valo.MissionCIR__r.RecordType.DeveloperName == 'CIR';
        
        this.stdCtrl = stdCtrl;
        
    
    	if(ApexPages.currentPage().getParameters().get('sharingRecalc') == '1')
    		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Le partage de la mission aux équipes consulting peut prendre quelques minutes...'));
    }
    
    public PageReference deleteValo(){

        Id missionId = this.valo.MissionCIR__c;
    	if(INNOmissionUtils.userHasFullAccess() || this.valo.MissionCIR__r.OwnerId == Userinfo.getUserId() || [SELECT RecordId, HasDeleteAccess FROM UserRecordAccess WHERE RecordId = :this.valo.MissionCIR__c AND UserId = :Userinfo.getUserId()][0].HasDeleteAccess){
	 		Database.delete(this.valo.Id);
	    	
	     	PageReference retPage = new PageReference ('/'+missionId);
	     	retPage.setRedirect(true);
	 		return retPage;
    	}
    	else{
    		 Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Seul le propriétaire ou les utilisateurs du groupe \'INNO ADVANCE FULL ACCESS\' peuvent supprimer une valorisation'));
    		 return null;
    	}
	 }
	 
        
     
    
    
}