gac_sb/objects/AppCIRentite__c.object
<CustomObject>
    <description>APPLICATION CIR - Les entités d&apos;un client sur l&apos;application CIR pour les consultants</description>
    <fields>
        <fullName>CA__c</fullName>
        <description>Chiffre d&apos;affaire</description>
        <label>CA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Le contrat auquel est rattaché l&apos;entité</description>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>EntitesCIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effectif__c</fullName>
        <label>Effectif</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Resultat_NET__c</fullName>
        <label>Résultat NET</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SIREN__c</fullName>
        <label>SIREN</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>[OLD] Entité</label>
    <nameField>
        <label>Nom de l&apos;entité</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>MissionsCIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/INNOmissionCtrl_withoutSharing.cls
public without sharing class INNOmissionCtrl_withoutSharing {
	
	//Le controller standard de la mission
    private ApexPages.standardController stdCtrl;
    
    public Map<String, String> missionAccessByUser {get; set;}
    public Boolean missionReadWrite {get; set;}
    
    // //La liste des autres entités du client
    // public AppCIRentite__c[] entitesSoeurs {get; set;}
        
        
	public INNOmissionCtrl_withoutSharing(ApexPages.standardController stdCtrl){
    
    	this.stdCtrl = stdCtrl;
    	this.missionReadWrite = true;
    	
		//Permet notamment de vérifier automatiquement que l'utilisateur à bien les droits sur la mission
		INNOmission__c mission = (INNOmission__c) stdCtrl.getRecord();
		
		this.missionAccessByUser = new Map<String, String>();
        
       	Integer userReadAccess, userEditAccess;
       	List<UserRecordAccess> ura;
        for(INNOequipeConsulting__c eq : mission.EquipesConsulting__r){
        	system.debug(eq);
        	userReadAccess = userEditAccess = 0;
        	ura = [SELECT RecordId, HasReadAccess, HasEditAccess FROM UserRecordAccess WHERE UserId = :eq.Utilisateur__c AND RecordId = :mission.Id LIMIT 1];
        	
        	this.missionAccessByUser.put(eq.Utilisateur__c, ura.isEmpty() ? 'Aucun accès' : (ura[0].HasEditAccess ? 'Modification' : (ura[0].HasReadAccess ? 'Lecture' : 'Aucun accès')));
        	 
        }
		
		
  //      this.initEntitesSoeurs(mission.Entite__c, mission.Entite__r.Contrat__c);
	}

	 public PageReference deleteMission(){
    	INNOmission__c mission = (INNOmission__c) this.stdCtrl.getRecord();


    	if(INNOmissionUtils.userHasFullAccess() || mission.OwnerId == Userinfo.getUserId() || [SELECT RecordId, HasDeleteAccess FROM UserRecordAccess WHERE RecordId = :mission.Id AND UserId = :Userinfo.getUserId()][0].HasDeleteAccess){
	 		Database.delete(mission.Id);
	    	
	     	PageReference retPage = new PageReference ('/'+mission.Contrat__c);
	     	retPage.setRedirect(true);
	 		return retPage;
    	}
    	else{
    		 Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Seul le propriétaire de la mission ou les utilisateurs du groupe \'INNO ADVANCE FULL ACCESS\' peuvent supprimer une mission'));
    		 return null;
    	}
	 }
	
	
	// /**
 //   *   Initialise les autres entités du client
 //   */
 //   public void initEntitesSoeurs(Id entiteId, Id contratId){
 //       this.entitesSoeurs = [SELECT Id, Name, SIREN__c, Effectif__c, CA__c, Resultat_NET__c FROM AppCIRentite__c WHERE Id != :entiteId AND Contrat__c = :contratId];
 //   }
	
	
	
}