gac_sb/objects/AppCIRentite__c.object
<CustomObject>
    <description>APPLICATION CIR - Les entités d&apos;un client sur l&apos;application CIR pour les consultants</description>
    <label>[OLD] Entité</label>
    <nameField>
        <label>Nom de l&apos;entité</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/AppCIRequipeConsulting__c.object
<CustomObject>
    <description>APPLICATION CIR - Les consultants / superviseurs / managers travaillant sur les missions CIR</description>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Permet de rendre actif un utilisateur</description>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mission_CIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>AppCIRmission__c</referenceTo>
        <relationshipLabel>Equipes consulting</relationshipLabel>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Rôle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consultant scientifique</fullName>
                    <default>true</default>
                    <label>Consultant scientifique</label>
                </value>
                <value>
                    <fullName>Consultant fiscaliste</fullName>
                </value>
                <value>
                    <fullName>Consultant extérieur</fullName>
                </value>
                <value>
                    <fullName>Consultant scientifique RO</fullName>
                </value>
                <value>
                    <fullName>Superviseur/Consultant</fullName>
                </value>
                <value>
                    <fullName>Superviseur</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Auditeur Financier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>[OLD] Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/AppCIRmission__c.object
<CustomObject>
    <description>APPLICATION CIR - Les missions CIR d&apos;un client</description>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Entité</label>
        <referenceTo>AppCIRentite__c</referenceTo>
        <relationshipName>Missions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>[OLD] Mission CIR</label>
    <nameField>
        <label>Nom de la mission CIR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>[OLD] Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/ApexSharingRecalc_AppCIRmission.cls
global without sharing class ApexSharingRecalc_AppCIRmission implements Database.Batchable<sObject>{
	
	static final String equipeConsultingMissionRowCause = Schema.AppCIRmission__Share.RowCause.Equipe_Consulting__c;
	static final String equipeConsultingEntiteRowCause = Schema.AppCIRentite__Share.RowCause.Equipe_Consulting__c;
	static final String emailAddress = 'contact@synefo.fr';
	
	private Set<Id> updatedMissionsINNOids;
	
	private Set<Id> relatedEntitesIds = new Set<Id>();
	
	
	global ApexSharingRecalc_AppCIRmission(){}
	
	
	global ApexSharingRecalc_AppCIRmission(Set<Id> updatedMissionsINNOids){
		this.updatedMissionsINNOids = updatedMissionsINNOids;
	}
	
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		/*
		if(this.updatedMissionsINNOids != null){
			
			for(AppCIRmission__c m : [SELECT Id, Entite__c FROM AppCIRmission__c WHERE Id IN :updatedMissionsINNOids]){
				this.relatedEntitesIds.add(m.Entite__c);
			}
			
			return Database.getQueryLocator([SELECT Id FROM AppCIRmission__c WHERE Entite__c IN :relatedEntitesIds ORDER BY Entite__c]);
		}
		else
			return Database.getQueryLocator([SELECT Id FROM AppCIRmission__c ORDER BY Entite__c]);
		*/

		if(this.updatedMissionsINNOids != null){
			
			for(AppCIRmission__c m : [SELECT Id, Entite__c FROM AppCIRmission__c WHERE Id IN :updatedMissionsINNOids]){
				this.relatedEntitesIds.add(m.Entite__c);
			}
			
			return Database.getQueryLocator([SELECT Id FROM AppCIRentite__c WHERE Id IN :relatedEntitesIds ]);
		}
		else
			return Database.getQueryLocator([SELECT Id FROM AppCIRentite__c ]);

	}

	
	
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		
		system.debug('Start: BATCH ApexSharingRecalc_AppCIRmission');
		

		List<AppCIRentite__c> entites = (List<AppCIRentite__c>) scope;
		List<AppCIRmission__c> missionsINNO = [SELECT Id FROM AppCIRmission__c WHERE Entite__c IN :entites];
		//List<AppCIRmission__c> missionsINNO = (List<AppCIRmission__c>) scope;
		
		
		// Create a list of Mission__Share objects to be inserted.
		List<AppCIRmission__Share> newMissionINNOShrs = new List<AppCIRmission__Share>();
		
		//On sépare les entités share en 2: read et edit, pour ensuite insérer les Edit APRES les Read afin de surcharger le Read si necessaire
		List<AppCIRentite__Share> newEntiteINNOReadShrs = new List<AppCIRentite__Share>();
		List<AppCIRentite__Share> newEntiteINNOEditShrs = new List<AppCIRentite__Share>();
		
		system.debug(missionsINNO.size() + ' missions INNO');
		//this.relatedEntitesIds = new Set<Id>();
		
		for(AppCIRequipeConsulting__c eq : [SELECT Id, Mission_CIR__c, Mission_CIR__r.Entite__c, Utilisateur__c, Role__c FROM AppCIRequipeConsulting__c WHERE Mission_CIR__r.Entite__c IN :entites AND Utilisateur__r.IsActive = true AND Actif__c = true]){
			
			newMissionINNOShrs.add(new AppCIRmission__Share(ParentId = eq.Mission_CIR__c, UserOrGroupId = eq.Utilisateur__c, AccessLevel = (eq.Role__c == 'Consultant extérieur' ? 'Read' : 'Edit'), RowCause = equipeConsultingMissionRowCause));
			
			if(eq.Role__c == 'Consultant extérieur')
				newEntiteINNOReadShrs.add(new AppCIRentite__Share(ParentId = eq.Mission_CIR__r.Entite__c, UserOrGroupId = eq.Utilisateur__c, AccessLevel = 'Read', RowCause = equipeConsultingEntiteRowCause));
			else
				newEntiteINNOEditShrs.add(new AppCIRentite__Share(ParentId = eq.Mission_CIR__r.Entite__c, UserOrGroupId = eq.Utilisateur__c, AccessLevel = 'Edit', RowCause = equipeConsultingEntiteRowCause));
			
			//this.relatedEntitesIds.add(eq.Mission_CIR__r.Entite__c);
		}
		
		
		newEntiteINNOReadShrs.addAll(newEntiteINNOEditShrs);
		
		
		system.debug(newMissionINNOShrs.size() + ' newMissionINNOShrs');
		system.debug(newEntiteINNOReadShrs.size() + ' newEntiteINNOShrs');
		
		
		try {
			// Locate and delete all existing sharing records for the Mission records in the batch.
			// This allows new sharing records to be written from scratch.
			Database.delete([SELECT Id FROM AppCIRmission__Share WHERE ParentId IN :missionsINNO AND RowCause = :equipeConsultingMissionRowCause], false);
			Database.delete([SELECT Id FROM AppCIRentite__Share WHERE ParentId IN :entites AND RowCause = :equipeConsultingEntiteRowCause], false);
			
			
			// Insert the new sharing records and capture the save result. 
			// The false parameter allows for partial processing if multiple records are 
			// passed into operation. 
			Database.SaveResult[] lsr = Database.insert(newMissionINNOShrs, false);
			lsr.addAll(Database.insert(newEntiteINNOReadShrs, false));
			
			// Process the save results for insert.
			for(Database.SaveResult sr : lsr){
				if(!sr.isSuccess()){
					// Get the first save result error.
					Database.Error err = sr.getErrors()[0];
					
					// Check if the error is related to trivial access level.
					// Access levels equal or more permissive than the object's default 
					// access level are not allowed. 
					// These sharing records are not required and thus an insert exception 
					// is acceptable. 
					if(!(err.getStatusCode() == StatusCode.FIELD_FILTER_VALIDATION_EXCEPTION  
								&&  err.getMessage().contains('AccessLevel'))){
						// Error is not related to trivial access level.
						// Send an email to the Apex job's submitter.
						Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
						String[] toAddresses = new String[] {emailAddress}; 
						mail.setToAddresses(toAddresses); 
						mail.setSubject('GAC: INNO Advance - AppCIRmission Apex Sharing Recalculation sur UN record');
						mail.setPlainTextBody('Apex sharing recalculation exception: \n' + err.getMessage() + '\n' + err.getFields());
						system.debug('Exception sur un record: ' + err.getMessage() + '-' + err.getFields());
						Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
					}
				}
			}  
		} catch(DmlException e) {
			//Send an email to the Apex job's submitter on failure.
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			String[] toAddresses = new String[] {emailAddress}; 
			mail.setToAddresses(toAddresses); 
			mail.setSubject('GAC: INNO Advance - AppCIRmission Apex Sharing Recalculation');
			mail.setPlainTextBody('Apex sharing recalculation exception: \n' + e.getMessage());
			system.debug('Exception globale: ' + e.getMessage());
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		}
		
		system.debug('End: BATCH ApexSharingRecalc_AppCIRmission');
	}
	
	

	global void finish(Database.BatchableContext BC){}
	
	
}