gac_sb/objects/Detail_facture__c.object
<CustomObject>
    <description>SF CONSULTING - permet de saisir plusieurs lignes de détail sur une facture</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Facture__c</fullName>
        <label>Facture</label>
        <referenceTo>Facture__c</referenceTo>
        <relationshipLabel>Détails facture</relationshipLabel>
        <relationshipName>Details_facture</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Montant_HT__c</fullName>
        <label>Montant HT</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ordre__c</fullName>
        <inlineHelpText>Ordre d&apos;affichage sur la facture</inlineHelpText>
        <label>Ordre</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>R_clamation__c</fullName>
        <label>Réclamation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>des_credits__c</fullName>
        <label>% des crédits</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Détail facture</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Detail facture</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Détails facture</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/FacturationEntite__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SF CONSULTING - Utilisé dans le footer des factures</description>
    <label>FacturationEntité</label>
</CustomObject>

gac_sb/objects/Facture__c.object
<CustomObject>
    <description>SF CONSULTING - permet de créer des factures</description>
    <fields>
        <fullName>Entite_GAC__c</fullName>
        <label>Entité GAC</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Montant_HT__c</fullName>
        <description>(Facture)</description>
        <label>Montant HT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Facture</label>
    <nameField>
        <label>N° Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/FactuFacturePDFCtrl.cls
public with sharing class FactuFacturePDFCtrl {
    
    public List<Detail_facture__c> DetailFactuList{get;set;}
    public Facture__c factu{get;set;}
    private ApexPages.standardController stdCtrl;
    //Informations du footer (FacturationEntite__c est un custom setting)
    public FacturationEntite__c footerInfos {get; set;}
    
     public FactuFacturePDFCtrl(ApexPages.standardController stdCtrl){
                
        this.stdCtrl = stdCtrl;
        this.factu = (Facture__c)stdCtrl.getRecord();
        this.initDetailFactuList();
        this.initFooterInfos();

    }
    
    private void initDetailFactuList(){
        
        this.DetailFactuList = new List<Detail_facture__c>();
    
        for(Detail_facture__c df : [SELECT Id, Description__c, Montant_HT__c, Ordre__c, des_credits__c, R_clamation__c
                                                FROM Detail_facture__c 
                                                WHERE Facture__c = :this.factu.Id
                                                ORDER BY Ordre__c ASC]){
                this.DetailFactuList.add(df);                                       
        }
        
    }
    
    private void initFooterInfos(){
        //Récupération des infos du footer relatives au paiement (FacturationEntite__c est un custom setting)
        this.footerInfos = FacturationEntite__c.getInstance(this.factu.Entite_GAC__c);
    }

}