gac_sb/objects/Encaissement__c.object
<CustomObject>
    <description>SF CONSULTING - permet de saisir les encaissements sur les factures</description>
    <fields>
        <fullName>Date_encaissement__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date encaissement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facture__c</fullName>
        <label>Facture</label>
        <referenceTo>Facture__c</referenceTo>
        <relationshipLabel>Encaissements</relationshipLabel>
        <relationshipName>Encaissements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Montant_TTC__c</fullName>
        <label>Montant TTC (encaissement)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Encaissement</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>N° Encaissement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encaissements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Facture__c.object
<CustomObject>
    <description>SF CONSULTING - permet de créer des factures</description>
    <fields>
        <fullName>Apporteur_d_affaire_comptabilise_paye__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apporteur d&apos;affaire comptabilisé/payé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_validation__c</fullName>
        <label>Date validation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facture_liee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Dans le cas des avoirs uniquements</description>
        <label>Facture liée</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Contrat__c</field>
                <operation>equals</operation>
                <valueField>Facture__c.Contrat__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facture__c</referenceTo>
        <relationshipLabel>Avoirs</relationshipLabel>
        <relationshipName>Avoirs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Montant_TTC__c</fullName>
        <description>Facture</description>
        <formula>ROUND(Montant_HT__c +  Montant_TVA__c, 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant TTC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prestataire__c</fullName>
        <label>Prestataire</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Forskel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prestataire_comptabilise_paye__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prestataire comptabilisé/payé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En attente</fullName>
                    <default>true</default>
                    <label>En attente</label>
                </value>
                <value>
                    <fullName>Validée</fullName>
                </value>
                <value>
                    <fullName>Envoyée</fullName>
                </value>
                <value>
                    <fullName>Soldée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>percent_Prestation__c</fullName>
        <label>% Prestation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Facture</label>
    <nameField>
        <label>N° Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Prevision_de_facturation__c.object
<CustomObject>
    <description>SF CONSULTING - permet de saisir des planifications de facturation</description>
    <fields>
        <fullName>Apporteur_d_affaire_comptabilise_paye__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apporteur d&apos;affaire comptabilisé/payé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facture associée</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Mission__c</field>
                <operation>equals</operation>
                <valueField>Facture__c.Mission__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facture__c</referenceTo>
        <relationshipLabel>Planifications de facturation liées</relationshipLabel>
        <relationshipName>Planificiations_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prestataire__c</fullName>
        <label>Prestataire</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Arbor</fullName>
                </value>
                <value>
                    <fullName>Aucun</fullName>
                </value>
                <value>
                    <fullName>Autre</fullName>
                </value>
                <value>
                    <fullName>Forskel</fullName>
                </value>
                <value>
                    <fullName>FT</fullName>
                </value>
                <value>
                    <fullName>MP Ressource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prestataire_comptabilise_paye__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prestataire comptabilisé/payé</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Facturée</fullName>
                </value>
                <value>
                    <fullName>Prévue</fullName>
                </value>
                <value>
                    <fullName>HGNF</fullName>
                </value>
                <value>
                    <fullName>Rejetée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>percent_Prestation__c</fullName>
        <label>% Prestation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Planification de facturation</label>
    <nameField>
        <displayFormat>Planif-{000000}</displayFormat>
        <label>N° Planification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planifications de facturation</pluralLabel>
    <recordTypes>
        <fullName>ACS</fullName>
        <active>true</active>
        <label>ACS</label>
    </recordTypes>
    <recordTypes>
        <fullName>FI</fullName>
        <active>true</active>
        <label>AS</label>
    </recordTypes>
    <recordTypes>
        <fullName>IL</fullName>
        <active>true</active>
        <label>IL</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/FactureHandler_Test.cls
@isTest
public class FactureHandler_Test {

	public static testmethod void testFactureHandlerErrorOnPrevisions(){
		
		FactuTestBase.Init();
		test.startTest();
		FactuTestBase.InitFactures();
		facture__c f = FactuTestBase.factures.get(1);
		prevision_de_facturation__c planif = FactuTestBase.createPlanif(1,'ACS',1000);
		planif.percent_Prestation__c = 10;
		planif.Prestataire__c = 'Test Prestataire';
		planif.Prestataire_comptabilise_paye__c = true;
		planif.Apporteur_d_affaire_comptabilise_paye__c = true;
		planif.Facture__c = f.id;
		insert planif;
		
		prevision_de_facturation__c planif2 = FactuTestBase.createPlanif(1,'ACS',5000);
		planif2.Prestataire__c = 'ERR Prestataire';
		planif2.Prestataire_comptabilise_paye__c = false;
		planif2.percent_Prestation__c = 50;
		planif2.Facture__c = f.id;
		string err = '';
		
		system.debug('testFactureHandlerErrorOnPrevisions');
		//Il devrait y avoir une erreur ici étant donné qu'on essaie de mettre 2 prévisions différentes:
		try{
			insert planif2;
		}catch(Exception e){
			system.debug('Exception Catched!');
			err=e.getMessage();
		}
		system.debug('Erreur obtenue : '+err);
		
		system.assert(err.contains('est pas possible de saisir 2 prestataires différents sur 2 planifications liées à la même facture. Vous avez renseigné'));
		system.assert(err.contains('est pas possible de saisir 2 pourcentages de rémunération prestataires différents'));
		
		test.stopTest();
		
	}

	public static testmethod void testFactureHandlerValidation(){
				
		FactuTestBase.Init();
		
		Test.startTest();
		// Creation des factures
		FactuTestBase.InitFactures();
		
		// factures FI et avoir FI
		Facture__c f = FactuTestBase.Factures.get(4);
		
		
		
		f.Statut__c = 'Validée';
		f.Date_validation__c = date.today();
		// Validation de la facture
		update f;

		FactuTestBase.refreshFacture();
		f = FactuTestBase.Factures.get(4);
		
		Test.stopTest();
		
	}
	
	public static testmethod void testFactureHandlerValidationAvoir(){
				
		FactuTestBase.Init();
		
		Test.startTest();
		
		// Creation des factures
		FactuTestBase.InitFactures();
		
		// factures FI et avoir FI
		Facture__c f = FactuTestBase.Factures.get(4);


		Facture__c a = FactuTestBase.Factures.get(5);
		a.Facture_liee__c = f.Id;
		a.Statut__c = 'Validée';
		a.Date_validation__c = date.today();
		// Validation de l'avoir en le liant à la facture
		update a;
		
		FactuTestBase.refreshFacture();
		a = FactuTestBase.Factures.get(5);
		f = FactuTestBase.Factures.get(4);
		
		Test.stopTest();
	}
	
	public static testmethod void testFactureHandlerSuppression(){
				
		FactuTestBase.Init();
		
		Test.startTest();
		
		// Creation des factures
		FactuTestBase.InitFactures();
		
		// factures FI et avoir FI
		Facture__c f = FactuTestBase.Factures.get(4);
		
		f.Statut__c = 'Validée';
		f.Date_validation__c = date.today();
		// Validation de la facture
		update f;
		FactuTestBase.refreshFacture();
		f = FactuTestBase.Factures.get(4);
		
		f.Statut__c = 'En attente';
		f.Date_validation__c = null;
		// Devalidation
		update f;

		FactuTestBase.refreshFacture();
		f = FactuTestBase.Factures.get(4);
		// Delete
		delete f;

		Test.stopTest();

	}
	
	public static testmethod void testFactureHandlerEncaissement(){
				
		FactuTestBase.Init();
		
		Test.startTest();
		
		// Creation des factures
		FactuTestBase.InitFactures();
		
		// factures FI et avoir FI
		Facture__c f = FactuTestBase.Factures.get(4);
		
		f.Statut__c = 'Validée';
		f.Date_validation__c = date.today();
		// Validation de la facture
		update f;
		FactuTestBase.refreshFacture();
		f = FactuTestBase.Factures.get(4);
		
		// Saisie d'un encaissement sur la facture
		Encaissement__c Encaissement = new Encaissement__c (Facture__c = f.Id, Montant_TTC__c = f.Montant_TTC__c, Date_encaissement__c = date.today());
		insert Encaissement;
		
		FactuTestBase.refreshFacture();
		f = FactuTestBase.Factures.get(4);
		
		system.assertEquals('Soldée',f.Statut__c);
		
		Test.stopTest();
		
	}

	public static testmethod void testFactureHandlerPrevisions(){
		FactuTestBase.Init();
		test.startTest();
		FactuTestBase.InitFactures();
		facture__c f = FactuTestBase.factures.get(1);
		prevision_de_facturation__c planif = FactuTestBase.createPlanif(1,'ACS',1000);
		planif.percent_Prestation__c = 10;
		planif.Prestataire__c = 'Test Prestataire';
		planif.Prestataire_comptabilise_paye__c = true;
		planif.Apporteur_d_affaire_comptabilise_paye__c = true;
		planif.Facture__c = f.id;
		insert(planif);
		Facture__c f2= [select	id,
							Prestataire_comptabilise_paye__c,
							Apporteur_d_affaire_comptabilise_paye__c,
							percent_Prestation__c,
							Prestataire__c from facture__c where id = : f.id]; 
		system.assert(f2.Prestataire_comptabilise_paye__c,'La case prestataire comptabilisé payé devrait être cochée car elle l\'est sur une des planifs de la facture');
		system.assert(f2.Apporteur_d_affaire_comptabilise_paye__c,'La case apporteur d\'affaire comptabilisé payé devrait être cochée car elle l\'est sur une des planifs de la facture');
		system.assert(f2.percent_Prestation__c == 10,'le pourcentage de prestation devrait être de 10 étant donné qu\'il est de 10 sur la planif associée');
		system.assert(f2.Prestataire__c == 'Test Prestataire','Le prestataire devrait être "Test prestataire"');
		test.stopTest();
		
	}


}