gac_sb/objects/Facture__c.object
<CustomObject>
    <description>SF CONSULTING - permet de créer des factures</description>
    <fields>
        <fullName>Commentaires_recouvrement__c</fullName>
        <label>Commentaires recouvrement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Facture</label>
    <nameField>
        <label>N° Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/TaskHandler_Test.cls
@isTest
public class TaskHandler_Test {

	public static testmethod void testTaskHandler(){
				
		FactuTestBase.Init();
		Test.startTest();		
		// Creation des factures
		FactuTestBase.InitFactures();
		
		// factures FI et avoir FI
		Facture__c f = FactuTestBase.Factures.get(4);
		
		Task t = new Task(Subject = 'Test',Description = 'test commentaire recouvrement',WhatId = f.Id);
		insert t;
		
		FactuTestBase.refreshFacture();
		f = FactuTestBase.Factures.get(4);
		system.assertEquals('test commentaire recouvrement',f.Commentaires_recouvrement__c);
		
		t.Description = 'test commentaire recouvrement 2';
		update t;
		
		delete t;
		
		Test.stopTest();
		
	}
}