gac_sb/objects/Facture__c.object
<CustomObject>
    <description>SF CONSULTING - permet de créer des factures</description>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Factures</relationshipLabel>
        <relationshipName>Factures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Facture</label>
    <nameField>
        <label>N° Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Historique_Segmentation__c.object
<CustomObject>
    <label>Historique Segmentation</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historiques segmentation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/INNOamortissement__c.object
<CustomObject>
    <label>Amortissement</label>
    <nameField>
        <label>Désignation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amortissements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOdepensePersonnel__c.object
<CustomObject>
    <label>Dépense de personnel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses de personnel</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOdepensePrestation__c.object
<CustomObject>
    <label>Dépense de prestation</label>
    <nameField>
        <label>Prestation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses de prestation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOtimeSheet__c.object
<CustomObject>
    <label>TimeSheet CIR</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>TimeSheets INNO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheets CIR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/INNOvalo__c.object
<CustomObject>
    <label>Valorisation</label>
    <nameField>
        <label>Nom de la valorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valorisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/Prevision_de_facturation__c.object
<CustomObject>
    <description>SF CONSULTING - permet de saisir des planifications de facturation</description>
    <fields>
        <fullName>Facture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facture associée</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Mission__c</field>
                <operation>equals</operation>
                <valueField>Facture__c.Mission__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facture__c</referenceTo>
        <relationshipLabel>Planifications de facturation liées</relationshipLabel>
        <relationshipName>Planificiations_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mission__c.Contrat__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contrat__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>Planifications_de_facturation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Planification de facturation</label>
    <nameField>
        <displayFormat>Planif-{000000}</displayFormat>
        <label>N° Planification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planifications de facturation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Societe_a_auditer__c.object
<CustomObject>
    <description>Entités à intégrer à un objet Contrat</description>
    <fields>
        <fullName>Societe_a_auditer__c</fullName>
        <label>Société à auditer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inclus dans le périmètre des contrats</relationshipLabel>
        <relationshipName>Auditee_contrat</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Société à auditer</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nom de la société à auditer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sociétés à auditer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/TriggerFactory.cls
/**
 * Class TriggerFactory
 * @Author Tony Scott
 * @Date 2012-04-02
 * @Site http://developer.force.com/cookbook/recipe/trigger-pattern-for-tidy-streamlined-bulkified-triggers
 * @Description Used to instantiate and execute Trigger Handlers associated with sObjects.
 */
public with sharing class TriggerFactory
{
  /**
   * Public static method to create and execute a trigger handler
   *
   * Arguments:  Schema.sObjectType soType - Object type to process (SObject.sObjectType)
   *
   * Throws a MyException if no handler has been coded.
   */
  public static void createHandler(Schema.sObjectType soType) {
    // Get a handler appropriate to the object being processed
    ITrigger handler = getHandler(soType);
    
    // Make sure we have a handler registered, new handlers must be registered in the getHandler method.
    if (handler == null)
    {
      throw new TriggerException('No Trigger Handler registered for Object Type: ' + soType);
    }
    
    // Execute the handler to fulfil the trigger
    execute(handler);
  }
  
  /**
   * private static method to control the execution of the handler
   *
   * Arguments:  TriggerHandlerBase handler - A Trigger Handler to execute
   */  
  private static void execute(ITrigger handler) {
    // Before Trigger
    if (Trigger.isBefore)
    {
      // Call the bulk before to handle any caching of data and enable bulkification
      handler.bulkBefore();
      
      // Iterate through the records to be deleted passing them to the handler.
      if (Trigger.isDelete)
      {
        for (SObject so : Trigger.old)
        {
          handler.beforeDelete(so);
        }
      }
      // Iterate through the records to be inserted passing them to the handler.
      else if (Trigger.isInsert)
      {
        for (SObject so : Trigger.new)
        {
          handler.beforeInsert(so);
        }
      }
      // Iterate through the records to be updated passing them to the handler.
      else if (Trigger.isUpdate)
      {
        for (SObject so : Trigger.old)
        {
          handler.beforeUpdate(so, Trigger.newMap.get(so.Id));
        }
      }
    }
    else
    {
      // Call the bulk after to handle any caching of data and enable bulkification
      handler.bulkAfter();
      
      // Iterate through the records deleted passing them to the handler.
      if (Trigger.isDelete)
      {
        for (SObject so : Trigger.old)
        {
          handler.afterDelete(so);
        }
      }
      // Iterate through the records inserted passing them to the handler.
      else if (Trigger.isInsert || Trigger.isUndelete)
      {
        for (SObject so : Trigger.new)
        {
          handler.afterInsert(so);
        }
      }
      // Iterate through the records updated passing them to the handler.
      else if (Trigger.isUpdate)
      {
        for (SObject so : Trigger.old)
        {
          handler.afterUpdate(so, Trigger.newMap.get(so.Id));
        }
      }
    }
    
    // Perform any post processing
    handler.andFinally();
  }
  
  /**
   * private static method to get the appropriate handler for the object type.
   * Modify this method to add any additional handlers.
   *
   * Arguments:  Schema.sObjectType soType - Object type tolocate (SObject.sObjectType)
   *
   * Returns:    ITrigger - A trigger handler if one exists or null.
   */
  private static ITrigger getHandler(Schema.sObjectType soType) {
    
    if(soType == Case.sObjectType)
      return new CaseHandler();

    if(soType == User.sObjectType)
      return new UserHandler();
    
    if(soType == Opportunity.sObjectType)
      return new OpportunityHandler();
    
    if(soType == Event.sObjectType)
      return new EventHandler();
      
    if(soType == Task.sObjectType)
      return new TaskHandler();
    
    if(soType == Contract.sObjectType)
      return new ContractHandler();
      
    if(soType == Account.sObjectType)
      return new AccountHandler();
    
    if(soType == Societe_a_auditer__c.sObjectType)
      return new Societe_a_auditerHandler();
    
    if(soType == Lead.sObjectType)
      return new LeadHandler();
      
    if(soType == Facture__c.sObjectType)
      return new FactureHandler();
      
    if(soType == Prevision_de_facturation__c.sObjectType)
      return new Prevision_de_facturationHandler();
      
    if(soType == Mission__c.sObjectType)
      return new MissionHandler(); 
      /*
    if(soType == Propale__c.SobjectType)
        return new PropaleHandler();*/
    if(soType == Historique_Segmentation__c.sObjectType)
        return new Historique_SegmentationHandler();
        
    if(soType == INNOmission__c.sObjectType)
        return new INNOmissionHandler();
        
	if(soType == INNOdepensePersonnel__c.sObjectType)
        return new INNOdepensePersonnelHandler();
    
    if(soType == INNOdepensePrestation__c.sObjectType)
        return new INNOdepensePrestationHandler();
        
	if(soType == INNOamortissement__c.sObjectType)
		return new INNOamortissementHandler();

	if(soType == INNOequipeConsulting__c.sObjectType)
		return new INNOequipeConsultingHandler();
		
	if(soType == INNOtimeSheet__c.sObjectType)
		return new INNOtimeSheetHandler();
		
	if(soType == INNOvalo__c.sObjectType)
		return new INNOvalorisationHandler();
			
    return null;
  }
}