gac_sb/objects/Facture__c.object
<CustomObject>
    <description>SF CONSULTING - permet de créer des factures</description>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Factures</relationshipLabel>
        <relationshipName>Factures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Facture</label>
    <nameField>
        <label>N° Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <recordTypes>
        <fullName>ACS</fullName>
        <active>true</active>
        <description>Mission ACS</description>
        <label>ACS</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <description>Mission CIR</description>
        <label>CIR</label>
    </recordTypes>
    <recordTypes>
        <fullName>FI</fullName>
        <active>true</active>
        <description>Mission AS</description>
        <label>AS</label>
    </recordTypes>
    <recordTypes>
        <fullName>IL</fullName>
        <active>true</active>
        <description>Mission IL</description>
        <label>IL</label>
    </recordTypes>
    <recordTypes>
        <fullName>TAT</fullName>
        <active>true</active>
        <description>Mission TAT</description>
        <label>TAT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/Prevision_de_facturation__c.object
<CustomObject>
    <description>SF CONSULTING - permet de saisir des planifications de facturation</description>
    <fields>
        <fullName>Facture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facture associée</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Mission__c</field>
                <operation>equals</operation>
                <valueField>Facture__c.Mission__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facture__c</referenceTo>
        <relationshipLabel>Planifications de facturation liées</relationshipLabel>
        <relationshipName>Planificiations_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mission__c.Contrat__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contrat__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>Planifications_de_facturation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Planification de facturation</label>
    <nameField>
        <displayFormat>Planif-{000000}</displayFormat>
        <label>N° Planification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planifications de facturation</pluralLabel>
    <recordTypes>
        <fullName>ACS</fullName>
        <active>true</active>
        <label>ACS</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <description>Prévision de facturation CIR</description>
        <label>CIR</label>
    </recordTypes>
    <recordTypes>
        <fullName>FI</fullName>
        <active>true</active>
        <label>AS</label>
    </recordTypes>
    <recordTypes>
        <fullName>IL</fullName>
        <active>true</active>
        <label>IL</label>
    </recordTypes>
    <recordTypes>
        <fullName>TAT</fullName>
        <active>true</active>
        <description>Prévision de facturation TAT</description>
        <label>TAT</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/FactuCreateFactureCtrl_Test.cls
@isTest
public class FactuCreateFactureCtrl_Test {

	public static testmethod void testFactuEditFactureCtrl(){
				
		FactuTestBase.Init();
		Test.startTest();
		FactuTestBase.InitFactures();
		
		// CIR et devalidate
		Facture__c f = FactuTestBase.Factures.get(0);
		Test.setCurrentPageReference(new Pagereference('/apex/FactuCreateFacture'));
		System.currentPageReference().getParameters().put('id', f.Id);
		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(f);
		FactuCreateFactureCtrl ctrl = new FactuCreateFactureCtrl(stdCtrl);
		ctrl.saveFacture();
		ctrl.unvalidateFacture();
		Test.stopTest();

    }
    
    public static testmethod void testFactuCreateFactureCIRCtrl(){
    	
    	FactuTestBase.Init();
    	Test.startTest();
		FactuTestBase.InitFactures();
		
		// CIR
		Mission__c m = FactuTestBase.Missions.get(0);
		Test.setCurrentPageReference(new Pagereference('/apex/FactuCreateFacture'));
		System.currentPageReference().getParameters().put('MissionId', m.Id);
		System.currentPageReference().getParameters().put('PlanifsId', m.Planifications_de_facturation__r[0].Id);
		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(new Facture__c());
		FactuCreateFactureCtrl ctrl = new FactuCreateFactureCtrl(stdCtrl);
		ctrl.saveFacture();
		
		Test.stopTest();
    	
    }
    
    public static testmethod void testFactuCreateFactureACSCtrl(){
    	
    	FactuTestBase.Init();
    	Test.startTest();
		FactuTestBase.InitFactures();
		
		// ACS
		Mission__c m = FactuTestBase.Missions.get(1);
		Test.setCurrentPageReference(new Pagereference('/apex/FactuCreateFacture'));
		System.currentPageReference().getParameters().put('MissionId', m.Id);
		System.currentPageReference().getParameters().put('PlanifsId', m.Planifications_de_facturation__r[0].Id);
		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(new Facture__c());
		FactuCreateFactureCtrl ctrl = new FactuCreateFactureCtrl(stdCtrl);
		ctrl.saveFacture();
		
		Test.stopTest();
    	
    }
    
     public static testmethod void testFactuCreateFactureTATCtrl(){
				
		FactuTestBase.Init();
		Test.startTest();
		FactuTestBase.InitFactures();
		
		
		// TAT et detail facture
		Mission__c m = FactuTestBase.Missions.get(2);
		Test.setCurrentPageReference(new Pagereference('/apex/FactuCreateFacture'));
		System.currentPageReference().getParameters().put('MissionId', m.Id);
		System.currentPageReference().getParameters().put('PlanifsId', m.Planifications_de_facturation__r[0].Id);
		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(new Facture__c());
		FactuCreateFactureCtrl ctrl = new FactuCreateFactureCtrl(stdCtrl);
		ctrl.addDetailFacture();
		ctrl.addDetailFacture();
		System.currentPageReference().getParameters().put('detailFactureIndex', '1');
		ctrl.removeDetailFacture();
		ctrl.saveFacture();
		
		Test.stopTest();

    }
    
    public static testmethod void testFactuCreateFactureILCtrl(){
    	
    	FactuTestBase.Init();
    	Test.startTest();
		FactuTestBase.InitFactures();
		
		
		// IL
		Mission__c m = FactuTestBase.Missions.get(3);
		Test.setCurrentPageReference(new Pagereference('/apex/FactuCreateFacture'));
		System.currentPageReference().getParameters().put('MissionId', m.Id);
		System.currentPageReference().getParameters().put('PlanifsId', m.Planifications_de_facturation__r[0].Id);
		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(new Facture__c());
		FactuCreateFactureCtrl ctrl = new FactuCreateFactureCtrl(stdCtrl);
		ctrl.saveFacture();
		
		Test.stopTest();
    	
    }
    
    public static testmethod void testFactuCreateFactureFICtrl(){
    	
    	FactuTestBase.Init();
		Test.startTest();
		FactuTestBase.InitFactures();
		
		// FI et avoir
		Mission__c m = FactuTestBase.Missions.get(4);
		Test.setCurrentPageReference(new Pagereference('/apex/FactuCreateFacture'));
		System.currentPageReference().getParameters().put('MissionId', m.Id);
		System.currentPageReference().getParameters().put('PlanifsId', m.Planifications_de_facturation__r[0].Id);
		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(new Facture__c());
		FactuCreateFactureCtrl ctrl = new FactuCreateFactureCtrl(stdCtrl);
		ctrl.saveFacture();
		// System.currentPageReference().getParameters().put('MissionId', m.Id);
		// System.currentPageReference().getParameters().put('PlanifsId', m.Planifications_de_facturation__r[1].Id);
		// stdCtrl = new ApexPages.StandardController(new Facture__c());
		// ctrl = new FactuCreateFactureCtrl(stdCtrl);
		// ctrl.saveFacture();
		
		
		Test.stopTest();
    	
    }
    
   

}