gac_sb/objects/Facture__c.object
<CustomObject>
    <description>SF CONSULTING - permet de créer des factures</description>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Factures</relationshipLabel>
        <relationshipName>Factures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Factures</relationshipLabel>
        <relationshipName>Factures</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En attente</fullName>
                    <default>true</default>
                    <label>En attente</label>
                </value>
                <value>
                    <fullName>Validée</fullName>
                </value>
                <value>
                    <fullName>Envoyée</fullName>
                </value>
                <value>
                    <fullName>Soldée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Facture</label>
    <nameField>
        <label>N° Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/Prevision_de_facturation__c.object
<CustomObject>
    <description>SF CONSULTING - permet de saisir des planifications de facturation</description>
    <fields>
        <fullName>Commentaire_prevision__c</fullName>
        <description>Commentaires</description>
        <inlineHelpText>Permet de saisir un commentaire sur la planif.
Par exemple : La raison pour laquelle le client ne souhaite pas saisir le TA</inlineHelpText>
        <label>Commentaires</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>Planificiations_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_d_HGNF__c</fullName>
        <description>Date d&apos;honoraire gagné non facturé</description>
        <label>Date d&apos;HGNF</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_prevue__c</fullName>
        <label>Date prévue</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dossier_salarie__c</fullName>
        <label>Dossiers salariés</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Facture__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facture associée</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Mission__c</field>
                <operation>equals</operation>
                <valueField>Facture__c.Mission__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Facture__c</referenceTo>
        <relationshipLabel>Planifications de facturation liées</relationshipLabel>
        <relationshipName>Planificiations_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mission__c.Contrat__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contrat__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>Planifications_de_facturation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mois__c</fullName>
        <formula>CASE(MONTH( Date_prevue__c ),
1, $Label.Mois_Janvier ,
2, $Label.Mois_Fevrier ,
3, $Label.Mois_Mars ,
4, $Label.Mois_Avril ,
5, $Label.Mois_Mai ,
6, $Label.Mois_Juin ,
7, $Label.Mois_Juillet ,
8, $Label.Mois_Aout ,
9, $Label.Mois_Septembre ,
10, $Label.Mois_Octobre ,
11, $Label.Mois_Novembre ,
12, $Label.Mois_Decembre ,&apos;#&apos;) &amp; &apos; &apos; &amp;  TEXT(YEAR( Date_prevue__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mois</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Montant_HGNF__c</fullName>
        <description>montant pour le Canada</description>
        <label>Montant HGNF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nature_facturation__c</fullName>
        <inlineHelpText>Va permettre le pré-remplissage du contenu de la facture</inlineHelpText>
        <label>Nature facturation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Avoir</fullName>
                </value>
                <value>
                    <fullName>Regul</fullName>
                </value>
                <value>
                    <fullName>Facturation avec estimation</fullName>
                </value>
                <value>
                    <fullName>Facturation avec tous les éléments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Periode_debut__c</fullName>
        <label>Période début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Periode_fin__c</fullName>
        <label>Période fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pourcentage_Factur__c</fullName>
        <label>Pourcentage Facturé</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Prevision_HT__c</fullName>
        <label>Prévision HT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Facturée</fullName>
                </value>
                <value>
                    <fullName>Prévue</fullName>
                </value>
                <value>
                    <fullName>HGNF</fullName>
                </value>
                <value>
                    <fullName>Rejetée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Typologie_facturation__c</fullName>
        <inlineHelpText>Factu / Re-factu</inlineHelpText>
        <label>Typologie facturation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Facturation initiale</fullName>
                </value>
                <value>
                    <fullName>Avoir</fullName>
                </value>
                <value>
                    <fullName>Regul</fullName>
                </value>
                <value>
                    <fullName>Facturation avec estimation</fullName>
                </value>
                <value>
                    <fullName>Facturation avec tous les éléments</fullName>
                </value>
                <value>
                    <fullName>Re-facturation</fullName>
                </value>
                <value>
                    <fullName>Au forfait</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Planification de facturation</label>
    <nameField>
        <displayFormat>Planif-{000000}</displayFormat>
        <label>N° Planification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planifications de facturation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/FactuSelectPlanificationsCtrl.cls
public with sharing class FactuSelectPlanificationsCtrl {
    
    public Mission__c mission{get;set;}
    
    
    public List<Selectoption> lsSelectOptionPlanifications{get;set;}
    
    public List<Id> selectedPlanifications{get;set;} 
    
    private Map<String,Id> recordTypes = new Map<String,Id>();
    
    
    
    
    /*
    * constructor
    */
    public FactuSelectPlanificationsCtrl () {
        
        this.selectedPlanifications = new List<Id>();
        
        ApexPages.getMessages().clear();

        this.initInfos(ApexPages.currentPage().getParameters().get('id'));
        
        if(this.mission.Planifications_de_facturation__r.size() > 0)
            this.initCheckBoxes();
        else
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, Label.Factu_CreatePlanificationFirst));
            
            
        for(RecordType rtype : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType='Facture__c']){
            this.recordTypes.put(rtype.DeveloperName, rtype.Id);
        }
    }
    
    /*
    * get mission and all associated planifications
    */
    private void initInfos(Id id){
        
        this.mission = [Select  m.name,
                                m.Id,
                                m.Contrat__c,
                                m.Contrat__r.Id,
                                m.RecordType.developerName,
                                (Select Id,
                                        Name,
                                        Prevision_HT__c,
                                        Statut__c,
                                        Mois__c,
                                        Periode_debut__c,
                                        Periode_fin__c,
                                        Pourcentage_Factur__c,
                                        Typologie_facturation__c,
                                        Nature_facturation__c,
                                        Commentaire_prevision__c,
                                        Dossier_salarie__c,
                                        Montant_HGNF__c,
                                        Date_d_HGNF__c,
                                        CurrencyIsoCode
                                        FROM Planifications_de_facturation__r
                                        WHERE Statut__c = 'Prévue'
                                            OR Statut__c = 'HGNF'
                                        ORDER BY Date_prevue__c ASC)
                                From Mission__c m
                                Where m.Id =:id];
        
    }
    
    /*
    * create list of planifications checkboxes
    */
    private void initCheckBoxes(){
        this.lsSelectOptionPlanifications = new List<Selectoption>();
        String description;
        
        for(Prevision_de_facturation__c pr : this.mission.Planifications_de_facturation__r){



            if(pr.Statut__c== 'HGNF' )
                description = pr.Mois__c + ' : ['+pr.CurrencyIsoCode+' ' + ((Decimal)pr.Prevision_HT__c).format() + '] '+' - Date HGNF : '+ pr.Date_d_HGNF__c.format() +' - Montant HGNF : ['+ pr.CurrencyIsoCode+' ' + ((Decimal)pr.Montant_HGNF__c).format()+']';
           else
            description = pr.Mois__c + ' : ['+pr.CurrencyIsoCode+' ' + ((Decimal)pr.Prevision_HT__c).format() + '] ';

			description +=  (pr.Pourcentage_Factur__c != null) ? ' [' + pr.Pourcentage_Factur__c +' %]' : '';   
            description +=  (pr.Commentaire_prevision__c != null) ? ' [' + pr.Commentaire_prevision__c +']' : '';   
            description +=  (pr.Typologie_facturation__c != null) ? ' [' + pr.Typologie_facturation__c + ']' : '';
            description +=  (pr.Nature_facturation__c != null) ? ' [' + pr.Nature_facturation__c + ']' : '';       
            description +=  (pr.Dossier_salarie__c != null) ? ' [' + pr.Dossier_salarie__c + ']' : '';
            description +=  (pr.Periode_debut__c != null) ? '['+System.Label.Factu_Periode + ' : ' + pr.Periode_debut__c.format() + ' - ' + pr.Periode_fin__c.format() + '] ' : '';
            
            this.lsSelectOptionPlanifications.add(new Selectoption(pr.Id, description));
            
        }
    }
    
    public PageReference CreateFactu(){
        
        
        if(this.selectedPlanifications.size() > 0){
            Pagereference ret = new Pagereference('/apex/FactuCreateFacture');
     
            ret.getParameters().put('MissionId',mission.Id);
            ret.getParameters().put('PlanifsId',string.join(this.selectedPlanifications,':'));
            
            ret.getParameters().put('retURL','apex/FactuSelectPlanifications?id='+mission.Id);
            return ret;
        }
        
        else{
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Vous devez selectionner au moins une planification'));
        }
        
        return null;
    }
    
    private Id getRecordTypeId(String RecordTypeName) {
        
        return this.recordTypes.get(RecordTypeName);
        
    }

    
    
  
    
}