gac_sb/objects/FieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>FieldIds</label>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Annee_CIR__c</fullName>
        <label>Année CIR</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>MissionsCIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOvalo__c.object
<CustomObject>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipLabel>Valorisations</relationshipLabel>
        <relationshipName>Valorisations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Valorisation</label>
    <nameField>
        <label>Nom de la valorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valorisations</pluralLabel>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <fields>
        <fullName>Annee_concernee__c</fullName>
        <inlineHelpText>Années correspondantes à la mission</inlineHelpText>
        <label>Année concernée</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>Outros</fullName>
                </value>
                <value>
                    <fullName>FINEP</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <description>Mission CIR</description>
        <label>CIR</label>
    </recordTypes>
    <recordTypes>
        <fullName>IL</fullName>
        <active>true</active>
        <description>Mission IL</description>
        <label>IL</label>
    </recordTypes>
    <recordTypes>
        <fullName>TAT</fullName>
        <active>true</active>
        <description>Mission TAT</description>
        <label>TAT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/Prevision_de_facturation__c.object
<CustomObject>
    <description>SF CONSULTING - permet de saisir des planifications de facturation</description>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>Planificiations_de_facturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <label>Mission</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mission__c.Contrat__c</field>
                <operation>equals</operation>
                <valueField>$Source.Contrat__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Profile.Id</field>
                <operation>notEqual</operation>
                <value>00eD0000001h8r5</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>Planifications_de_facturation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ValoINNOadvance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Valorisation INNO Advance</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipLabel>Planifications de facturation</relationshipLabel>
        <relationshipName>PlanificationsFacturation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Planification de facturation</label>
    <nameField>
        <displayFormat>Planif-{000000}</displayFormat>
        <label>N° Planification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planifications de facturation</pluralLabel>
    <recordTypes>
        <fullName>AT_Advance_Risk_Pro</fullName>
        <active>true</active>
        <description>AT Advance/Risk Pro Online</description>
        <label>AT Advance/Risk Pro Online</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <description>Prévision de facturation CIR</description>
        <label>CIR</label>
    </recordTypes>
    <recordTypes>
        <fullName>IL</fullName>
        <active>true</active>
        <label>IL</label>
    </recordTypes>
    <recordTypes>
        <fullName>TAT</fullName>
        <active>true</active>
        <description>Prévision de facturation TAT</description>
        <label>TAT</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/FactuCreatePlanificationFromMissionCtrl.cls
public with sharing class FactuCreatePlanificationFromMissionCtrl {
    
    private ApexPages.standardController stdCtrl;
    
    protected Map<String,Id> recordTypes = new Map<String,Id>();
    
    public SelectOption[] recordTypeTATSelectList {get; set;}
    
    public String recordTypeTAT {get; set;}
    
    public FactuCreatePlanificationFromMissionCtrl(ApexPages.standardController stdCtrl){
        this.stdCtrl = stdCtrl;
        for(RecordType rtype : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType='Prevision_de_facturation__c']){
            this.recordTypes.put(rtype.DeveloperName, rtype.Id);
        }
        
        // on init le menu list pour les missions TAT ou il y a le choix entre 2 planifs
        this.recordTypeTATSelectList = new List<selectOption>();
        this.recordTypeTATSelectList.add(new selectOption('TAT', 'TAT'));
        this.recordTypeTATSelectList.add(new selectOption('AT_Advance_Risk_Pro', 'AT Advance/Risk Pro Online'));
    }
    
    
    public PageReference createPlanification(){
        
        Mission__c m = (Mission__c) this.stdCtrl.getRecord();
        Pagereference ret = new Pagereference('/' + Prevision_de_facturation__c.sObjectType.getDescribe().getKeyPrefix() + '/e');

        // permet de transférer le bon contrat lors de la création de la planif
        ret.getParameters().put(FieldIds__c.getValues('Prevision_de_facturation__c.Contrat__c').Id__c,m.Contrat__r.ContractNumber); 
        ret.getParameters().put(FieldIds__c.getValues('Prevision_de_facturation__c.Contrat__c').Id__c+'_lkid',m.Contrat__c);
        
        // permet de transférer la bonne mission lors de la création de la planif
        ret.getParameters().put(FieldIds__c.getValues('Prevision_de_facturation__c.Mission__c').Id__c,m.Name); 
        ret.getParameters().put(FieldIds__c.getValues('Prevision_de_facturation__c.Mission__c').Id__c+'_lkid',m.Id);
        
        ret.getParameters().put('retURL',m.Id);
        
        // Si on est pas sur une mission TAT, on redirige tout de suite
        if(m.RecordType.developerName != 'TAT')
          ret.getParameters().put('RecordType',this.getRecordTypeId(m.RecordType.developerName));
        // Si on est sur du TAT, on return null pour afficher le formulaire de choix du type de planif ou alors on redirige si on est dans le cas où on a déja sélectionné le type de planif
        else if(m.RecordType.developerName == 'TAT'){
          if(this.recordTypeTAT != null)
            ret.getParameters().put('RecordType',this.getRecordTypeId(this.recordTypeTAT));
          else
            return null;
        }
        
        ret.setRedirect(true);
        return ret;
    }
    
    
    /**
    *   Methode utilisé pour la création de nouvelle planifs DEPUIS INNO Advance
    *   On ne passe donc pas une mission Factu mais une mission CIR
    *   @deprecated maintenant createPlanificationFromValoCIR()
    */
    public PageReference createPlanificationFromMissionCIR(){
       return null;
    }
    
    
    public PageReference createPlanificationFromValoCIR(){
        INNOvalo__c valo = (INNOvalo__c) this.stdCtrl.getRecord();
        Pagereference ret = new Pagereference('/' + Prevision_de_facturation__c.sObjectType.getDescribe().getKeyPrefix() + '/e');


        List<Mission__c> missionsFactu = [SELECT Id, Name FROM Mission__c WHERE Contrat__c = :valo.MissionCIR__r.Contrat__c AND Annee_concernee__c = :valo.MissionCIR__r.Annee_CIR__c];
        
        if(!missionsFactu.isEmpty()){
            ret.getParameters().put(FieldIds__c.getValues('Prevision_de_facturation__c.Mission__c').Id__c, missionsFactu[0].Name);
        }
        
        ret.getParameters().put(FieldIds__c.getValues('Prevision_de_facturation__c.Contrat__c').Id__c, valo.MissionCIR__r.Contrat__r.ContractNumber); 
        ret.getParameters().put(FieldIds__c.getValues('Prevision_de_facturation__c.Contrat__c').Id__c+'_lkid', valo.MissionCIR__r.Contrat__c);
        
        ret.getParameters().put(FieldIds__c.getValues('Prev_factu__c.ValoINNOadvance__c').Id__c, valo.Name); 
        ret.getParameters().put(FieldIds__c.getValues('Prev_factu__c.ValoINNOadvance__c').Id__c + '_lkid', valo.Id); 
        
        PageReference retUrl = Page.INNOfacturationValo;
        retUrl.getParameters().put('id', valo.Id);
        retUrl.getParameters().put('missionId', valo.MissionCIR__c);
        
        ret.getParameters().put('retURL', retUrl.getUrl());
        ret.getParameters().put('saveURL', retUrl.getUrl());
        ret.getParameters().put('RecordType',this.getRecordTypeId('CIR'));
        return ret;
    }
    
    
    private Id getRecordTypeId(String RecordTypeName) {
        
        return this.recordTypes.get(RecordTypeName);
        
    }
    
}