gac_sb/objects/FieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>FieldIds</label>
</CustomObject>

gac_sb/objects/Historique_Segmentation__c.object
<CustomObject>
    <fields>
        <fullName>Annee__c</fullName>
        <label>Année</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CIR_Annee_dernier_CIR__c</fullName>
        <label>Année Dernier CIR</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>&lt; 2009</fullName>
                </value>
                <value>
                    <fullName>Inconnu</fullName>
                </value>
                <value>
                    <fullName>Non communiqué</fullName>
                </value>
                <value>
                    <fullName>Non Concerné</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CIR_Annees_concernees_concurrent__c</fullName>
        <inlineHelpText>Indiquez les années concernées par le contrat du concurrent en place si vous avez l&apos;information</inlineHelpText>
        <label>CIR Années concernées concurrent</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2005</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CIR_Budget_R_D__c</fullName>
        <inlineHelpText>Renseignez la valeur en k€</inlineHelpText>
        <label>Budget R&amp;D (k€)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CIR_Concurrent__c</fullName>
        <inlineHelpText>Indiquez le concurrent en place chez le prospect, utilisez le choix &quot;Autres&quot; si le concurrent n&apos;apparait pas dans la liste, utilisez le choix &quot;Inconnu&quot; si vous n&apos;avez pas l&apos;information</inlineHelpText>
        <label>CIR Gestion du dossier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non concerné</fullName>
                </value>
                <value>
                    <fullName>Concurrent non communiqué</fullName>
                </value>
                <value>
                    <fullName>Interne</fullName>
                </value>
                <value>
                    <fullName>GAC</fullName>
                </value>
                <value>
                    <fullName>Absiskey</fullName>
                </value>
                <value>
                    <fullName>Acies</fullName>
                </value>
                <value>
                    <fullName>Actemis</fullName>
                </value>
                <value>
                    <fullName>Adocis</fullName>
                </value>
                <value>
                    <fullName>Alma Consulting Group</fullName>
                </value>
                <value>
                    <fullName>Capital High Tech</fullName>
                </value>
                <value>
                    <fullName>Crofthawk</fullName>
                </value>
                <value>
                    <fullName>Efficient Innovation</fullName>
                </value>
                <value>
                    <fullName>Effigroup Bloomon (ex Effinov)</fullName>
                </value>
                <value>
                    <fullName>Eurinnov</fullName>
                </value>
                <value>
                    <fullName>Expert comptable</fullName>
                </value>
                <value>
                    <fullName>F.Iniciativas</fullName>
                </value>
                <value>
                    <fullName>Fidal</fullName>
                </value>
                <value>
                    <fullName>Fineco</fullName>
                </value>
                <value>
                    <fullName>Hexalliance</fullName>
                </value>
                <value>
                    <fullName>IFEM</fullName>
                </value>
                <value>
                    <fullName>Ilceos</fullName>
                </value>
                <value>
                    <fullName>Inventage (ex GSM Subventium)</fullName>
                </value>
                <value>
                    <fullName>Kurt Salmon</fullName>
                </value>
                <value>
                    <fullName>Leyton</fullName>
                </value>
                <value>
                    <fullName>Lowendal Masai</fullName>
                </value>
                <value>
                    <fullName>OL &amp; DI</fullName>
                </value>
                <value>
                    <fullName>Sogedev</fullName>
                </value>
                <value>
                    <fullName>TAJ</fullName>
                </value>
                <value>
                    <fullName>Autres</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CIR_Dans_le_dispositif__c</fullName>
        <label>Dans le dispositif CIR</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non</fullName>
                </value>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>NSP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CIR_Depenses_eligibles__c</fullName>
        <inlineHelpText>Renseignez la valeur en k€</inlineHelpText>
        <label>Dépenses éligibles (k€)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CIR_Dernier_CIR__c</fullName>
        <inlineHelpText>Renseignez la valeur en k€</inlineHelpText>
        <label>Dernier CIR (k€)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CIR_Effectif_RD__c</fullName>
        <label>Effectif R&amp;D</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CIR_Enjeux_opportunite__c</fullName>
        <inlineHelpText>Champ obligatoire pour effectuer la demande d&apos;approbation.</inlineHelpText>
        <label>CIR Enjeux Compte</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Enjeux insuffisants</fullName>
                </value>
                <value>
                    <fullName>ECO</fullName>
                </value>
                <value>
                    <fullName>PREMIUM</fullName>
                </value>
                <value>
                    <fullName>STAR</fullName>
                </value>
                <value>
                    <fullName>Grand compte</fullName>
                </value>
                <value>
                    <fullName>Inéligible</fullName>
                </value>
                <value>
                    <fullName>Non communiqué</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compte__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Historiques segmentation</relationshipLabel>
        <relationshipName>Histos_segmentation</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IL_nb_sites_commerce__c</fullName>
        <label>Nombre de sites commerciaux</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_de_Credit_d_impot__c</fullName>
        <description>Permet de selectionner le type de Crédit d&apos;impôt</description>
        <label>Type de Crédit d&apos;impôt</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CIR</fullName>
                </value>
                <value>
                    <fullName>CII</fullName>
                </value>
                <value>
                    <fullName>CIR + CII</fullName>
                </value>
                <value>
                    <fullName>CIR + JEI</fullName>
                </value>
                <value>
                    <fullName>CII + JEI</fullName>
                </value>
                <value>
                    <fullName>CIR + CII + JEI</fullName>
                </value>
                <value>
                    <fullName>Aucun</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Historique Segmentation</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historiques segmentation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/V2Params__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AutoSynchOpp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AutoSynchOpp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BUFL__c</fullName>
        <label>BUFL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BUINNO__c</fullName>
        <label>BUINNO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BUOPTI__c</fullName>
        <label>BUOPTI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuDescribeId__c</fullName>
        <label>BuDescribeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>V2Params</label>
</CustomObject>

gac_sb/classes/V2AP01_SegmentationManager_TEST.cls
@isTest
private class V2AP01_SegmentationManager_TEST {

    static{
        V2Params__c par = new V2Params__c(AutoSynchOpp__c = true,BuInno__c = 'CIR,FI,CIN',buOpti__c = 'ACS,TAT',BuFL__c ='IL',BuDescribeId__c='TEST BU');
        insert par;
    }

	private static testMethod void TestBasicMethods() {
        FactuTestBase.init();
        Account a = FactuTestBase.Accounts.get(0);
        test.startTest();
        V2AP01_SegmentationManager.datesMercato = new map<id,map<string,Date>>();
        V2AP01_SegmentationManager.datesMercato.put(a.id,new map<string,Date>{'CIR_date_Mercato__c'=> date.today()});
        a.CIR_Dans_le_dispositif__c = 'Oui';
        a.CIR_Concurrent__c = 'Test Concurrent';
        update a;
        Historique_Segmentation__c h = V2AP01_SegmentationManager.applyToHisto(a, null);
        system.assertEquals(date.today().year(), h.annee__c);
        system.assertEquals('Oui', h.CIR_Dans_le_dispositif__c);
        
        h.CIR_Effectif_RD__c = 30;
        Account a2 = V2AP01_SegmentationManager.ApplyToAccount(h,a.id);
        a2.CIR_Concurrent__c = 'Test Concurrent';
        system.assertEquals(30, a2.CIR_Effectif_RD__c);
        Opportunity o = new Opportunity(AccountId = a2.id);
        V2AP01_SegmentationManager.applyToOpp(a2,o,'CIR',true);
        system.assertEquals('Test Concurrent', o.concurrent__c);
        test.stopTest();
        
	}
	
	private static testMethod void testTriggerSegmentationHandler(){
	    Account a =  new Account(Name = 'TestFactu 1',Siret__c='12343678900001', BillingStreet = '1 avenue de la cristallerie', BillingCity = 'SEVRES' , BillingPostalCode = '92370', BillingCountry = 'FRANCE',Industry = 'Santé',Activity__c='Biotech, biologie',
	    CIR_Dans_le_dispositif__c = 'Oui',CIR_Concurrent__c='Test Concurrent');
        insert a;
        Historique_Segmentation__c h = V2AP01_SegmentationManager.applyToHisto(a, null);  
        h.compte__c = a.id;
        insert h;
        Historique_SegmentationHandler.bAlreadyDone = false;
        Historique_SegmentationHandler.lAccountToUp.clear();
        test.startTest();
        h.CIR_Dans_le_dispositif__c = 'Non';
        update h;
        Account a2 = [SELECT id,CIR_Dans_le_dispositif__c from account where id = :a.id][0];
        system.assertEquals('Non', a2.CIR_Dans_le_dispositif__c);
        delete h;   //Couverture uniquement
	    
	}
	
	private static testMethod void TestSF2VFC02_AccountFRView(){
	     //FactuTestBase.init();
        Account a = new Account(Name = 'TestFactu 1',Siret__c='12343678900001', BillingStreet = '1 avenue de la cristallerie', BillingCity = 'SEVRES' , BillingPostalCode = '92370', BillingCountry = 'FRANCE',Industry = 'Santé',Activity__c='Biotech, biologie');
        insert a;
	     //Insertion d'un produit field id
	     insert new FieldIds__c(Name = 'Task.Produit__c',id__c='000000000000000');
	     Contact[] cons = new Contact[]{
	            new Contact(LastName = 'Test Contact', AccountId=a.id),
	            new Contact(LastName = 'Test Contact 2', AccountId=a.id)
	     };
	     insert cons;
	    Contact con0 = cons.get(0);
        Contact con1 = cons.get(1);
	     AccountContactRole[] oACRs = new AccountContactRole[]{
	         new AccountContactRole(AccountId = a.id, role = 'Interlocuteur commerce CIR',ContactId = con0.id),
	         new AccountContactRole(AccountId = a.id, role = 'Interlocuteur facturation CIR',ContactId = con0.id)
	     };


	     insert oACRs;
	     
	     AccountContactRole oIntCommerce = oACRs.get(0);
	     
	     test.startTest();
	     //Test du controller du composant:(couverture)
	     SF2VFC02_AccountFRView ctrlComp = new SF2VFC02_AccountFRView();
	     
	     //Test du vrai controller
	     ApexPages.StandardController sc = new ApexPages.StandardController(a);
	     SF2VFC02_AccountFRView ctrl = new SF2VFC02_AccountFRView(sc);
	     system.assertEquals(ctrl, ctrl.getCtrl());
	     
	     ctrl.getFieldsByBu();
	     ctrl.SwitchEdit();
	     system.assert(ctrl.bEdit);
	     Historique_Segmentation__c h = ctrl.lHistos.get(0);
         h.CIR_Budget_R_D__c = h.CIR_Effectif_RD__c = h.CIR_Depenses_eligibles__c = h.CIR_Dernier_CIR__c = 2010;
         h.CIR_Annee_dernier_CIR__c = '2010';
         h.CIR_Dans_le_dispositif__c = 'Non';
         h.type_de_credit_d_impot__c = 'CIR + CII + JEI';
	     h.CIR_enjeux_opportunite__c = 'PREMIUM';
	     
	     ctrl.refContactRoles.get(oIntCommerce.role).contactId = con1.id;
	     ctrl.refContactRoles.get('Interlocuteur facturation CIR').contactID = null;
	     ctrl.refContactRoles.get('Interlocuteur mission CIR').contactID = con0.id;
	     
	     ctrl.saveSegmentation();
	     
	     if(ApexPages.hasMessages()){
	         string msg = 'On ne devrait pas avoir de message d\'erreur, on obtient:';
	         for(ApexPages.Message m : ApexPages.getMessages()){
	             msg += m.getDetail();
	         }
	         system.assert(false,msg);
	     }
	     
	     
	     test.stopTest();
	     Map<Id,AccountContactRole> refACRs = new map<Id,AccountContactRole>([Select id, contactId, role from AccountContactRole where isDeleted = false]);
	     Account a2 = [Select id,CIR_Effectif_RD__c,CIR_Concurrent__c from account where id = : a.id Limit 1 ][0];
	     
	     system.assertEquals(2, refACRs.size());                                    //Test de la bonne insertion du nouveau role de contact
	     system.assert(!refACRs.containsKey(oACRs.get(1).id));                       //Test de la suppression du contact
	     system.assertEquals(con1.id,refACRs.get(oIntCommerce.id).contactId);    //Test de la modification de contact
	     
	     system.assertEquals(2010, a2.CIR_Effectif_RD__c);
	     ctrl.cancelSegmentation();
	}
	
	private static testMethod void TestSF2VFC02_AccountFRViewWithError(){
	    FactuTestBase.init();
	    Account a = FactuTestBase.Accounts.get(0);
	    test.startTest();
	     ApexPages.StandardController sc = new ApexPages.StandardController(a);
	     SF2VFC02_AccountFRView ctrl = new SF2VFC02_AccountFRView(sc);  // Erreur static, exception catchée
	    system.assert(ApexPages.hasMessages(ApexPages.severity.FATAL));
	    apexPages.getMessages().clear();
	    //On essaye d'enregistrer une valeur txt dans un champs numéro
	    ctrl.lHistos.get(0).put('IL_nb_sites_commerce__c',1234567); //ERREUR Sur l'update d'une opportunité liée
	    ctrl.saveSegmentation();
	    system.assert(ApexPages.hasMessages(ApexPages.severity.FATAL));
	    test.stopTest();
	}

    private static testMethod void TestPopulateOpportunity(){
        FactuTestBase.init();
        Opportunity o = FactuTestBase.Opportunities.get(0);
        o.AccountId = FactuTestBase.Accounts.get(0).id;
        ApexPages.StandardController sc = new ApexPages.StandardController(o);
	    SF2VFP01_UpdateOpportunitySegmentation ctrl = new SF2VFP01_UpdateOpportunitySegmentation(sc);
	    ctrl.populateAndRedirect();
	    //system.assert(ApexPages.hasMessages()); //On a forcément un message catché d'erreur étant donné qu'on a pas rempli de RV
    }
    
    private static testMethod void Testv2AP02_Concurrents(){
         Account a = new Account(Name = 'TestFactu 1',Siret__c='12343678900001', BillingStreet = '1 avenue de la cristallerie', BillingCity = 'SEVRES' , BillingPostalCode = '92370', BillingCountry = 'FRANCE',Industry = 'Santé',Activity__c='Biotech, biologie');
        insert a;
         Integer year = Date.today().year();
         test.startTest();
         Historique_Segmentation__c h = new Historique_Segmentation__c(Annee__c = year - 3, compte__c = a.id);
         h.CIR_Concurrent__c = 'Test Concurrent';
         h.CIR_annees_concernees_concurrent__c = (year -3)+';'+(year-2)+';'+(year-1)+';'+year;
         h.CIR_Budget_R_D__c = h.CIR_Effectif_RD__c = h.CIR_Depenses_eligibles__c = h.CIR_Dernier_CIR__c = 2010;
         h.CIR_Annee_dernier_CIR__c = '2010';
         h.CIR_Dans_le_dispositif__c = 'Non';
         h.type_de_credit_d_impot__c = 'CIR + CII + JEI';
          h.CIR_enjeux_opportunite__c = 'PREMIUM';
         insert h;
         Historique_Segmentation__c[] lHistos = [Select id , CIR_Concurrent__c from Historique_Segmentation__c where compte__c = : a.id];
         Account a2 = [Select id , CIR_Concurrent__c from Account where Id = : a.id LIMIT 1];
         system.assertEquals(4, lHistos.size());
         system.assertEquals('Test Concurrent', lHistos.get(0).CIR_Concurrent__c);
         system.assertEquals('Test Concurrent', lHistos.get(1).CIR_Concurrent__c);
         system.assertEquals('Test Concurrent', a2.CIR_Concurrent__c);
         system.debug('1ere partie du test effectuée; on continue');
         test.stopTest();
         
         //On reset le trigger bAlreadyDone
         Historique_SegmentationHandler.bAlreadyDone = false;
         Historique_Segmentation__c h2 = new Historique_Segmentation__c(Annee__c = year - 4, compte__c = a.id);
         h2.CIR_Concurrent__c = 'Test Concurrent 2';
         h2.CIR_annees_concernees_concurrent__c = (year -4)+';'+(year-3);
         h2.ACS_Concurrent__c = 'Test Concurrent 3';
         h2.ACS_annees_concernees_concurrent__c = (year -4)+';'+(year-3);
         Historique_Segmentation__c h3 = new Historique_Segmentation__c(Annee__c = year -5, compte__c = a.id); //On insere un autre historique pour vérifier les update concurrrent
         h3.TAT_Concurrent__c = 'Test Concurrent TAT';
         h3.TAT_annees_concernees_concurrent__c = (year -5)+';'+ (year -4)+';'+(year-3);
         insert new Historique_Segmentation__c[]{h2,h3};
         //On vérifie qu'on n' overwrite pas le cir et qu'on rempli l'ACS
         Historique_Segmentation__c[] lHistos2 = [Select id , CIR_Concurrent__c, ACS_Concurrent__c,TAT_Concurrent__c, annee__c from Historique_Segmentation__c where compte__c = : a.id and (annee__c = : (year-3) OR annee__c = : (year-4)) order by Annee__c ASC];
         system.assertEquals('Test Concurrent 2', lHistos2.get(0).CIR_Concurrent__c, 'Annee : '+ lHistos2.get(0).annee__c+ ' CIR champ concurrent ');
         system.assertEquals('Test Concurrent', lHistos2.get(1).CIR_Concurrent__c, 'Annee : '+ lHistos2.get(1).annee__c+' CIR champ concurrent ');  //Ne doit pas avoir été mis a jour
         system.assertEquals('Test Concurrent 3', lHistos2.get(1).ACS_Concurrent__c, 'Annee : '+ lHistos2.get(1).annee__c+' ACS champ concurrent ');
         system.assertEquals('Test Concurrent TAT', lHistos2.get(1).TAT_Concurrent__c, 'Annee : '+ lHistos2.get(1).annee__c+' TAT champ concurrent ');
         system.assertEquals('Test Concurrent TAT', lHistos2.get(0).TAT_Concurrent__c, 'Annee : '+ lHistos2.get(0).annee__c+' TAT champ concurrent ');
         
    }

}