gac_sb/objects/FieldIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>FieldIds</label>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <fields>
        <fullName>AT_Advance__c</fullName>
        <description>Cocher la case si le client souhaite utiliser l&apos;application AT Advance.</description>
        <inlineHelpText>Cocher la case si le client souhaite utiliser l&apos;application AT Advance.</inlineHelpText>
        <label>AT Advance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gratuit</fullName>
                </value>
                <value>
                    <fullName>Payant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compte__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cond_renouvellement__c</fullName>
        <label>Conditions de renouvellement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tacite</fullName>
                </value>
                <value>
                    <fullName>Par nouvel accord</fullName>
                </value>
                <value>
                    <fullName>Autre</fullName>
                </value>
                <value>
                    <fullName>Written consent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Conditions_particuli_res__c</fullName>
        <label>Conditions particulières</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Conds_facturation__c</fullName>
        <label>Conditions de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dépôt 2069A</fullName>
                </value>
                <value>
                    <fullName>50% au dépôt, le solde à la justification</fullName>
                </value>
                <value>
                    <fullName>Réception des taux AT/MP rectifiés / simulé</fullName>
                </value>
                <value>
                    <fullName>Avis de crédit URSSAF</fullName>
                </value>
                <value>
                    <fullName>70% S + 30% D + Succès</fullName>
                </value>
                <value>
                    <fullName>50% S + 50% D + Succès</fullName>
                </value>
                <value>
                    <fullName>30% S + 70% D + Succès</fullName>
                </value>
                <value>
                    <fullName>à réception accord dégrèvement</fullName>
                </value>
                <value>
                    <fullName>Autres</fullName>
                </value>
                <value>
                    <fullName>Dépot COFACE</fullName>
                </value>
                <value>
                    <fullName>à la signature du contrat DI</fullName>
                </value>
                <value>
                    <fullName>à la signature du contrat COFACE</fullName>
                </value>
                <value>
                    <fullName>Pourcentage</fullName>
                </value>
                <value>
                    <fullName>A l&apos;heure</fullName>
                </value>
                <value>
                    <fullName>Mixte</fullName>
                </value>
                <value>
                    <fullName>Notice Of Assessment</fullName>
                </value>
                <value>
                    <fullName>100% NOA reception</fullName>
                </value>
                <value>
                    <fullName>100% Benefit Reception</fullName>
                </value>
                <value>
                    <fullName>50% GAC sending &amp; 50% Submission to IRAS</fullName>
                </value>
                <value>
                    <fullName>50% GAC sending &amp; 50% NOA reception</fullName>
                </value>
                <value>
                    <fullName>50% NOA reception &amp; 50% Benefit Reception</fullName>
                </value>
                <value>
                    <fullName>100% GAC sending</fullName>
                </value>
                <value>
                    <fullName>100% Submission to IRAS</fullName>
                </value>
                <value>
                    <fullName>A l&apos;accord</fullName>
                </value>
                <value>
                    <fullName>Au taux rectifié/simulé</fullName>
                </value>
                <value>
                    <fullName>A l&apos;avis de crédit/remboursement URSSAF</fullName>
                </value>
                <value>
                    <fullName>A échoir</fullName>
                </value>
                <value>
                    <fullName>A échoir avec régularisation MS n-1</fullName>
                </value>
                <value>
                    <fullName>A l’accord avec régularisation MS n-1</fullName>
                </value>
                <value>
                    <fullName>Forfait</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Conds_paiement__c</fullName>
        <label>Conditions de paiement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15 dias</fullName>
                </value>
                <value>
                    <fullName>A réception</fullName>
                </value>
                <value>
                    <fullName>A 30 jours</fullName>
                </value>
                <value>
                    <fullName>40% à la livraison du dossier, solde de nos honoraires à la réception de l’avis de cotisation fédéral</fullName>
                </value>
                <value>
                    <fullName>A la réception de l’avis de cotisation fédéral ; Sur présentation de facture, payable sur réception</fullName>
                </value>
                <value>
                    <fullName>Sur présentation de facture, payable net 10 jours</fullName>
                </value>
                <value>
                    <fullName>Sur présentation de facture, payable net 30 jours</fullName>
                </value>
                <value>
                    <fullName>8 jours après réception</fullName>
                </value>
                <value>
                    <fullName>Immediate</fullName>
                </value>
                <value>
                    <fullName>30 days from reception</fullName>
                </value>
                <value>
                    <fullName>A 45 jours</fullName>
                </value>
                <value>
                    <fullName>A 60 jours</fullName>
                </value>
                <value>
                    <fullName>Upon IRAS approval</fullName>
                </value>
                <value>
                    <fullName>Autres</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Conds_remuneration__c</fullName>
        <label>Conditions de rémunération</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pourcentage du FI du client</fullName>
                </value>
                <value>
                    <fullName>Pourcentage du FI du consortium</fullName>
                </value>
                <value>
                    <fullName>Pourcentage du CIR</fullName>
                </value>
                <value>
                    <fullName>Pourcentage de l&apos;optimisation du CIR</fullName>
                </value>
                <value>
                    <fullName>Pourcentage des économies réalisées</fullName>
                </value>
                <value>
                    <fullName>Forfait</fullName>
                </value>
                <value>
                    <fullName>Mix Forfait + % FI client</fullName>
                </value>
                <value>
                    <fullName>Mix Forfait + % FI consortium</fullName>
                </value>
                <value>
                    <fullName>Mix</fullName>
                </value>
                <value>
                    <fullName>Barème par tranche</fullName>
                </value>
                <value>
                    <fullName>Pourcentage</fullName>
                </value>
                <value>
                    <fullName>Forfait + Pourcentage</fullName>
                </value>
                <value>
                    <fullName>Pourcentage du remboursement URSSAF</fullName>
                </value>
                <value>
                    <fullName>Flat percentage</fullName>
                </value>
                <value>
                    <fullName>Increasing percentage</fullName>
                </value>
                <value>
                    <fullName>Decreasing percentage</fullName>
                </value>
                <value>
                    <fullName>% (success fee)</fullName>
                </value>
                <value>
                    <fullName>Autres</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contrat_signe_par__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contrat signé par</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dur_e_initiale_mois__c</fullName>
        <label>Durée initiale (mois)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pr_avis_r_siliation_mois__c</fullName>
        <label>Préavis de résiliation (mois)</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Precision_facturation__c</fullName>
        <label>Précision facturation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Precision_paiement__c</fullName>
        <label>Précision paiement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Precision_remuneration__c</fullName>
        <label>Précision rémunération</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>R_mun_ration_future__c</fullName>
        <label>Rémunération future</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>6 mois</fullName>
                </value>
                <value>
                    <fullName>12 mois</fullName>
                </value>
                <value>
                    <fullName>18 mois</fullName>
                </value>
                <value>
                    <fullName>24 mois</fullName>
                </value>
                <value>
                    <fullName>36 mois</fullName>
                </value>
                <value>
                    <fullName>48 mois</fullName>
                </value>
                <value>
                    <fullName>60 mois</fullName>
                </value>
                <value>
                    <fullName>N+1</fullName>
                </value>
                <value>
                    <fullName>N+2</fullName>
                </value>
                <value>
                    <fullName>N+3</fullName>
                </value>
                <value>
                    <fullName>N+4</fullName>
                </value>
                <value>
                    <fullName>N+5</fullName>
                </value>
                <value>
                    <fullName>Toutes les années</fullName>
                </value>
                <value>
                    <fullName>3 année par CE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Pro_Online__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Cocher la case si le client souhaite utiliser le service Risk Pro Online.</description>
        <inlineHelpText>Cocher la case si le client souhaite utiliser le service Risk Pro Online.</inlineHelpText>
        <label>Risk Pro Online</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Statut_deploi_AT_Advance__c</fullName>
        <label>Statut déploiement AT Advance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En attente de la convention signée</fullName>
                </value>
                <value>
                    <fullName>Convention signée reçue / Déploiement à effectuer</fullName>
                </value>
                <value>
                    <fullName>Déploiement terminé / Identifiants transmis au client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Taux_de_r_mun_ration__c</fullName>
        <label>Taux de rémunération</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>nb_lic_atadvance__c</fullName>
        <label>Nombre de licence AT Advance</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <recordTypes>
        <fullName>TAT</fullName>
        <active>true</active>
        <description>Mission TAT</description>
        <label>TAT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/FactuCreateMissionCtrl.cls
public with sharing class FactuCreateMissionCtrl {
	
	private ApexPages.standardController stdCtrl;
	
	protected Map<String,Id> recordTypes = new Map<String,Id>();
	
	public FactuCreateMissionCtrl(ApexPages.standardController stdCtrl){
		this.stdCtrl = stdCtrl;
		for(RecordType rtype : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType='Mission__c']){
			this.recordTypes.put(rtype.DeveloperName, rtype.Id);
		}
	}
	
	public PageReference createMission(){
		
		Contract c = (Contract) this.stdCtrl.getRecord();
		Pagereference ret = new Pagereference('/' + Mission__c.sObjectType.getDescribe().getKeyPrefix() + '/e');

		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Contrat__c').Id__c,c.ContractNumber); 
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Contrat__c').Id__c+'_lkid',c.Id);
		
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Compte__c').Id__c,c.Account.Name); 
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Compte__c').Id__c+'_lkid',c.Account.Id);
		
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Cond_renouvellement__c').Id__c,c.Conditions_de_renouvellement__c);
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Conds_facturation__c').Id__c,c.Conditions_de_facturation__c);
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Conds_paiement__c').Id__c,c.Conditions_de_paiement__c);
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Conds_remuneration__c').Id__c,c.Conditions_de_remuneration__c);
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Precision_facturation__c').Id__c,c.Precision_facturation__c);
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Precision_paiement__c').Id__c,c.Precision_paiement__c);
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Precision_remuneration__c').Id__c,c.Precision_remuneration__c); 
		
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Contrat_signe_par__c').Id__c,c.Consultant_Commercial__r.Name);
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Contrat_signe_par__c').Id__c+'_lkid',c.Consultant_Commercial__c); 
		
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Conditions_particuli_res__c').Id__c,c.Conditions_particuli_res__c);
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Dur_e_initiale_mois__c').Id__c,String.valueOf(c.ContractTerm));
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Pr_avis_r_siliation_mois__c').Id__c,String.valueOf(c.Preavis_de_resiliation__c));
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.R_mun_ration_future__c').Id__c,c.Remuneratuin_future__c);
		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Taux_de_r_mun_ration__c').Id__c,String.valueOf(c.Taux_de_remuneration__c));
        
        if(c.recordType.developerName == 'TAT'){
            ret.getParameters().put(FieldIds__c.getValues('Mission__c.Statut_deploi_AT_Advance__c').Id__c,c.Statut_deploiement_AT_Advance__c);
    		ret.getParameters().put(FieldIds__c.getValues('Mission__c.AT_Advance__c').Id__c,c.AT_Advance__c);
    		ret.getParameters().put(FieldIds__c.getValues('Mission__c.nb_lic_atadvance__c').Id__c,String.valueOf(c.Nombre_de_licence_AT_Advance__c));
    		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Risk_Pro_Online__c').Id__c,c.Risk_Pro_Online__c?'1':'0');
    		ret.getParameters().put(FieldIds__c.getValues('Mission__c.ConditionsATA_RPO__c').Id__c,c.Conditions_AT_Advance_Risk_Pro_Online__c);
    		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Modalit_de_facturation__c').Id__c,c.Modalit_de_facturation__c);
    		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Montant_forfait__c').Id__c,String.valueOf(c.Montant_forfait__c)); 
    		ret.getParameters().put(FieldIds__c.getValues('Mission__c.Periode_Fact_forfait__c').Id__c,c.Periode_Facturation_forfait__c);
        }

		ret.getParameters().put('retURL',c.Id);
		ret.getParameters().put('RecordType',this.getRecordTypeId(c.RecordType.developerName));
		return ret;

    }
	
	private Id getRecordTypeId(String RecordTypeName) {
		
		return this.recordTypes.get(RecordTypeName);
		
	}

}