gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>Avancement__c</fullName>
        <formula>IF(Nombre_jours_theoriques_Total__c == 0,
0,
Nombre_jours_travailles_Total__c / Nombre_jours_theoriques_Total__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Avancement</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Annee_CIR__c</fullName>
        <label>Année CIR</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Avancement__c</fullName>
        <formula>IF(Nombre_jours_theoriques_Total__c == 0, 0, Nombre_jours_travailles_total__c / Nombre_jours_theoriques_Total__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Avancement</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Consultants_exterieurs__c</fullName>
        <label>Consultants exterieurs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultants_fiscalistes__c</fullName>
        <label>Consultants fiscalistes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultants_scientifiques__c</fullName>
        <label>Consultants scientifiques</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Managers__c</fullName>
        <label>Managers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactif / en attente de renouvellement</fullName>
                </value>
                <value>
                    <fullName>Inactif / en attente de lancement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Valorisation</fullName>
                </value>
                <value>
                    <fullName>Justification</fullName>
                </value>
                <value>
                    <fullName>Terminée</fullName>
                </value>
                <value>
                    <fullName>Terminée - Dossier à 0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>CASE( Phase__c , 
&apos;Inactif / en attente de renouvellement&apos;, &apos;Inactive&apos;, 
&apos;Inactif / en attente de lancement&apos;, &apos;Inactive&apos;, 
&apos;Terminée&apos;, IF(NombreCFenCours__c &gt; 0, &apos;Active&apos;, &apos;Terminée&apos;), 
&apos;Terminée - Dossier à 0&apos;, &apos;Terminée&apos;, 
&apos;Active&apos;)</formula>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taux_CIR__c</fullName>
        <label>Taux CIR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/INNOhomeCtrl.cls
public with sharing class INNOhomeCtrl {

	public SelectOption[] anneesCIR {get; set;}
	
	public String[] consultants {get; set;}
	public String[] consultantsFiscalistes {get; set;}
	
	public List<SelectOption> missionRecordTypes {get; set;}
	public Id selectedMissionRecordType {get; set;}
	
	public List<SelectOption> statuts {get; set;}
	public String selectedStatut {get; set;}
	

	public transient INNOmission__c[] missions {get;set;}
	
	public Boolean userHasFullAccess {get; set;}
	
	public Boolean userIsManager {get; set;}
	
	public INNOhomeCtrl(){
		
		this.statuts = new List<SelectOption>{new SelectOption('Active', 'Actives'), new SelectOption('Inactive', 'Inactives'), new SelectOption('Terminée', 'Terminées')};
		
		this.missionRecordTypes = new List<SelectOption>();
		for(RecordType rt : [SELECT Id, Name, DeveloperName FROM RecordType WHERE SObjectType = 'INNOmission__c' ORDER BY Name]){
			this.missionRecordTypes.add(new SelectOption(rt.Id, rt.Name));
			if(rt.DeveloperName == 'CIR')
				this.selectedMissionRecordType = rt.Id;
		}
		
		this.selectedStatut = 'Active';

		this.userHasFullAccess = INNOmissionUtils.userHasFullAccess();
		this.userIsManager = INNOmissionUtils.userIsManager();
		
		//Init les années CIR disponibles
		this.anneesCIR = new List<Selectoption>{ new SelectOption('', 'Toutes')};
		for(Integer y = System.today().addYears(2).year(); y > 2006 ; y--)
			this.anneesCIR.add( new SelectOption(String.valueOf(y), String.valueOf(y)) );
			
			
		//Init les consultant disponibles
		this.consultants = new List<String>();
		for(AggregateResult aggr : [SELECT Utilisateur__r.Name u FROM INNOequipeConsulting__c GROUP BY Utilisateur__r.Name])
			this.consultants.add(String.valueOf(aggr.get('u')));
		
		this.initMissions();
		
	}
	
	
	public void initMissions(){
		/*
		*	Seletionne uniquement les missions auquelles j'ai accès grace aux sharing rules
		*/
		String missionQuery = 'SELECT Id, Name, Annee_CIR__c, Phase__c, Avancement__c, Consultants_scientifiques__c, Consultants_fiscalistes__c, Consultants_exterieurs__c, Managers__c';
		
		//Pour les non admin, on recup aussi l'equipe consulting du user courant pour pouvoir récupérer son avancement
		if(!this.userHasFullAccess)
			missionQuery += ', (SELECT Id, Avancement__c FROM EquipesConsulting__r WHERE Utilisateur__c = \'' + UserInfo.getUserId() + '\')';
		
		missionQuery += ' FROM INNOmission__c WHERE Statut__c = :selectedStatut AND RecordTypeId = :selectedMissionRecordType ORDER BY Annee_CIR__c DESC LIMIT 3000';
		
		this.missions = Database.query(missionQuery);
	
		for(INNOmission__c m : this.missions){
			
			if(!this.userHasFullAccess)
				m.Taux_CIR__c = (m.EquipesConsulting__r.isEmpty() ? null : m.EquipesConsulting__r[0].Avancement__c);
			else
				m.Taux_CIR__c = m.Avancement__c;
			
			m.Consultants_scientifiques__c = (String.isNotBlank(m.Consultants_scientifiques__c) ? m.Consultants_scientifiques__c.replace(' - ', '<br />') : '') + 
												(String.isNotBlank(m.Consultants_fiscalistes__c) ? '<br />' + m.Consultants_fiscalistes__c.replace(' - ', '<br />') : '') + 
												(String.isNotBlank(m.Consultants_exterieurs__c) ? '<br />' + m.Consultants_exterieurs__c.replace(' - ', '<br />') : '');
												
			
			m.Managers__c = (String.isNotBlank(m.Managers__c) ? m.Managers__c.replace(' - ', '<br />') : '');
		}

		
		
	}
	
		
	
}