gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Audit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours programmés - Audit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Controle__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours programmés - Contrôle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Justification__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours programmés - Justif</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Valorisation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours programmés - Valo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Audit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours travaillés - Audit</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Controle__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours travaillés - Contrôle</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Justification__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours travaillés - Justif</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Valorisation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours travaillés - Valo</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOtimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>Duree__c</fullName>
        <description>La durée passé en jour (compris entre 0 et 1):
1 = toute la journée
0.5 = une demi-journée</description>
        <label>Durée</label>
        <precision>3</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission_CIR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>TimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passée</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Valorisation</fullName>
                </value>
                <value>
                    <fullName>Justification</fullName>
                </value>
                <value>
                    <fullName>Contrôle</fullName>
                </value>
                <value>
                    <fullName>Formation</fullName>
                </value>
                <value>
                    <fullName>Disponibilité</fullName>
                </value>
                <value>
                    <fullName>Avant-Vente / AO</fullName>
                </value>
                <value>
                    <fullName>AS/DI</fullName>
                </value>
                <value>
                    <fullName>CP / RTT</fullName>
                </value>
                <value>
                    <fullName>DUP</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>ASDI</fullName>
                    <isActive>false</isActive>
                    <label>ASDI</label>
                </value>
                <value>
                    <fullName>Administratif</fullName>
                    <isActive>false</isActive>
                    <label>Administratif</label>
                </value>
                <value>
                    <fullName>CP</fullName>
                    <isActive>false</isActive>
                    <label>CP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phase_technique__c</fullName>
        <formula>SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(TEXT(Phase__c), &apos;Avant-Vente / AO&apos;, &apos;AvantVenteAO&apos;), &apos;Disponibilité&apos;, &apos;Disponibilite&apos;), &apos;Contrôle&apos;, &apos;Controle&apos;), &apos;AS/DI&apos;, &apos;ASDI&apos;), &apos;CP / RTT&apos;, &apos;CP&apos;)</formula>
        <label>Phase technique</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>INNOtimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TimeSheet CIR</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>TimeSheets INNO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheets CIR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/classes/INNOtimeSheetHandler.cls
/**
 * Class INNOtimeSheetHandler
 *
 * Trigger Handler for the INNOtimeSheet__c	 SObject. This class implements the ITrigger
 * interface to help ensure the trigger code is bulkified and all in one place.
 */

public with sharing class INNOtimeSheetHandler implements ITrigger {
	
	private Set<Id> involvedMissionIds = new Set<Id>();
	private Set<Id> involvedUserIds = new Set<Id>();
	
	
	// Constructor
	public INNOtimeSheetHandler(){
	}

	
	public void bulkBefore(){
	}
	
	public void bulkAfter(){
	}
		
	public void beforeInsert(SObject so){
	}
	
	public void beforeUpdate(SObject oldSo, SObject so){
	}
	
	
	public void beforeDelete(SObject so){	
	}
	
	public void afterInsert(SObject so){
		INNOtimeSheet__c ts = (INNOtimeSheet__c) so;
		
		this.involvedMissionIds.add(ts.Mission_CIR__c);
		this.involvedUserIds.add(ts.Utilisateur__c);
	}
	
	public void afterUpdate(SObject oldSo, SObject so){
		INNOtimeSheet__c ts = (INNOtimeSheet__c) so;
		
		this.involvedMissionIds.add(ts.Mission_CIR__c);
		this.involvedUserIds.add(ts.Utilisateur__c);
	}
	
	public void afterDelete(SObject so){
		INNOtimeSheet__c ts = (INNOtimeSheet__c) so;
		
		this.involvedMissionIds.add(ts.Mission_CIR__c);
		this.involvedUserIds.add(ts.Utilisateur__c);
	}
	
	/**
	 * andFinally
	 *
	 * This method is called once all records have been processed by the trigger. Use this 
	 * method to accomplish any final operations such as creation or updates of other records.
	 */
	public void andFinally(){
		
		this.computeEquipeConsultingRollups();
		
	}
	
	
	private void computeEquipeConsultingRollups(){
		
		this.involvedMissionIds.remove(null);
		this.involvedUserIds.remove(null);
		
		
		if(!this.involvedMissionIds.isEmpty()){
			
			/**
			 * Création des copies des equipes consulting à updater
			 *  - clé: userId-missionId
			 *  - valeur: l'equipe consulting correspondante
			 */
			Map<String, INNOequipeConsulting__c> equipesRecords = new Map<String, INNOequipeConsulting__c>();
		
			for(INNOequipeConsulting__c eq : [SELECT Id, Utilisateur__c, MissionCIR__c FROM INNOequipeConsulting__c WHERE MissionCIR__c IN :this.involvedMissionIds AND Utilisateur__c IN :this.involvedUserIds]){
				equipesRecords.put(eq.Utilisateur__c + '-' + eq.MissionCIR__c, new INNOequipeConsulting__c(Id 											= eq.Id,
																											Nombre_jours_travailles_Audit__c 			= 0,
																											Nombre_jours_travailles_Valorisation__c 	= 0,
																											Nombre_jours_travailles_Justification__c 	= 0,
																											Nombre_jours_travailles_Controle__c 		= 0,
																											Nombre_jours_programmes_Audit__c 			= 0,
																											Nombre_jours_programmes_Valorisation__c 	= 0,
																											Nombre_jours_programmes_Justification__c 	= 0,
																											Nombre_jours_programmes_Controle__c 		= 0
																										));
			}
			
			system.debug(equipesRecords);
			
			INNOequipeConsulting__c tempEq;
			String tempFieldName;
			for(INNOtimeSheet__c ts : [SELECT Id, Duree__c, Mission_CIR__c, Utilisateur__c, Phase_technique__c, Passee__c FROM INNOtimeSheet__c WHERE Mission_CIR__c IN :this.involvedMissionIds AND Utilisateur__c IN :this.involvedUserIds AND Duree__c > 0 AND Phase__c IN ('Audit', 'Valorisation', 'Justification', 'Contrôle', 'Controle')]){
				
				tempEq = equipesRecords.get(ts.Utilisateur__c + '-' + ts.Mission_CIR__c);
				
				if(tempEq != null){
					tempFieldName = 'Nombre_jours_' + (ts.Passee__c ? 'travailles' : 'programmes') + '_' + ts.Phase_technique__c + '__c';
					tempEq.put(tempFieldName, (decimal) tempEq.get(tempFieldName) + ts.Duree__c);
				}
	
				
			}
			
			update equipesRecords.values();
		}
		
		
	}
	
}