gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Permet de rendre actif un utilisateur</description>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Rôle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Consultant scientifique</fullName>
                    <default>true</default>
                    <label>Consultant scientifique</label>
                </value>
                <value>
                    <fullName>Consultant fiscaliste</fullName>
                </value>
                <value>
                    <fullName>Consultant extérieur</fullName>
                </value>
                <value>
                    <fullName>Rédacteur scientifique</fullName>
                </value>
                <value>
                    <fullName>Redacteur scientifique RO</fullName>
                    <label>Rédacteur scientifique RO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Annee_CIR__c</fullName>
        <label>Année CIR</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>MissionsCIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taux_CIR__c</fullName>
        <label>Taux CIR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <fields>
        <fullName>Annee_concernee__c</fullName>
        <inlineHelpText>Années correspondantes à la mission</inlineHelpText>
        <label>Année concernée</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>Outros</fullName>
                </value>
                <value>
                    <fullName>FINEP</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <description>Mission CIR</description>
        <label>CIR</label>
    </recordTypes>
    <recordTypes>
        <fullName>Consulting</fullName>
        <active>true</active>
        <description>ES - Consulting</description>
        <label>Consulting</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/ApexSharingRecalc_Mission_Test.cls
@isTest
public with sharing class ApexSharingRecalc_Mission_Test {


	public static testMethod void testMissionApexSharingRecalculation() {
		
		
		
	//Insertion de 100 Contracts
    	Account acc = new Account(Name = 'Test 1', BillingPostalCode = '92370', BillingCountry = 'FRANCE',Industry = 'Santé', Activity__c = 'Biotech, biologie', Date_de_creation_societe__c = system.today().addYears(-1), SIRET__c = '1284621900001', Type_d_etablissement__c = 'Principal');
    	insert acc;

		Id CIRcontractRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Contract' AND DeveloperName = 'CIR'][0].Id;
		List<Contract> contracts = new List<Contract>();
		for(Integer i = 0; i < 100; i++){
			contracts.add(new Contract( AccountId = acc.Id, Status = 'Non activé', recordTypeId = CIRcontractRecordTypeId, Date_de_reception_du_contrat__c = date.today(), Annees_concernees__c = '2017'));
		}
		insert contracts;

	//Insertion de 100 missions INNO Advance et 100 missions Factu
		Id CIRmissionRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Mission__c' AND DeveloperName = 'CIR'][0].Id;
		List<INNOmission__c> missionsINNO = new List<INNOmission__c>();
		List<Mission__c> missionsFactu = new List<Mission__c>();
		for(Contract c : contracts){
			missionsINNO.add(new INNOmission__c(Contrat__c = c.Id, Name = c.Annees_concernees__c, Annee_CIR__c = '2017', Taux_CIR__c = 30));
			missionsFactu.add(new Mission__c(Contrat__c = c.Id, Annee_concernee__c = c.Annees_concernees__c, RecordTypeId = CIRmissionRecordTypeId));
		}
		    										
		insert missionsINNO;
		insert missionsFactu;
		
		
	//Insertion des equipes consulting (1 Manager et 1 Consultant extérieur sur chaquune des 100 missions INNO Advance précédemment insérées)
		User manager = [SELECT ID, UserName FROM User WHERE IsActive = true AND UserType = 'Standard' AND Profile.Name = 'FR - Tech - Manager - Inno'][0];
		User consultant = [SELECT ID, UserName FROM User WHERE IsActive = true AND UserType = 'Standard' AND Profile.Name = 'FR - Tech - Consultant - Inno'][0];
		
		List<INNOequipeConsulting__c> equipes = new List<INNOequipeConsulting__c>();
		for(INNOmission__c m : missionsINNO){
			equipes.add(new INNOequipeConsulting__c(MissionCIR__c = m.Id, Role__c = 'Manager', Utilisateur__c = manager.Id, Actif__c = true));
			equipes.add(new INNOequipeConsulting__c(MissionCIR__c = m.Id, Role__c = 'Consultant extérieur', Utilisateur__c = consultant.Id, Actif__c = true));
		}
		insert equipes;
		
		
		
	//Lancement du batch ApexSharingRecalc_Mission
		Test.StartTest();
		
		ApexSharingRecalc_Mission missionApexSharingRecalculation = new ApexSharingRecalc_Mission();
		Database.executeBatch(missionApexSharingRecalculation);
		System.enqueueJob(new ApexSharingRecalc_Mission());
        
		Test.stopTest();
	
	
	//Test du partage des missions Factus par le batch ApexSharingRecalc_Mission	
		List<Mission__Share> missionsFactuShare = [SELECT Id, ParentId, UserOrGroupId, AccessLevel FROM Mission__Share WHERE RowCause = :Schema.Mission__Share.RowCause.INNO_Advance__c];
		
		Boolean managerFound, consultantFound;
		for(Mission__c m : missionsFactu){
			
			managerFound = consultantFound = false;
			
			for(Mission__Share ms : missionsFactuShare){
				if(ms.ParentId == m.Id && ms.UserOrGroupId == manager.Id && ms.AccessLevel == 'Edit')
					managerFound = true;
				else if(ms.ParentId == m.Id && ms.UserOrGroupId == consultant.Id && ms.AccessLevel == 'Read')
					consultantFound = true;
				
				if(managerFound && consultantFound)
					break;
			}
			
			system.assert(managerFound);
			system.assert(consultantFound);
		}
	}
	
	
}