gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Permet de rendre actif un utilisateur</description>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mission_Utilisateur__c</fullName>
        <description>Champ technique</description>
        <formula>CASESAFEID(MissionCIR__c) + &quot;-&quot; + CASESAFEID(Utilisateur__c)</formula>
        <label>Mission-Utilisateur</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Audit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours programmés - Audit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Controle__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours programmés - Contrôle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Justification__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours programmés - Justif</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Valorisation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours programmés - Valo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_restants_Audit__c</fullName>
        <formula>Nombre_jours_theoriques_Audit__c - Nombre_jours_travailles_Audit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nombre de jours restants - Audit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_restants_Controle__c</fullName>
        <formula>Nombre_jours_theoriques_Controle__c - Nombre_jours_travailles_Controle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nombre de jours restants - Contrôle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_restants_Justification__c</fullName>
        <formula>Nombre_jours_theoriques_Justification__c - Nombre_jours_travailles_Justification__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nombre de jours restants - Justif</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_restants_Valorisation__c</fullName>
        <formula>Nombre_jours_theoriques_Valorisation__c - Nombre_jours_travailles_Valorisation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nombre de jours restants - Valo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Audit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Audit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Controle__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Contrôle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Justification__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Justif</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Valorisation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Valo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Audit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours travaillés - Audit</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Controle__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours travaillés - Contrôle</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Justification__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours travaillés - Justif</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Valorisation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours travaillés - Valo</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Rôle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Consultant scientifique</fullName>
                    <default>true</default>
                    <label>Consultant scientifique</label>
                </value>
                <value>
                    <fullName>Consultant fiscaliste</fullName>
                </value>
                <value>
                    <fullName>Consultant extérieur</fullName>
                </value>
                <value>
                    <fullName>Rédacteur scientifique</fullName>
                </value>
                <value>
                    <fullName>Redacteur scientifique RO</fullName>
                    <label>Rédacteur scientifique RO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Nombre_jours_programmes_Audit__c</fullName>
        <label>Nombre de jours programmés - Audit</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_programmes_Audit__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Controle__c</fullName>
        <label>Nombre de jours programmés - Contrôle</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_programmes_Controle__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Justification__c</fullName>
        <label>Nombre de jours programmés - Justif</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_programmes_Justification__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_programmes_Valorisation__c</fullName>
        <label>Nombre de jours programmés - Valo</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_programmes_Valorisation__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Audit__c</fullName>
        <label>Nombre de jours théoriques - Audit</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Audit__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Controle__c</fullName>
        <label>Nombre de jours théoriques - Contrôle</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Controle__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Justification__c</fullName>
        <label>Nombre de jours théoriques - Justif</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Justification__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Valorisation__c</fullName>
        <label>Nombre de jours théoriques - Valo</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Valorisation__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Audit__c</fullName>
        <label>Nombre de jours travaillés - Audit</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_travailles_Audit__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Controle__c</fullName>
        <label>Nombre de jours travaillés - Contrôle</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_travailles_Controle__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Justification__c</fullName>
        <label>Nombre de jours travaillés - Justif</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_travailles_Justification__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_travailles_Valorisation__c</fullName>
        <label>Nombre de jours travaillés - Valo</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_travailles_Valorisation__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>CASE( Phase__c , 
&apos;Inactif / en attente de renouvellement&apos;, &apos;Inactive&apos;, 
&apos;Inactif / en attente de lancement&apos;, &apos;Inactive&apos;, 
&apos;Terminée&apos;, IF(NombreCFenCours__c &gt; 0, &apos;Active&apos;, &apos;Terminée&apos;), 
&apos;Terminée - Dossier à 0&apos;, &apos;Terminée&apos;, 
&apos;Active&apos;)</formula>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOtimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>Mission_CIR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>TimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passée</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>INNOtimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TimeSheet CIR</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>TimeSheets INNO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheets CIR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/classes/INNOequipeConsultingReassignCtrl.cls
public without sharing class INNOequipeConsultingReassignCtrl{

    public INNOequipeConsulting__c dummyEquipe {get; set;}
    
    public List<TeamMember> results {get; set;}
    
    
    public INNOequipeConsultingReassignCtrl(){
        
        this.dummyEquipe = new INNOequipeConsulting__c();
        
    }
    
    
    
    public void searchEquipes(){
        
        this.results = new List<TeamMember>();
        
        for(INNOequipeConsulting__c eq : [SELECT Id, 
                                                MissionCIR__c,
                                                MissionCIR__r.Name,
                                                Role__c, 
                                                Nombre_jours_programmes_Audit__c, 
                                                Nombre_jours_programmes_Controle__c, 
                                                Nombre_jours_programmes_Justification__c, 
                                                Nombre_jours_programmes_Valorisation__c, 
                                                Nombre_jours_theoriques_Audit__c, 
                                                Nombre_jours_theoriques_Controle__c, 
                                                Nombre_jours_theoriques_Justification__c, 
                                                Nombre_jours_theoriques_Valorisation__c, 
                                                Nombre_jours_travailles_Audit__c, 
                                                Nombre_jours_travailles_Controle__c, 
                                                Nombre_jours_travailles_Justification__c, 
                                                Nombre_jours_travailles_Valorisation__c,
                                                Nombre_jours_restants_Audit__c,
                                                Nombre_jours_restants_Valorisation__c, 
                                                Nombre_jours_restants_Justification__c,
                                                Nombre_jours_restants_Controle__c 
                                            FROM INNOequipeConsulting__c
                                            WHERE MissionCIR__r.Statut__c IN ('Inactive', 'Active')
                                                AND Utilisateur__c = :this.dummyEquipe.Utilisateur__c
                                                AND Actif__c = true
                                                AND (Nombre_jours_restants_Audit__c > 0
                                                    OR Nombre_jours_restants_Valorisation__c > 0
                                                    OR Nombre_jours_restants_Justification__c > 0
                                                    OR Nombre_jours_restants_Controle__c > 0
                                                    )
                                            ORDER BY MissionCIR__r.Name]){
            
            this.results.add(new TeamMember(eq));
                
        }
    }
    
    public void saveMembers(){
        
        List<INNOequipeConsulting__c> membersToUpsert = new List<INNOequipeConsulting__c>();
        
        
        /**
         * Initisalitation de dupeMembersByMissionIdUserId avec:
         *  - clé: IdMissionCIR-IdUser
         *  - valeur: objet equipe consulting pour cet mission/utilisateur s'il existe
         */
        Map<String, INNOequipeConsulting__c> dupeMembersByMissionIdUserId = new Map<String ,INNOequipeConsulting__c>();
        for(TeamMember member : this.results){
            dupeMembersByMissionIdUserId.put(member.newMember.MissionCIR__c + '-' + member.newMember.Utilisateur__c, null);
        }
        for(INNOequipeConsulting__c eq : [SELECT Id, Mission_Utilisateur__c, Nombre_jours_theoriques_Audit__c, Nombre_jours_theoriques_Valorisation__c, Nombre_jours_theoriques_Justification__c, Nombre_jours_theoriques_Controle__c FROM INNOequipeConsulting__c WHERE Mission_Utilisateur__c IN :dupeMembersByMissionIdUserId.keySet()]){
            dupeMembersByMissionIdUserId.put(eq.Mission_Utilisateur__c, eq);
        }
        
        System.debug(dupeMembersByMissionIdUserId);
        List<Id> reaffectedMissionIds = new List<Id> ();
        
        INNOequipeConsulting__c tempDupeMember;
        for(TeamMember member : this.results){
            
            if(member.newMember.Utilisateur__c != null && member.newMember.Utilisateur__c != this.dummyEquipe.Utilisateur__c){
                
                //Désactivation et décrémentation des temps théorique de l'ancien utilisateur
                member.oldMember.Actif__c = false;
                member.oldMember.Nombre_jours_theoriques_Audit__c           = Math.min(member.oldMember.Nombre_jours_travailles_Audit__c, member.oldMember.Nombre_jours_theoriques_Audit__c);
                member.oldMember.Nombre_jours_theoriques_Valorisation__c    = Math.min(member.oldMember.Nombre_jours_travailles_Valorisation__c, member.oldMember.Nombre_jours_theoriques_Valorisation__c);
                member.oldMember.Nombre_jours_theoriques_Justification__c   = Math.min(member.oldMember.Nombre_jours_travailles_Justification__c, member.oldMember.Nombre_jours_theoriques_Justification__c);
                member.oldMember.Nombre_jours_theoriques_Controle__c        = Math.min(member.oldMember.Nombre_jours_travailles_Controle__c, member.oldMember.Nombre_jours_theoriques_Controle__c);
                membersToUpsert.add(member.oldMember);
                
                
                tempDupeMember = dupeMembersByMissionIdUserId.get(member.newMember.MissionCIR__c + '-' + member.newMember.Utilisateur__c);
                
                //Si le nouvel utilisateur est déjà dans l'equipe consulting de la mission, on modifie ses temps theoriques
                if(tempDupeMember != null){
                    tempDupeMember.Actif__c = true;
                    tempDupeMember.Role__c = member.newMember.Role__c;
    
                    tempDupeMember.Nombre_jours_theoriques_Audit__c += member.newMember.Nombre_jours_theoriques_Audit__c;
                    tempDupeMember.Nombre_jours_theoriques_Valorisation__c += member.newMember.Nombre_jours_theoriques_Valorisation__c;
                    tempDupeMember.Nombre_jours_theoriques_Justification__c += member.newMember.Nombre_jours_theoriques_Justification__c;
                    tempDupeMember.Nombre_jours_theoriques_Controle__c += member.newMember.Nombre_jours_theoriques_Controle__c;
                    membersToUpsert.add(tempDupeMember);
                }
                //Sinon ajout du nouveau utilisateur dans l'equipe consulting
                else
                    membersToUpsert.add(member.newMember);
                    
                reaffectedMissionIds.add(member.newMember.MissionCIR__c);  
            }
        }
        
        upsert membersToUpsert;
        
        delete [SELECT Id FROM INNOtimeSheet__c WHERE Utilisateur__c = :this.dummyEquipe.Utilisateur__c AND Passee__c = false AND Mission_CIR__c IN :reaffectedMissionIds];
        
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, reaffectedMissionIds.size() + ' missions réaffectées'));
        
        this.searchEquipes();
    }
    
    
    
    /**
     * Wrapper class correspondant à une equipe consulting à réattribuer
     */
    public class TeamMember{
        
        public INNOequipeConsulting__c oldMember {get; set;}
        
        public INNOequipeConsulting__c newMember {get; set;}
        
        
        
        public TeamMember(INNOequipeConsulting__c oldMember){
            this.oldMember = oldMember;
            
            this.newMember = new INNOequipeConsulting__c(MissionCIR__c                               = oldMember.MissionCIR__c, 
                                                            Role__c                                     = oldMember.Role__c,
                                                            Nombre_jours_theoriques_Audit__c            = Math.max(0, oldMember.Nombre_jours_restants_Audit__c),
                                                            Nombre_jours_theoriques_Valorisation__c     = Math.max(0, oldMember.Nombre_jours_restants_Valorisation__c),
                                                            Nombre_jours_theoriques_Justification__c    = Math.max(0, oldMember.Nombre_jours_restants_Justification__c),
                                                            Nombre_jours_theoriques_Controle__c         = Math.max(0, oldMember.Nombre_jours_restants_Controle__c)
                                                            );
            
        }
        
    }
}