gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Permet de rendre actif un utilisateur</description>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Rôle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Consultant scientifique</fullName>
                    <default>true</default>
                    <label>Consultant scientifique</label>
                </value>
                <value>
                    <fullName>Consultant fiscaliste</fullName>
                </value>
                <value>
                    <fullName>Consultant extérieur</fullName>
                </value>
                <value>
                    <fullName>Rédacteur scientifique</fullName>
                </value>
                <value>
                    <fullName>Redacteur scientifique RO</fullName>
                    <label>Rédacteur scientifique RO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Annee_CIR__c</fullName>
        <label>Année CIR</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>MissionsCIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <recordTypes>
        <fullName>CIN</fullName>
        <active>true</active>
        <label>CIN</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <label>CIR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <fields>
        <fullName>Annee_concernee__c</fullName>
        <inlineHelpText>Années correspondantes à la mission</inlineHelpText>
        <label>Année concernée</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>Outros</fullName>
                </value>
                <value>
                    <fullName>FINEP</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <recordTypes>
        <fullName>CIN</fullName>
        <active>true</active>
        <description>Conseil en innovation</description>
        <label>CIN</label>
    </recordTypes>
    <recordTypes>
        <fullName>CIR</fullName>
        <active>true</active>
        <description>Mission CIR</description>
        <label>CIR</label>
    </recordTypes>
    <recordTypes>
        <fullName>FI</fullName>
        <active>true</active>
        <description>Mission AS</description>
        <label>AS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/ApexSharingRecalc_Mission.cls
/**
 * Utilisé en Queueable dans le trigger
 * mais on prévoit également le Batchable pour faire d'éventuels "Apex Sharing Recalculation"
 */
global class ApexSharingRecalc_Mission implements Database.Batchable<sObject>, Queueable{
	
	static final String INNOadvanceRowCause = Schema.Mission__Share.RowCause.INNO_Advance__c;
	
	
	private Set<Id> relatedContractIds;
	
	global ApexSharingRecalc_Mission(){}
	
	
	global ApexSharingRecalc_Mission(Set<Id> updatedMissionsINNOids){
		this.relatedContractIds = new Set<Id>();
		
		for(INNOmission__c m : [SELECT Id, Contrat__c FROM INNOmission__c WHERE Id IN :updatedMissionsINNOids])
			this.relatedContractIds.add(m.Contrat__c);
	}
	
	/**
	 * Pour le Batchable
	 */
		global Database.QueryLocator start(Database.BatchableContext BC){
			
			List<RecordType> rts = [SELECT Id FROM RecordType WHERE sObjectType = 'Mission__c' 
			                                                            AND (DeveloperName = 'CIR'
			                                                            OR DeveloperName = 'CIN'
			                                                            OR DeveloperName = 'FI')];
			Set<Id> rtIds = new Set<Id>();
			for(RecordType rt : rts){
			    rtIds.add(rt.Id);
			}                      
			
			if(this.relatedContractIds != null)
				return Database.getQueryLocator([SELECT Id, Contrat__c, Annee_concernee__c FROM Mission__c WHERE Contrat__c IN :this.relatedContractIds AND RecordTypeId IN :rtIds AND Annee_concernee__c != null]);
			else
				return Database.getQueryLocator([SELECT Id, Contrat__c, Annee_concernee__c FROM Mission__c WHERE RecordTypeId IN :rtIds AND Annee_concernee__c != null]);
		}
		
		global void execute(Database.BatchableContext BC, List<Mission__c> missions){
			this.recomputeSharing(missions);
		}
	
		global void finish(Database.BatchableContext BC){}
	
	
	
	/**
	 * Pour le Queueable
	 */
	 	global void execute(QueueableContext SC) {
			if(this.relatedContractIds != null)
				this.recomputeSharing([SELECT Id, Contrat__c, Annee_concernee__c FROM Mission__c WHERE Contrat__c IN :this.relatedContractIds]);
			else
				this.recomputeSharing([SELECT Id, Contrat__c, Annee_concernee__c FROM Mission__c]);
		}
	
	
	
	private void recomputeSharing(List<Mission__c> missions){
		
		system.debug('Start: BATCH ApexSharingRecalc_Mission');
		
		system.debug(missions.size() + ' missions Factu');
		
		/*
		*	Map avec:
		* 	Clé: ContractId-AnnéeConcernée
		*	Valeur: L'id de la mission Factu
		*/
		Map<String, Id> missionIdByContractIdAndYear = new Map<String, Id>();
		
		//L'ensemble des Ids de contrats concernés par le chunk de missions
		Set<Id> contratsIds = new Set<Id>();
		
		//Remplissage de missionIdByContractIdAndYear et de contratsIds
		for(Mission__c mission : missions){
			missionIdByContractIdAndYear.put(mission.Contrat__c + '-' + mission.Annee_concernee__c, mission.Id);
			contratsIds.add(mission.Contrat__c);
		}
		
		List<Mission__Share> newMissionShrs = new List<Mission__Share>();
		Id missionId;
		
		//Ajoute un Mission__Share pour chaque membre des équipes consultings
		for(INNOequipeConsulting__c eq : [SELECT Id, Utilisateur__c, Role__c, MissionCIR__r.Contrat__c, MissionCIR__r.Annee_CIR__c FROM INNOequipeConsulting__c WHERE MissionCIR__r.Contrat__c IN :contratsIds AND Utilisateur__r.IsActive = true AND Actif__c = true]){
			missionId = missionIdByContractIdAndYear.get(eq.MissionCIR__r.Contrat__c + '-' + eq.MissionCIR__r.Annee_CIR__c);
			
			if(missionId != null)
				newMissionShrs.add(new Mission__Share(ParentId = missionId, UserOrGroupId = eq.Utilisateur__c, AccessLevel = (eq.Role__c == 'Manager' ? 'Edit' : 'Read'), RowCause = INNOadvanceRowCause));
		}
		
		system.debug(newMissionShrs.size() + ' newMissionShrs');
		
		Database.delete([SELECT Id FROM Mission__Share WHERE ParentId IN :missions AND RowCause = :INNOadvanceRowCause], false);
		Database.insert(newMissionShrs, false);
		system.debug(newMissionShrs.size());
		system.debug('End: BATCH ApexSharingRecalc_Mission');
	}
		
}