gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Permet de rendre actif un utilisateur</description>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Audit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Audit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Controle__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Contrôle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Justification__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Justif</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Valorisation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Valo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Annee_CIR__c</fullName>
        <label>Année CIR</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>MissionsCIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_debut_Audit__c</fullName>
        <label>Date début Audit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_debut_justification__c</fullName>
        <label>Date début justification</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_debut_valorisation__c</fullName>
        <label>Date début valorisation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_audit__c</fullName>
        <label>Date fin Audit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_justification_recap__c</fullName>
        <inlineHelpText>Calculée automatiquement avec le MAX des Dates d&apos;échéance DT des valorisations associées</inlineHelpText>
        <label>Date fin justification</label>
        <summarizedField>INNOvalo__c.Date_echeance_DT__c</summarizedField>
        <summaryForeignKey>INNOvalo__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Date_fin_valorisation__c</fullName>
        <label>Date fin valorisation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Audit__c</fullName>
        <label>Nombre de jours théoriques - Audit</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Audit__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Controle__c</fullName>
        <label>Nombre de jours théoriques - Contrôle</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Controle__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Justification__c</fullName>
        <label>Nombre de jours théoriques - Justif</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Justification__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Valorisation__c</fullName>
        <label>Nombre de jours théoriques - Valo</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Valorisation__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactif / en attente de renouvellement</fullName>
                </value>
                <value>
                    <fullName>Inactif / en attente de lancement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Valorisation</fullName>
                </value>
                <value>
                    <fullName>Justification</fullName>
                </value>
                <value>
                    <fullName>Terminée</fullName>
                </value>
                <value>
                    <fullName>Terminée - Dossier à 0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>CASE( Phase__c , 
&apos;Inactif / en attente de renouvellement&apos;, &apos;Inactive&apos;, 
&apos;Inactif / en attente de lancement&apos;, &apos;Inactive&apos;, 
&apos;Terminée&apos;, IF(NombreCFenCours__c &gt; 0, &apos;Active&apos;, &apos;Terminée&apos;), 
&apos;Terminée - Dossier à 0&apos;, &apos;Terminée&apos;, 
&apos;Active&apos;)</formula>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <recordTypes>
        <fullName>AS</fullName>
        <active>true</active>
        <label>AS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOtimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duree__c</fullName>
        <description>La durée passé en jour (compris entre 0 et 1):
1 = toute la journée
0.5 = une demi-journée</description>
        <label>Durée</label>
        <precision>3</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission_CIR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>TimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passée</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Valorisation</fullName>
                </value>
                <value>
                    <fullName>Justification</fullName>
                </value>
                <value>
                    <fullName>Contrôle</fullName>
                </value>
                <value>
                    <fullName>Formation</fullName>
                </value>
                <value>
                    <fullName>Disponibilité</fullName>
                </value>
                <value>
                    <fullName>Avant-Vente / AO</fullName>
                </value>
                <value>
                    <fullName>AS/DI</fullName>
                </value>
                <value>
                    <fullName>CP / RTT</fullName>
                </value>
                <value>
                    <fullName>DUP</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>ASDI</fullName>
                    <isActive>false</isActive>
                    <label>ASDI</label>
                </value>
                <value>
                    <fullName>Administratif</fullName>
                    <isActive>false</isActive>
                    <label>Administratif</label>
                </value>
                <value>
                    <fullName>CP</fullName>
                    <isActive>false</isActive>
                    <label>CP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phase_technique__c</fullName>
        <formula>SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(TEXT(Phase__c), &apos;Avant-Vente / AO&apos;, &apos;AvantVenteAO&apos;), &apos;Disponibilité&apos;, &apos;Disponibilite&apos;), &apos;Contrôle&apos;, &apos;Controle&apos;), &apos;AS/DI&apos;, &apos;ASDI&apos;), &apos;CP / RTT&apos;, &apos;CP&apos;)</formula>
        <label>Phase technique</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theorique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Théorique</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>INNOtimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TimeSheet CIR</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>TimeSheets INNO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheets CIR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/classes/INNOtimeSheetCtrl.cls
global with sharing class INNOtimeSheetCtrl {

    private ApexPages.standardController stdCtrl;
    
    private String selectedMission = ApexPages.currentPage().getParameters().get('missionId');
    
    public INNOmission__c[] missions {get; set;}
    
    public transient Map<String, INNOtimeSheet__c> timeSheets {get;set;}
    public transient Map<String, Decimal> otherMissionsTimes {get; set;}
    
    public Date[] dates {get; set;}
    
    public Integer numeroSemaine {get; set;}
     
    public static final String[] PHASES_MISSION = new List<String>{'Audit', 'Valorisation', 'Justification', 'Controle'};
    public static final String[] PHASES_MISSION_NOT_CIR = new List<String>{'Audit'};
    public static final String[] PHASES_GENERAL = new List<String>{'AvantVenteAO', 'Formation', 'Administration', 'Disponibilite', 'CP', 'DUP'}; 
    
    public static final Map<String, String> PHASES_LABELS = new Map<String, String>{'Audit' 			=> 'Audit',
																					'Valorisation' 		=> 'Valorisation', 
																					'Justification'		=> 'Justification', 
																					'Controle'	 		=> 'Contrôle', 
																					'AvantVenteAO' 		=> 'Avant-Vente / AO', 
																					'Formation' 		=> 'Formation', 
																					'Administration'	=> 'Administration', 
																					'Disponibilite' 	=> 'Disponibilité', 
																					'ASDI' 				=> 'AS/DI', 
																					'CP' 				=> 'CP / RTT', 
																					'DUP' 				=> 'DUP'};
    
    public Boolean userHasFullAccess {get; set;}
    
    public Date startOfTodaysWeek {get; set;}
    
    public transient Map<String, Decimal> otherWeeksRealTimes {get; set;}
    public transient Map<String, Decimal> otherWeeksScheduledTimes {get; set;}
    
    public INNOtimeSheetCtrl(){
        
        this.stdCtrl = stdCtrl;
        
        this.userHasFullAccess = true;
        
        this.startOfTodaysWeek = System.today().toStartOfWeek();
        
        Boolean lastWeek = ApexPages.currentPage().getParameters().get('lastWeek') == '1';
        
        this.initWeek(system.today().toStartOfWeek().addDays(lastWeek ? -7 : 0));
        
        this.initTimeSheets();
    }
    
    /**
    *   Change la semaine de remplissage de la TimeSheet
    *   @PageReferenceParam (String way, 'lower' ou 'upper' pour monter ou descendre d'une semaine) OU (String day, une date au format yyyy-MM-dd la semaine à afficher)
    */
    public void changeWeek(){
        
        String way = ApexPages.currentPage().getParameters().get('way');
        
        //Si on a passer le parametre 'way' (lower ou upper)
        if(way != null){
            this.initWeek( this.dates[0].addDays( way == 'lower' ? -7 : 7 ) );
        }
        //Si on a passer directement un jour de l'année
        else{
            this.initWeek( date.valueOf( ApexPages.currentPage().getParameters().get('day') + ' 00:00:00' ).toStartOfWeek() );
        }
        
        
        this.initTimeSheets();
    }
    
    
        
    public List<String> getPhasesMission(){
        return PHASES_MISSION;
    }
    
    public List<String> getPhasesGeneral(){
        return PHASES_GENERAL;
    }
    
    
    
    
    
    
    
    
    
    
    private void initWeek(Date lundi){
        
        /*
        *   Initialisation des jours de la semaine
        */
        
        this.dates = new List<Date>();
        for(Integer i = 0; i < 5; i++)
            this.dates.add(lundi.addDays(i));

        this.numeroSemaine = Integer.valueOf(DateTime.newInstance( lundi, Time.newInstance(12,0,0,0) ).format('w'));
        
        
    }
    
    

    
    
    private void initTimeSheets(){
        
        this.missions = new List<INNOmission__c>();
        Set<Id> missionsIds = new Set<Id>();
        Set<Id> missionsIdsMatchingFilters = new Set<Id>{null};
        this.otherWeeksRealTimes = new Map<String, Decimal>();
        this.otherWeeksScheduledTimes = new Map<String, Decimal>();

        for(INNOmission__c mission : [SELECT Id, Name, RecordType.DeveloperName, Annee_CIR__c, Contrat__r.AccountId, Date_debut_Audit__c, Date_debut_valorisation__c, Date_debut_justification__c, Date_fin_audit__c, Date_fin_valorisation__c, Date_fin_justification_recap__c, (SELECT Id, Actif__c, Nombre_jours_theoriques_Audit__c, Nombre_jours_theoriques_Valorisation__c, Nombre_jours_theoriques_Justification__c, Nombre_jours_theoriques_Controle__c FROM EquipesConsulting__r WHERE Utilisateur__c = :UserInfo.getUserId()) FROM INNOmission__c WHERE Statut__c = 'Active' ORDER BY Annee_CIR__c, Name]){
            if(!mission.EquipesConsulting__r.isEmpty() && mission.EquipesConsulting__r[0].Actif__c){
	            missionsIds.add(mission.Id);
	            
	            if(this.selectedMission == mission.Id || this.selectedMission == null){
	                
	                this.missions.add(mission); 
	                missionsIdsMatchingFilters.add(mission.Id);
	                
	                for(String phase : PHASES_MISSION){
	                    this.otherWeeksRealTimes.put(mission.Id + '_' + phase, 0);
	                    this.otherWeeksScheduledTimes.put(mission.Id + '_' + phase, 0);
	                }
	            } 
            }
                    
        }
        
        //Initialisation de this.otherMissionsTimes avec les jours de la semaine
        this.otherMissionsTimes = new Map<String, Decimal>();
        for(Date d : this.dates)
            this.otherMissionsTimes.put(String.valueOf(d), 0);
            
            
        //L'id le l'utilisateur
        Id userId = UserInfo.getUserId();
        
        this.timeSheets = new Map<String, INNOtimeSheet__c>();
        
        for(INNOtimeSheet__c TSs : [SELECT Id, Mission_CIR__c, Date__c, Phase__c, Phase_technique__c, Duree__c, Theorique__c FROM INNOtimeSheet__c WHERE Utilisateur__c = :userId AND Date__c >= :this.dates[0] AND Date__c <= :this.dates[4]]){
            
            //Si la TS rentre dans les critères des filtres
            if(missionsIdsMatchingFilters.contains(TSs.Mission_CIR__c))
                this.timeSheets.put( (TSs.Mission_CIR__c == null ? 'general' : TSs.Mission_CIR__c) + '_' + String.valueOf(TSs.Date__c) + '_' + TSs.Phase_technique__c, TSs);
            else
                this.otherMissionsTimes.put(String.valueOf(TSs.Date__c), this.otherMissionsTimes.get(String.valueOf(TSs.Date__c)) + TSs.Duree__c);
        }
        
    
        for(AggregateResult aggr : [SELECT SUM(Duree__c) duree, Mission_CIR__c, Phase__c, Passee__c FROM INNOtimeSheet__c WHERE Mission_CIR__c IN :missionsIdsMatchingFilters AND Utilisateur__c = :UserInfo.getUserId() AND Date__c NOT IN :this.dates GROUP BY Mission_CIR__c, Phase__c, Passee__c]){
        	
        	if((Boolean) aggr.get('Passee__c'))
            	this.otherWeeksRealTimes.put(aggr.get('Mission_CIR__c') + '_' + String.valueOf(aggr.get('Phase__c')).replace('Contrôle', 'Controle'), (Decimal) aggr.get('duree'));
            else
            	this.otherWeeksScheduledTimes.put(aggr.get('Mission_CIR__c') + '_' + String.valueOf(aggr.get('Phase__c')).replace('Contrôle', 'Controle'), (Decimal) aggr.get('duree'));
        }
        
       
      
        
    }
    
    
    public PageReference validateWeek(){
    	
    	Date firstDayOfWeekToValidate = Date.parse(ApexPages.CurrentPage().getParameters().get('firstDayOfWeekToValidate'));

	
        List<INNOtimeSheet__c> tsList = [SELECT Id, Theorique__c FROM INNOtimeSheet__c WHERE Utilisateur__c = :Userinfo.getUserId() AND Theorique__c = true AND Date__c >= :firstDayOfWeekToValidate AND Date__c <= :firstDayOfWeekToValidate.addDays(4) AND (Mission_CIR__c IN :this.missions OR Mission_CIR__c = null)];
        
        for(INNOtimeSheet__c ts : tsList){
            ts.Theorique__c = false;
        }
        
        update tsList;
        
        PageReference retPage = Page.INNOtimeSheetEdit;
        retPage.setRedirect(true);
        
        if(String.isNotBlank(this.selectedMission))
            retPage.getParameters().put('missionId', this.selectedMission);
            
        return retPage;
    }
    
    
    @RemoteAction
	public static Boolean saveTimeSheet(String missionId, String tsDate, String phase, String dureeStr){
		
        return INNOtimeSheet.saveTimeSheet(missionId, tsDate, phase, dureeStr, null);
	}
}