gac_sb/objects/INNOamortissement__c.object
<CustomObject>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Amortissements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Methode_de_calcul__c</fullName>
        <description>Sert à définir la méthode de calcul du taux R&amp;D</description>
        <label>Méthode de calcul du taux R&amp;D</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manuelle</fullName>
                    <default>true</default>
                    <label>Manuelle</label>
                </value>
                <value>
                    <fullName>Moyenne des sommes</fullName>
                </value>
                <value>
                    <fullName>Somme des moyennes</fullName>
                </value>
                <value>
                    <fullName>Moyenne des sommes du département</fullName>
                </value>
                <value>
                    <fullName>Somme des moyennes du département</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Taux_RD_option1__c</fullName>
        <label>Taux R&amp;D option 1</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Taux_RD_option2__c</fullName>
        <label>Taux R&amp;D option 2</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Taux_RD_option3__c</fullName>
        <label>Taux R&amp;D option 3</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Amortissements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Amortissement</label>
    <nameField>
        <label>Désignation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amortissements</pluralLabel>
    <recordTypes>
        <fullName>amortissement</fullName>
        <active>true</active>
        <label>Dotations aux amortissements</label>
    </recordTypes>
    <recordTypes>
        <fullName>amortissementBrevet</fullName>
        <active>true</active>
        <label>Dotations aux amortissements de brevets</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOamortissementCtrl.cls
public with sharing class INNOamortissementCtrl extends INNOmissionBaseCtrl{

	private ApexPages.standardController stdCtrl;
	
	
	public String tab {get; set;}
	
	public INNOamortissementUtils tauxRDcls {get; set;}
	public String selectedDepartement {get; set;}
	
	
	public INNOamortissementCtrl(ApexPages.standardController stdCtrl){
		this.stdCtrl = stdCtrl;
		
		this.tab = ApexPages.currentPage().getParameters().get('tab');

		if(this.tab == null)
			this.tab = 'amortissement';
		
		
		INNOamortissement__c dotation = (INNOamortissement__c) this.stdCtrl.getRecord();
		
		Id entiteId;
		
		if( ApexPages.currentPage().getUrl().startsWith('/apex/INNOamortissementEdit') ){
				
			//Si c'est une NOUVELLE depense de personnel
			if( dotation.Id == null){
				dotation.Valorisation__c = this.valoId;
				dotation.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'INNOamortissement__c' AND DeveloperName = :this.tab LIMIT 1][0].Id;
				dotation.Methode_de_calcul__c = 'Manuelle';
				
				if(this.tab == 'amortissementBrevet')
					dotation.Taux_RD_option1__c = dotation.Taux_RD_option2__c = dotation.Taux_RD_option3__c = 100;  
			}
			
			this.initDepartements();
			this.initProjets();

			this.tauxRDcls = new INNOamortissementUtils(this.valoId);
			this.selectedDepartement = dotation.Departement__c;
			
		}

	}
	
	
	
	public PageReference save(){
	
	
		this.stdCtrl.save();
		
		PageReference retPage;
		
		retPage = new PageReference('/apex/INNOamortissementView');
		retPage.getParameters().put('id', this.stdCtrl.getId());
		retPage.getParameters().put('valoId', this.valoId);
		retPage.getParameters().put('tab', this.tab);
			
		retPage.setRedirect(true);
		
		return retPage;
	}
	
	
	/**
	*	Supprime une dotation aux amortissements et redirige vers la page de liste dotations
	*/
	public PageReference deleteAndRedirect(){
		Database.delete(this.stdCtrl.getId());

		PageReference retPage = new pageReference( '/apex/INNOamortissementList' );
		retPage.getParameters().put('valoId', this.valoId);
		retPage.getParameters().put('tab', this.tab);
		retPage.setRedirect(true);
		return retPage; 
	}
	
	
	
}