gac_sb/objects/INNOdepartement__c.object
<CustomObject>
    <label>Département</label>
    <nameField>
        <label>Département</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Départements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOprojet__c.object
<CustomObject>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nom_regroupement_projet__c</fullName>
        <description>Si le projet est inclus dans un ensemble de projets, on saisi le nom de cet ensemble</description>
        <inlineHelpText>Si le projet est inclus dans un ensemble de projets, précisez le nom de cet ensemble.</inlineHelpText>
        <label>Nom du regroupement de projet</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Num_projet__c</fullName>
        <label>N° de projet</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Champ invisible pour l&apos;utilisateur, permet de savoir si l&apos;enregistrement est un &quot;vrai&quot; projet ou si c&apos;est un enregistrement qui est la juste pour rattacher des dépenses de personnel aux veilles, PM de brevet ou normalisation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>projet</fullName>
                    <default>true</default>
                    <label>projet</label>
                </value>
                <value>
                    <fullName>veille</fullName>
                </value>
                <value>
                    <fullName>brevetPM</fullName>
                </value>
                <value>
                    <fullName>normalisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOprojetListCtrl.cls
public with sharing class INNOprojetListCtrl extends INNOmissionBaseCtrl{

	
	public List<INNOprojet__c> projets {get; set;}
	
	
	public INNOprojetListCtrl(ApexPages.StandardController stdCtrl){
		
		
		this.projets = [SELECT Id, 
								Name, 
								Departement__c, 
								Departement__r.Name, 
								Num_projet__c, 
								Nom_regroupement_projet__c 
							FROM INNOprojet__c 
							WHERE Valorisation__c = :this.valo.Id 
								AND Type__c = 'projet'];
		
	}
	
	
	
	
}