gac_sb/objects/INNOdepartement__c.object
<CustomObject>
    <fields>
        <fullName>Entite__c</fullName>
        <label>Entité</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DepartementsCIR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Département</label>
    <nameField>
        <label>Département</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Départements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOdepensePersonnel__c.object
<CustomObject>
    <fields>
        <fullName>CleUnique__c</fullName>
        <formula>Nom__c+Prenom__c+Matricule__c+RecordType.DeveloperName</formula>
        <label>Clé unique</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Depenses_de_personnel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ImportId__c</fullName>
        <label>Id d&apos;import</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Matricule__c</fullName>
        <label>Matricule</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Depenses_de_personnel</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dépense de personnel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses de personnel</pluralLabel>
    <recordTypes>
        <fullName>salarie</fullName>
        <active>true</active>
        <label>Salariés</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOprojet__c.object
<CustomObject>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ImportId__c</fullName>
        <label>Id d&apos;import</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Champ invisible pour l&apos;utilisateur, permet de savoir si l&apos;enregistrement est un &quot;vrai&quot; projet ou si c&apos;est un enregistrement qui est la juste pour rattacher des dépenses de personnel aux veilles, PM de brevet ou normalisation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>projet</fullName>
                    <default>true</default>
                    <label>projet</label>
                </value>
                <value>
                    <fullName>veille</fullName>
                </value>
                <value>
                    <fullName>brevetPM</fullName>
                </value>
                <value>
                    <fullName>normalisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOsubvention__c.object
<CustomObject>
    <fields>
        <fullName>CleUnique__c</fullName>
        <formula>CASESAFEID(RecordType.Id) + Matricule__c</formula>
        <label>Clé unique</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_versement__c</fullName>
        <label>Date de versement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Subventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ImportId__c</fullName>
        <label>Id d&apos;import</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Matricule__c</fullName>
        <label>Matricule</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Montant_option1__c</fullName>
        <label>Montant option 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_option2__c</fullName>
        <label>Montant option 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_option3__c</fullName>
        <label>Montant option 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nature__c</fullName>
        <label>Nature</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Organisme__c</fullName>
        <label>Organisme</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projet</label>
        <referenceTo>INNOprojet__c</referenceTo>
        <relationshipName>Subventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salarie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Uniquement pour les subventions, à choisir parmi les salariés de la mission</description>
        <label>Salarié</label>
        <referenceTo>INNOdepensePersonnel__c</referenceTo>
        <relationshipName>Subventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Subventions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subvention et avance</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subventions et avances</pluralLabel>
    <recordTypes>
        <fullName>avanceRemboursable</fullName>
        <active>true</active>
        <label>Avances remboursables</label>
    </recordTypes>
    <recordTypes>
        <fullName>remboursementAvance</fullName>
        <active>true</active>
        <label>Remboursements d&apos;avances</label>
    </recordTypes>
    <recordTypes>
        <fullName>subvention</fullName>
        <active>true</active>
        <label>Subventions</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOvalo__c.object
<CustomObject>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entité</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Valorisations (Entité)</relationshipLabel>
        <relationshipName>Valorisations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Valorisation</label>
    <nameField>
        <label>Nom de la valorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valorisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOimport_subventionAvance.cls
public with sharing class INNOimport_subventionAvance extends INNOimport{

	private Id valoId;
	
	
	public override void init(Id valoId){
		
		this.valoId = valoId;
		
		this.existingRecordsWhereClause = 'WHERE Valorisation__c = \'' + this.valoId + '\' AND Matricule__c != null';
		
		this.importTypeName = 'Subventions et avances';
		
		List<INNOvalo__c> valos = [SELECT Id, Name, Entite__c FROM INNOvalo__c WHERE Id = :this.valoId LIMIT 1];
		
		this.pageTitle = valos[0].Name;
				
		this.excelFileName = 'INNO-Imports_subventions_avances.xlsx';

		this.sObjectDescribe = INNOsubvention__c.SObjectType;
		
		this.standardColumns = new List<Map<String, String>>{ 
															new Map<String, String>{'Name'=>'Organisme*', 'FieldName'=>'Organisme__c', 'Required'=>'true', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Type* (Subvention, Avance perçue, Avance remboursée)', 'FieldName'=>'RecordTypeId', 'Required'=>'true', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'Matricule', 'FieldName'=>'Matricule__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Date de versement', 'FieldName'=>'Date_versement__c', 'Required'=>'false', 'Type'=>'Date'},
															new Map<String, String>{'Name'=>'Nature', 'FieldName'=>'Nature__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Salarié', 'FieldName'=>'Salarie__c', 'Required'=>'false', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'Département', 'FieldName'=>'Departement__c', 'Required'=>'false', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'Projet', 'FieldName'=>'Projet__c', 'Required'=>'false', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'Montant opt1', 'FieldName'=>'Montant_option1__c', 'Required'=>'false', 'Type'=>'Currency'},
															new Map<String, String>{'Name'=>'Montant opt2', 'FieldName'=>'Montant_option2__c', 'Required'=>'false', 'Type'=>'Currency'},
															new Map<String, String>{'Name'=>'Montant opt3', 'FieldName'=>'Montant_option3__c', 'Required'=>'false', 'Type'=>'Currency'},
															new Map<String, String>{'Name'=>'Commentaires', 'FieldName'=>'Commentaires__c', 'Required'=>'false', 'Type'=>'String'}
															};
															
		this.upsertKeyFieldName = 'CleUnique__c';
	
		this.importIdField = 'ImportId__c';
		
		this.retPage = new pageReference( '/apex/INNOsubventionList' );
		this.retPage.getParameters().put('id', this.valoId);
		this.retPage.getParameters().put('valoId', this.valoId);
		this.retPage.getParameters().put('tab', 'subvention');
		
		
		Map<String, Id> recordTypes = new Map<String, Id>();
		for(RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'INNOsubvention__c' ])
			recordTypes.put(rt.DeveloperName, rt.Id);
			
		
		/*
		*   Initialisation des départements possibles du champ 'Type'
		*/
		List<SelectOption> types = new List<SelectOption>{
															new SelectOption( recordTypes.get('subvention'), 'Subvention'),
															new SelectOption( recordTypes.get('avanceRemboursable'), 'Avance perçue'),
															new SelectOption( recordTypes.get('remboursementAvance'), 'Avance remboursée')
														};
		
		this.picklistValues.put('RecordTypeId', types);	
		
		
	   
		/*
		*   Initialisation des départements possibles du champ 'Salarié'
		*/
		List<SelectOption> salaries = new List<SelectOption>{new SelectOption('', '- Aucun -')};
		for(INNOdepensePersonnel__c salarie : [SELECT Id, Name FROM INNOdepensePersonnel__c WHERE Valorisation__c = :this.valoId ORDER BY Name]){
			salaries.add( new SelectOption(salarie.Id, salarie.Name) );
		}
		
		this.picklistValues.put('Salarie__c', salaries);
		
		
		/*
		*   Initialisation des départements possibles du champ 'Departement'
		*/
		List<SelectOption> departements = new List<SelectOption>{new SelectOption('', '-Aucun-')};
		
		if(valos.size() > 0){
			for(INNOdepartement__c dept : [SELECT Id, Name FROM INNOdepartement__c WHERE Entite__c = :valos[0].Entite__c ORDER BY Name])
			    departements.add(new SelectOption(dept.Id, dept.Name));
		}
		
		this.picklistValues.put('Departement__c', departements);	
	
	
		/*
		*   Initialisation des projets possibles du champ 'Projet'
		*/
		List<SelectOption> projets = new List<SelectOption>{new SelectOption('', '-Aucun-')};
		
		for(INNOprojet__c projet : [SELECT Id, Name FROM INNOprojet__c WHERE Valorisation__c = :this.valoId AND Type__c = 'projet' ORDER BY Name])
			projets.add(new SelectOption(projet.Id, projet.Name));
			
		this.picklistValues.put('Projet__c', projets);
		
		
	}



	
	protected override String getRowUpsertKeyValue(INNOimport.ImportRow row){
		return row.cells[1].value + row.cells[2].value;
	}
	
	

	
	protected override sObject getRecord(ImportRow row){
		sObject record = new INNOsubvention__c(Id = row.existingRecordId, Valorisation__c = this.valoId);
		
		for(INNOimport.ImportCell cell : row.cells){
			
			if(cell.datatype == 'Number')
				record.put(cell.fieldName, Decimal.valueOf(cell.value));
			else if(cell.datatype == 'Boolean')
				record.put(cell.fieldName, cell.value == 'oui' ? true : false);
			else if(cell.datatype == 'Date')
				record.put(cell.fieldName, cell.value == null ? null : Date.parse(cell.value));
			else
				record.put(cell.fieldName, cell.value);
				
		}
		
		return record;
	}
	
	
	
	
	
}