gac_sb/objects/INNOdepartement__c.object
<CustomObject>
    <fields>
        <fullName>Entite__c</fullName>
        <label>Entité</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DepartementsCIR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Département</label>
    <nameField>
        <label>Département</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Départements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOdepensePrestation__c.object
<CustomObject>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_debut_agrement__c</fullName>
        <label>Date début d&apos;agrément</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_agrement__c</fullName>
        <label>Date fin d&apos;agrément</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_piece__c</fullName>
        <label>Date pièce</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>DepensesPrestation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ImportId__c</fullName>
        <label>Id d&apos;import</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lien_de_dependance__c</fullName>
        <label>Lien de dépendance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Avec</fullName>
                </value>
                <value>
                    <fullName>Sans</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Localisation__c</fullName>
        <label>Localisation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>En France</fullName>
                </value>
                <value>
                    <fullName>A l&apos;étranger</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Montant_HT__c</fullName>
        <label>Montant HT</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nature_prestation__c</fullName>
        <label>Nature prestation</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Num_piece__c</fullName>
        <label>N° pièce</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Precisez_pays__c</fullName>
        <inlineHelpText>Précisez le pays si l&apos;organisme est basé à l&apos;étranger</inlineHelpText>
        <label>Précisez pays</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prestataire__c</fullName>
        <label>Prestataire</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projet</label>
        <referenceTo>INNOprojet__c</referenceTo>
        <relationshipName>DepensesPrestation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIREN__c</fullName>
        <label>SIREN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taux_option1__c</fullName>
        <label>Taux option 1</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Taux_option2__c</fullName>
        <label>Taux option 2</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Taux_option3__c</fullName>
        <label>Taux option 3</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type_organisme__c</fullName>
        <label>Type d&apos;organisme</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Agréé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Depenses_de_prestation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dépense de prestation</label>
    <nameField>
        <label>Prestation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses de prestation</pluralLabel>
    <recordTypes>
        <fullName>prestataire</fullName>
        <active>true</active>
        <label>Prestataires</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOprojet__c.object
<CustomObject>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ImportId__c</fullName>
        <label>Id d&apos;import</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Champ invisible pour l&apos;utilisateur, permet de savoir si l&apos;enregistrement est un &quot;vrai&quot; projet ou si c&apos;est un enregistrement qui est la juste pour rattacher des dépenses de personnel aux veilles, PM de brevet ou normalisation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>projet</fullName>
                    <default>true</default>
                    <label>projet</label>
                </value>
                <value>
                    <fullName>veille</fullName>
                </value>
                <value>
                    <fullName>brevetPM</fullName>
                </value>
                <value>
                    <fullName>normalisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOvalo__c.object
<CustomObject>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_debut_agrement__c</fullName>
        <label>Date de début d&apos;agrément</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_agrement__c</fullName>
        <label>Date de fin d&apos;agrément</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entité</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Valorisations (Entité)</relationshipLabel>
        <relationshipName>Valorisations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Valorisation</label>
    <nameField>
        <label>Nom de la valorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valorisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOimport_prestataire.cls
public with sharing class INNOimport_prestataire extends INNOimport{

	private Id valoId;
	
	private String recordTypeId;
	

	public INNOimport_prestataire(){}
	
	
	public override void init(Id valoId){
		
		this.valoId = valoId;
		
		this.recordTypeId = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'INNOdepensePrestation__c' AND DeveloperName = 'prestataire' LIMIT 1][0].Id;
		
		this.existingRecordsWhereClause = 'WHERE Valorisation__c = \'' + this.valoId + '\' AND RecordTypeId = \'' + this.recordTypeId + '\'';
		
		this.importTypeName = 'Prestataires';
		
		List<INNOvalo__c> valos = [SELECT Id, Name, Entite__c FROM INNOvalo__c WHERE Id = :this.valoId LIMIT 1];
		
		if(valos.size() > 0)
			this.pageTitle = valos[0].Name;
				
		this.excelFileName = 'INNO-Imports_prestataires.xlsx';

		this.sObjectDescribe = INNOdepensePrestation__c.SObjectType;
		
		this.standardColumns = new List<Map<String, String>>{ 
															new Map<String, String>{'Name'=>'Prestataire*', 'FieldName'=>'Prestataire__c', 'Required'=>'true', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Nature prestation', 'FieldName'=>'Nature_prestation__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'SIREN', 'FieldName'=>'SIREN__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Date début d\'agrément', 'FieldName'=>'Date_debut_agrement__c', 'Required'=>'false', 'Type'=>'Date'},
															new Map<String, String>{'Name'=>'Date fin d\'agrément', 'FieldName'=>'Date_fin_agrement__c', 'Required'=>'false', 'Type'=>'Date'},
															new Map<String, String>{'Name'=>'Type d\'organisme* (Public/Agréé)', 'FieldName'=>'Type_organisme__c', 'Required'=>'true', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'Lien de dépendance* (Avec/Sans)', 'FieldName'=>'Lien_de_dependance__c', 'Required'=>'true', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'Localisation* (En France/A l\'étranger)', 'FieldName'=>'Localisation__c', 'Required'=>'true', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'Précisez pays (si localisation à l\'étranger)', 'FieldName'=>'Precisez_pays__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Département', 'FieldName'=>'Departement__c', 'Required'=>'false', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'Projet', 'FieldName'=>'Projet__c', 'Required'=>'false', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'N° pièce*', 'FieldName'=>'Num_piece__c', 'Required'=>'true', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Date pièce', 'FieldName'=>'Date_piece__c', 'Required'=>'false', 'Type'=>'Date'},
															new Map<String, String>{'Name'=>'Montant HT*', 'FieldName'=>'Montant_HT__c', 'Required'=>'true', 'Type'=>'Currency'},
															new Map<String, String>{'Name'=>'Taux R&D opt1', 'FieldName'=>'Taux_option1__c', 'Required'=>'false', 'Type'=>'Percent'},
															new Map<String, String>{'Name'=>'Taux R&D opt2', 'FieldName'=>'Taux_option2__c', 'Required'=>'false', 'Type'=>'Percent'},
															new Map<String, String>{'Name'=>'Taux R&D opt3', 'FieldName'=>'Taux_option3__c', 'Required'=>'false', 'Type'=>'Percent'},
															new Map<String, String>{'Name'=>'Commentaires', 'FieldName'=>'Commentaires__c', 'Required'=>'false', 'Type'=>'String'}
															};
															
		this.upsertKeyFieldName = 'Num_piece__c';
		
		this.importIdField = 'ImportId__c';
		
		this.retPage = new pageReference( '/apex/INNOdepensePrestationList' );
		this.retPage.getParameters().put('id', this.valoId);
		this.retPage.getParameters().put('valoId', this.valoId);
		this.retPage.getParameters().put('tab', 'prestataire');
		
		
		
		/*
		*	Initialisation des départements possibles du champ 'Departement'
		*/
		List<SelectOption> departements = new List<SelectOption>{new SelectOption('', '-Aucun-')};
		
		for(INNOdepartement__c dept : [SELECT Id, Name FROM INNOdepartement__c WHERE Entite__c = :valos[0].Entite__c ORDER BY Name])
			departements.add(new SelectOption(dept.Id, dept.Name));
			
		this.picklistValues.put('Departement__c', departements);	
	
	
		/*
		*	Initialisation des projets possibles du champ 'Projet'
		*/
		List<SelectOption> projets = new List<SelectOption>{new SelectOption('', '-Aucun-')};
		
		for(INNOprojet__c projet : [SELECT Id, Name FROM INNOprojet__c WHERE Valorisation__c = :this.valoId AND Type__c = 'projet' ORDER BY Name])
			projets.add(new SelectOption(projet.Id, projet.Name));
			
		this.picklistValues.put('Projet__c', projets);
		
		
	}


	protected override String getRowUpsertKeyValue(INNOimport.ImportRow row){
		return row.cells[11].value;
	}
	
	

	
	protected override sObject getRecord(ImportRow row){
		sObject record = new INNOdepensePrestation__c(Id = row.existingRecordId, Valorisation__c = this.valoId, RecordTypeId = this.recordTypeId);
		
		for(INNOimport.ImportCell cell : row.cells){
			
			if(cell.datatype == 'Number')
				record.put(cell.fieldName, Decimal.valueOf(cell.value));
			else if(cell.datatype == 'Boolean')
				record.put(cell.fieldName, cell.value == 'oui' ? true : false);
			else if(cell.datatype == 'Date')
				record.put(cell.fieldName, cell.value == null ? null : Date.parse(cell.value));
			else
				record.put(cell.fieldName, cell.value);
				
		}
		
		return record;
	}
	
	
	
	
	
}