gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Date_fin_audit__c</fullName>
        <label>Date fin Audit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_valorisation__c</fullName>
        <label>Date fin valorisation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Montant_CIR_definitif_option1__c</fullName>
        <inlineHelpText>Somme des montants des valorisations associées à cette mission</inlineHelpText>
        <label>Montant du CIR définitif option 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_CIR_definitif_option2__c</fullName>
        <inlineHelpText>Somme des montants des valorisations associées à cette mission</inlineHelpText>
        <label>Montant du CIR définitif option 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_CIR_definitif_option3__c</fullName>
        <inlineHelpText>Somme des montants des valorisations associées à cette mission</inlineHelpText>
        <label>Montant du CIR définitif option 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_CIR_definitif_optionFinale__c</fullName>
        <inlineHelpText>Somme des montants des valorisations associées à cette mission</inlineHelpText>
        <label>Montant CIR définitif retenu(après dédu)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_total_depenses_option1__c</fullName>
        <inlineHelpText>Somme des montants des valorisations associées à cette mission</inlineHelpText>
        <label>Montant total des dépenses option 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_total_depenses_option2__c</fullName>
        <inlineHelpText>Somme des montants des valorisations associées à cette mission</inlineHelpText>
        <label>Montant total des dépenses option 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_total_depenses_option3__c</fullName>
        <inlineHelpText>Somme des montants des valorisations associées à cette mission</inlineHelpText>
        <label>Montant total des dépenses option 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_total_depenses_optionFinale__c</fullName>
        <inlineHelpText>Somme des montants des valorisations associées à cette mission</inlineHelpText>
        <label>Montant total dép. retenu (avant dédu)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOvalo__c.object
<CustomObject>
    <fields>
        <fullName>Date_envoi_valorisation__c</fullName>
        <label>Date d&apos;envoi valorisation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_validation_perimetre__c</fullName>
        <label>Date de validation de périmètre</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipLabel>Valorisations</relationshipLabel>
        <relationshipName>Valorisations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Montant_CIR_definitif_option1__c</fullName>
        <formula>Montant_total_dep_apres_dedu_option1__c * IF(RecordType.DeveloperName = &apos;CIR&apos;, MissionCIR__r.Taux_CIR__c, MissionCIR__r.TauxCII__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant du CIR définitif option 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_CIR_definitif_option2__c</fullName>
        <formula>Montant_total_dep_apres_dedu_option2__c * IF(RecordType.DeveloperName = &apos;CIR&apos;, MissionCIR__r.Taux_CIR__c, MissionCIR__r.TauxCII__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant du CIR définitif option 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_CIR_definitif_option3__c</fullName>
        <formula>Montant_total_dep_apres_dedu_option3__c * IF(RecordType.DeveloperName = &apos;CIR&apos;, MissionCIR__r.Taux_CIR__c, MissionCIR__r.TauxCII__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant du CIR définitif option 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_CIR_definitif_optionFinale__c</fullName>
        <formula>Montant_total_dep_apres_dedu_optionFinal__c * IF(RecordType.DeveloperName = &apos;CIR&apos;, MissionCIR__r.Taux_CIR__c, MissionCIR__r.TauxCII__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant CIR définitif retenu(après dédu)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_total_depenses_option1__c</fullName>
        <formula>Total_salarie_option1__c + 
Total_miseDisposition_option1__c +
Total_jeuneDocteur_option1__c +
Total_amortissement_option1__c +
Total_frais_fonctionnement_option1__c +
Total_brevetPM_option1__c +
Total_brevetDef_option1__c +
Total_amortissementBrevet_option1__c +
Total_brevetAssu_option1__c +
Total_normalisation_option1__c +
Total_veille_option1__c +
Total_prestataire_option1__c +
Total_remboursementAvance_option1__c -
Total_subvention_option1__c -
Total_avanceRemboursable_option1__c -
Honoraires_N1_a_deduire_option1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant total des dépenses option 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_total_depenses_option2__c</fullName>
        <formula>Total_salarie_option2__c + 
Total_miseDisposition_option2__c +
Total_jeuneDocteur_option2__c +
Total_amortissement_option2__c +
Total_frais_fonctionnement_option2__c +
Total_brevetPM_option2__c +
Total_brevetDef_option2__c +
Total_amortissementBrevet_option2__c +
Total_brevetAssu_option2__c +
Total_normalisation_option2__c +
Total_veille_option2__c +
Total_prestataire_option2__c +
Total_remboursementAvance_option2__c -
Total_subvention_option2__c -
Total_avanceRemboursable_option2__c -
Honoraires_N1_a_deduire_option2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant total des dépenses option 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_total_depenses_option3__c</fullName>
        <formula>Total_salarie_option3__c + 
Total_miseDisposition_option3__c +
Total_jeuneDocteur_option3__c +
Total_amortissement_option3__c +
Total_frais_fonctionnement_option3__c +
Total_brevetPM_option3__c +
Total_brevetDef_option3__c +
Total_amortissementBrevet_option3__c +
Total_brevetAssu_option3__c +
Total_normalisation_option3__c +
Total_veille_option3__c +
Total_prestataire_option3__c +
Total_remboursementAvance_option3__c -
Total_subvention_option3__c -
Total_avanceRemboursable_option3__c -
Honoraires_N1_a_deduire_option3__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant total des dépenses option 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_total_depenses_optionFinale__c</fullName>
        <formula>Total_salarie_optionFinale__c + 
Total_miseDisposition_optionFinale__c + 
Total_jeuneDocteur_optionFinale__c + 
Total_amortissement_optionFinale__c + 
Total_frais_fonctionnement_optionFinale__c + 
Total_brevetPM_optionFinale__c + 
Total_brevetDef_optionFinale__c + 
Total_amortissementBrevet_optionFinale__c + 
Total_brevetAssu_optionFinale__c + 
Total_normalisation_optionFinale__c + 
Total_veille_optionFinale__c + 
Total_prestataire_optionFinale__c + 
Total_remboursementAvance_optionFinale__c - 
Total_subvention_optionFinale__c - 
Total_avanceRemboursable_optionFinale__c - 
Honoraires_N1_a_deduire_optionFinale__c</formula>
        <label>Montant total dép. retenu (avant dédu)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ValoA0__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valo à 0</label>
        <type>Checkbox</type>
    </fields>
    <label>Valorisation</label>
    <nameField>
        <label>Nom de la valorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valorisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOvalorisationHandler.cls
/**
 * Class INNOvalorisationHandler
 *
 * Trigger Handler for the INNOvalo__c	 SObject. This class implements the ITrigger
 * interface to help ensure the trigger code is bulkified and all in one place.
 */

public with sharing class INNOvalorisationHandler implements ITrigger {
	
	//Contiendra tous les Id des missions dans lesquelles il faudra mettre à jour les faux rollups
	private Set<Id> missionsIdsToUpdateRollups = new Set<Id>();
	
	private List<INNOmission__c> missionsToUpdate = new List<INNOmission__c>();
	private Map<Id, INNOmission__c> missionsToUpsert = new Map<Id, INNOmission__c>();
	
	private Set<Id> tempMissionsToUpsert = new Set<Id>();
	private Set<Id> missionsValoDeleted = new Set<Id>();
	// Constructor
	public INNOvalorisationHandler(){
	}

	public void bulkBefore(){
	}
	
	public void bulkAfter(){
	    //EDIT Aurélien CLERC 13/06/2017
	    if(!Trigger.isDelete){
	        for(INNOvalo__c valo : (List<INNOvalo__c>)[SELECT Id, MissionCIR__c FROM INNOvalo__c WHERE Id IN :Trigger.New AND (Date_validation_perimetre__c != null OR Date_envoi_valorisation__c != null)]){
	            this.tempMissionsToUpsert.add(valo.MissionCIR__c);
	        }
	    }
	}
		
	public void beforeInsert(SObject so){
	}
	
	public void beforeUpdate(SObject oldSo, SObject so){
	}
	
	public void beforeDelete(SObject so){	
	}
	
	public void afterInsert(SObject so){
	    //EDIT Aurélien CLERC 15/06/2017
	    INNOvalo__c valo = (INNOvalo__c) so;
	   
	    if(valo.Date_envoi_valorisation__c == null || valo.Date_validation_perimetre__c == null){
	        if(valo.Date_envoi_valorisation__c == null)
	            missionsToUpsert.put(valo.MissionCIR__c, new INNOmission__c(Id                          = valo.MissionCIR__c,
		                                                                    Date_fin_valorisation__c    = null));
		        if(valo.Date_validation_perimetre__c == null)
		            missionsToUpsert.get(valo.MissionCIR__c).Date_fin_audit__c  = null;
		    else if(valo.Date_validation_perimetre__c == null)
		        missionsToUpsert.put(valo.MissionCIR__c, new INNOmission__c(Id                          = valo.MissionCIR__c,
		                                                                    Date_fin_audit__c           = null));
		        if(valo.Date_envoi_valorisation__c == null)    
		            missionsToUpsert.get(valo.MissionCIR__c).Date_fin_valorisation__c  = null;
	    }
		else
	        if(!this.tempMissionsToUpsert.isEmpty())
    	        this.missionDateFin(tempMissionsToUpsert);
	}
	
	public void afterUpdate(SObject oldSo, SObject so){
		INNOvalo__c oldValo = (INNOvalo__c) oldSo;
		INNOvalo__c valo = (INNOvalo__c) so;
		
		if(oldValo.Montant_CIR_definitif_option1__c != valo.Montant_CIR_definitif_option1__c 
			|| oldValo.Montant_CIR_definitif_option2__c != valo.Montant_CIR_definitif_option3__c
			|| oldValo.Montant_CIR_definitif_option3__c != valo.Montant_CIR_definitif_option3__c
			|| oldValo.Montant_CIR_definitif_optionFinale__c != valo.Montant_CIR_definitif_optionFinale__c){
			
			this.missionsIdsToUpdateRollups.add(valo.MissionCIR__c);
		}
		
		//EDIT Aurélien CLERC 15/06/2017
		if(oldValo.Date_envoi_valorisation__c != valo.Date_envoi_valorisation__c || oldValo.Date_validation_perimetre__c != valo.Date_validation_perimetre__c){
		    if(valo.Date_envoi_valorisation__c == null){
		        missionsToUpsert.put(valo.MissionCIR__c, new INNOmission__c(Id                          = valo.MissionCIR__c,
		                                                                    Date_fin_valorisation__c    = null));
		        if(valo.Date_validation_perimetre__c == null)
		            missionsToUpsert.get(valo.MissionCIR__c).Date_fin_audit__c  = null;
		    }
		    else if(valo.Date_validation_perimetre__c == null)
		        missionsToUpsert.put(valo.MissionCIR__c, new INNOmission__c(Id                          = valo.MissionCIR__c,
		                                                                    Date_fin_audit__c           = null));
		}
        if(!this.tempMissionsToUpsert.isEmpty())
    	   this.missionDateFin(tempMissionsToUpsert);      
	}
	
	public void afterDelete(SObject so){
	    INNOvalo__c valo = (INNOvalo__c) so;
	    
	    this.missionsValoDeleted.add(valo.MissionCIR__c);
	    
	    if(!this.missionsValoDeleted.isEmpty())
    	   this.missionDateFin(missionsValoDeleted);
	}
	
	public void andFinally(){
		
		if(!this.missionsIdsToUpdateRollups.isEmpty()){
			List<INNOmission__c> missionsToUpdate = new List<INNOmission__c>();
			for(AggregateResult aggr : [SELECT MissionCIR__c, 
												SUM(Montant_total_depenses_option1__c) depensesOpt1,
												SUM(Montant_total_depenses_option2__c) depensesOpt2,
												SUM(Montant_total_depenses_option3__c) depensesOpt3,
												SUM(Montant_total_depenses_optionFinale__c) depensesRetenu,
												SUM(Montant_CIR_definitif_option1__c) cirOpt1,
												SUM(Montant_CIR_definitif_option2__c) cirOpt2,
												SUM(Montant_CIR_definitif_option3__c) cirOpt3,
												SUM(Montant_CIR_definitif_optionFinale__c) cirRetenu
												
											FROM INNOvalo__c
											WHERE MissionCIR__c IN :this.missionsIdsToUpdateRollups
											GROUP BY MissionCIR__c]){
				missionsToUpdate.add(new INNOmission__c(Id 										= (Id) aggr.get('MissionCIR__c'),
														Montant_total_depenses_option1__c		= (Decimal) aggr.get('depensesOpt1'),
														Montant_total_depenses_option2__c		= (Decimal) aggr.get('depensesOpt2'),
														Montant_total_depenses_option3__c		= (Decimal) aggr.get('depensesOpt3'),
														Montant_total_depenses_optionFinale__c	= (Decimal) aggr.get('depensesRetenu'),
														Montant_CIR_definitif_option1__c 		= (Decimal) aggr.get('cirOpt1'),
														Montant_CIR_definitif_option2__c 		= (Decimal) aggr.get('cirOpt2'),
														Montant_CIR_definitif_option3__c 		= (Decimal) aggr.get('cirOpt3'),
														Montant_CIR_definitif_optionFinale__c	= (Decimal) aggr.get('cirRetenu')));
			}
			update missionsToUpdate;
		}
		upsert missionsToUpsert.values();
	}
	
	private void missionDateFin(Set<Id> setId){
	    //EDIT Aurélien CLERC 13/06/2017
	    for(AggregateResult aggr : [SELECT MissionCIR__c, MAX(Date_envoi_valorisation__c) maxDate, COUNT(Date_envoi_valorisation__c) valoDateRemplie, COUNT(Id) valoTotal FROM INNOvalo__c WHERE ValoA0__c = false AND MissionCIR__c IN :setId GROUP BY MissionCIR__c]){
	        if(aggr.get('valoDateRemplie') == aggr.get('valoTotal')){ 
	            if(!this.missionsToUpsert.containsKey((Id) aggr.get('MissionCIR__c'))){
	                this.missionsToUpsert.put((Id) aggr.get('MissionCIR__c'), new INNOmission__c(Id                          = (Id) aggr.get('MissionCIR__c'),
	                                                                                             Date_fin_valorisation__c    = (Date) aggr.get('maxDate')));
	            }
	        }
	    }
	    
	    for(AggregateResult aggr : [SELECT MissionCIR__c, MAX(Date_validation_perimetre__c) maxDate, COUNT(Date_validation_perimetre__c) valoDateRemplie, COUNT(Id) valoTotal FROM INNOvalo__c WHERE MissionCIR__c IN :setId GROUP BY MissionCIR__c]){
	        if(aggr.get('valoDateRemplie') == aggr.get('valoTotal')){
	            if(!this.missionsToUpsert.containsKey((Id) aggr.get('MissionCIR__c'))){
	                this.missionsToUpsert.put((Id) aggr.get('MissionCIR__c'), new INNOmission__c(Id                 = (Id) aggr.get('MissionCIR__c'),
	                                                                                             Date_fin_audit__c  = (Date) aggr.get('maxDate')));
	            }
	            else
	                this.missionsToUpsert.get((Id) aggr.get('MissionCIR__c')).Date_fin_audit__c  = (Date) aggr.get('maxDate');
	        }
	    }
	}
}