gac_sb/objects/INNOdepartement__c.object
<CustomObject>
    <fields>
        <fullName>Entite__c</fullName>
        <label>Entité</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DepartementsCIR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Département</label>
    <nameField>
        <label>Département</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Départements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOprojet__c.object
<CustomObject>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Difficultes_techniques__c</fullName>
        <inlineHelpText>Difficultés techniques / Incertitudes technologiques</inlineHelpText>
        <label>Difficultés techniques</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Etat_de_art__c</fullName>
        <inlineHelpText>Etat de l&apos;art / Motivations à l&apos;origine du projet</inlineHelpText>
        <label>Etat de l&apos;art</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Existence_documents_justificatifs__c</fullName>
        <inlineHelpText>Existence de documents justificatifs et nature</inlineHelpText>
        <label>Existence de documents justificatifs</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ImportId__c</fullName>
        <label>Id d&apos;import</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nom_regroupement_projet__c</fullName>
        <description>Si le projet est inclus dans un ensemble de projets, on saisi le nom de cet ensemble</description>
        <inlineHelpText>Si le projet est inclus dans un ensemble de projets, précisez le nom de cet ensemble.</inlineHelpText>
        <label>Nom du regroupement de projet</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Num_projet__c</fullName>
        <label>N° de projet</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objectifs_projet__c</fullName>
        <inlineHelpText>Objectifs du projet / Buts techniques visés</inlineHelpText>
        <label>Objectifs du projet</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Progres_accomplis__c</fullName>
        <inlineHelpText>Progrès accomplis / Avancée des connaissances</inlineHelpText>
        <label>Progrès accomplis</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Travaux_menes__c</fullName>
        <inlineHelpText>Travaux menés : Grandes orientations et étapes</inlineHelpText>
        <label>Travaux menés</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Champ invisible pour l&apos;utilisateur, permet de savoir si l&apos;enregistrement est un &quot;vrai&quot; projet ou si c&apos;est un enregistrement qui est la juste pour rattacher des dépenses de personnel aux veilles, PM de brevet ou normalisation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>projet</fullName>
                    <default>true</default>
                    <label>projet</label>
                </value>
                <value>
                    <fullName>veille</fullName>
                </value>
                <value>
                    <fullName>brevetPM</fullName>
                </value>
                <value>
                    <fullName>normalisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOvalo__c.object
<CustomObject>
    <fields>
        <fullName>Commentaires__c</fullName>
        <label>Commentaires</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entité</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Valorisations (Entité)</relationshipLabel>
        <relationshipName>Valorisations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Valorisation</label>
    <nameField>
        <label>Nom de la valorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valorisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOimport_projet.cls
public with sharing class INNOimport_projet extends INNOimport{
	
	private Id valoId;
	
	
	public override void init(Id valoId){
		
		this.valoId = valoId;
		
		this.existingRecordsWhereClause = 'WHERE Valorisation__c = \'' + this.valoId + '\' AND Type__c = \'projet\'';
		
		this.importTypeName = 'Projets';
		
		system.debug(this.valoId);
		List<INNOvalo__c> valos = [SELECT Id, Name, Entite__c FROM INNOvalo__c WHERE Id = :this.valoId LIMIT 1];
		
		this.pageTitle = valos[0].Name;
				
		this.excelFileName = 'INNO-Imports_projets.xlsx';

		this.sObjectDescribe = INNOprojet__c.SObjectType;
		
		this.standardColumns = new List<Map<String, String>>{ 
															new Map<String, String>{'Name'=>'Nom*', 'FieldName'=>'Name', 'Required'=>'true', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Nom du regroupement de projet', 'FieldName'=>'Nom_regroupement_projet__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'N° de projet', 'FieldName'=>'Num_projet__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Département', 'FieldName'=>'Departement__c', 'Required'=>'false', 'Type'=>'Picklist'},
															new Map<String, String>{'Name'=>'Etat de l\'art', 'FieldName'=>'Etat_de_art__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Objectifs du projet', 'FieldName'=>'Objectifs_projet__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Difficultés techniques', 'FieldName'=>'Difficultes_techniques__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Travaux menés', 'FieldName'=>'Travaux_menes__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Progrès accomplis', 'FieldName'=>'Progres_accomplis__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Existence de documents justificatifs', 'FieldName'=>'Existence_documents_justificatifs__c', 'Required'=>'false', 'Type'=>'String'},
															new Map<String, String>{'Name'=>'Commentaires', 'FieldName'=>'Commentaires__c', 'Required'=>'false', 'Type'=>'String'}
															};
															
		this.upsertKeyFieldName = 'Name';
	
		this.importIdField = 'ImportId__c';
		
		this.retPage = new pageReference( '/apex/INNOprojetList' );
		this.retPage.getParameters().put('id', this.valoId);
		this.retPage.getParameters().put('valoId', this.valoId);
		
		
		
		/*
		*	Initialisation des départements possibles du champ 'Departement'
		*/
		List<SelectOption> departements = new List<SelectOption>{new SelectOption('', '-Aucun-')};
		
		for(INNOdepartement__c dept : [SELECT Id, Name FROM INNOdepartement__c WHERE Entite__c = :valos[0].Entite__c ORDER BY Name])
			departements.add(new SelectOption(dept.Id, dept.Name));
			
		this.picklistValues.put('Departement__c', departements);	
	
	}



	protected override String getRowUpsertKeyValue(INNOimport.ImportRow row){
		return row.cells[0].value;
	}
	
	

	
	protected override sObject getRecord(ImportRow row){
		sObject record = new INNOprojet__c(Id = row.existingRecordId, Valorisation__c = this.valoId, Type__c = 'projet');
		
		for(INNOimport.ImportCell cell : row.cells){
			
			if(cell.datatype == 'Number')
				record.put(cell.fieldName, Decimal.valueOf(cell.value));
			else if(cell.datatype == 'Boolean')
				record.put(cell.fieldName, cell.value == 'oui' ? true : false);
			else if(cell.datatype == 'Date')
				record.put(cell.fieldName, cell.value == null ? null : Date.parse(cell.value));
			else
				record.put(cell.fieldName, cell.value);
				
		}
		
		return record;
	}
	
	

	
}