gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Permet de rendre actif un utilisateur</description>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Audit__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Audit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Justification__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Justif</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Valorisation__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Nombre de jours théoriques - Valo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Rôle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Consultant scientifique</fullName>
                    <default>true</default>
                    <label>Consultant scientifique</label>
                </value>
                <value>
                    <fullName>Consultant fiscaliste</fullName>
                </value>
                <value>
                    <fullName>Consultant extérieur</fullName>
                </value>
                <value>
                    <fullName>Rédacteur scientifique</fullName>
                </value>
                <value>
                    <fullName>Redacteur scientifique RO</fullName>
                    <label>Rédacteur scientifique RO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Annee_CIR__c</fullName>
        <label>Année CIR</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>MissionsCIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_debut_Audit__c</fullName>
        <label>Date début Audit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_debut_justification__c</fullName>
        <label>Date début justification</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_debut_valorisation__c</fullName>
        <label>Date début valorisation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_audit__c</fullName>
        <label>Date fin Audit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_valorisation__c</fullName>
        <label>Date fin valorisation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Audit__c</fullName>
        <label>Nombre de jours théoriques - Audit</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Audit__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Justification__c</fullName>
        <label>Nombre de jours théoriques - Justif</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Justification__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nombre_jours_theoriques_Valorisation__c</fullName>
        <label>Nombre de jours théoriques - Valo</label>
        <summarizedField>INNOequipeConsulting__c.Nombre_jours_theoriques_Valorisation__c</summarizedField>
        <summaryForeignKey>INNOequipeConsulting__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactif / en attente de renouvellement</fullName>
                </value>
                <value>
                    <fullName>Inactif / en attente de lancement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Valorisation</fullName>
                </value>
                <value>
                    <fullName>Justification</fullName>
                </value>
                <value>
                    <fullName>Terminée</fullName>
                </value>
                <value>
                    <fullName>Terminée - Dossier à 0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Taux_CIR__c</fullName>
        <label>Taux CIR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/INNOtimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duree__c</fullName>
        <description>La durée passé en jour (compris entre 0 et 1):
1 = toute la journée
0.5 = une demi-journée</description>
        <label>Durée</label>
        <precision>3</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission_CIR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>TimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Valorisation</fullName>
                </value>
                <value>
                    <fullName>Justification</fullName>
                </value>
                <value>
                    <fullName>Contrôle</fullName>
                </value>
                <value>
                    <fullName>Formation</fullName>
                </value>
                <value>
                    <fullName>Disponibilité</fullName>
                </value>
                <value>
                    <fullName>Avant-Vente / AO</fullName>
                </value>
                <value>
                    <fullName>AS/DI</fullName>
                </value>
                <value>
                    <fullName>CP / RTT</fullName>
                </value>
                <value>
                    <fullName>DUP</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>ASDI</fullName>
                    <isActive>false</isActive>
                    <label>ASDI</label>
                </value>
                <value>
                    <fullName>Administratif</fullName>
                    <isActive>false</isActive>
                    <label>Administratif</label>
                </value>
                <value>
                    <fullName>CP</fullName>
                    <isActive>false</isActive>
                    <label>CP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theorique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Théorique</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>INNOtimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TimeSheet CIR</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>TimeSheets INNO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheets CIR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/INNOvalo__c.object
<CustomObject>
    <fields>
        <fullName>Date_echeance_DT__c</fullName>
        <inlineHelpText>Date à laquelle le rendu de DT est prévu. Elle est modifiable</inlineHelpText>
        <label>Date d&apos;échéance DT</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entité</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Valorisations (Entité)</relationshipLabel>
        <relationshipName>Valorisations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipLabel>Valorisations</relationshipLabel>
        <relationshipName>Valorisations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Valorisation</label>
    <nameField>
        <label>Nom de la valorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Valorisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOplanningTest.cls
@isTest
private class INNOplanningTest {


	/**
	 * Tests de la classe INNOtauxOccupationTheoriqueCtrl (+INNOtauxOccupationBase)
	 */
	private static testMethod void testTauxOccupationTheorique() {


		INNOtestBase.initRecords();
		
		
		Date planningStartDate = System.today().toStartOfMonth();
		
		INNOmission__c mission = new INNOmission__c(Contrat__c 									= INNOtestBase.Contracts[0].Id, 
														Annee_CIR__c 							= '2015', 
														Phase__c 								= 'Audit', 
														Taux_cir__c 							= 30, 
														Date_debut_Audit__c						= planningStartDate,
														Date_fin_audit__c					 	= planningStartDate.addMonths(1).addDays(-1),
														Date_debut_valorisation__c				= planningStartDate.addMonths(1),
														Date_fin_valorisation__c				= planningStartDate.addMonths(2).addDays(-1),
														Date_debut_justification__c				= planningStartDate.addMonths(2));
		insert mission;
		
		insert new INNOvalo__c(MissionCIR__c = mission.Id, Entite__c = INNOtestBase.Accs[0].Id, Date_echeance_DT__c = planningStartDate.addMonths(2).addDays(20));											
		
		
		User superviseur = [SELECT Id FROM User WHERE IsActive = true AND UserType = 'Standard' AND UserRole.DeveloperName = 'SCIENTIFIQUE_SUPERVISEUR' LIMIT 1][0];
		
		Integer startMonthIndex = planningStartDate.month() - 1;
		INNOequipeConsulting__c eq = new INNOequipeConsulting__c(MissionCIR__c = mission.Id, Utilisateur__c = superviseur.Id, Role__c = 'Superviseur', Actif__c = true, Nombre_jours_theoriques_Audit__c = INNOtauxOccupationTheoriqueCtrl.nbBusinessDaysInMonth.get('SCIENTIFIQUE_SUPERVISEUR').get(startMonthIndex), Nombre_jours_theoriques_Valorisation__c = INNOtauxOccupationTheoriqueCtrl.nbBusinessDaysInMonth.get('SCIENTIFIQUE_SUPERVISEUR').get(Math.mod(startMonthIndex + 1, 12)), Nombre_jours_theoriques_Justification__c = INNOtauxOccupationTheoriqueCtrl.nbBusinessDaysInMonth.get('SCIENTIFIQUE_SUPERVISEUR').get(Math.mod(startMonthIndex + 2, 12)) / 2);
		insert eq;
		
		//RunAs Admin
		INNOtauxOccupationTheoriqueCtrl ctrl = new INNOtauxOccupationTheoriqueCtrl();
		
		
		//RunAs SCIENTIFIQUE_SUPERVISEUR
		System.runAs(superviseur){
		
			Test.startTest();
			
			ctrl = new INNOtauxOccupationTheoriqueCtrl();
			ctrl.dummyEquipeManager.Utilisateur__c = superviseur.Id;
			ctrl.applyFilters();
			
			ctrl.getHeaderValues();
			ctrl.getThis();
			
			system.debug(ctrl.usersOccupancyRates.size());
		
			system.assertEquals(100, ctrl.usersOccupancyRates[0].occupancyRates[0]);
			system.assertEquals(100, ctrl.usersOccupancyRates[0].occupancyRates[1]);
			system.assertEquals(50, ctrl.usersOccupancyRates[0].occupancyRates[2]);
			
			
			Test.stopTest();
		}
		
	}
	
	
	
	/**
	 * Tests de la classe INNOtauxOccupationReelCtrl (+INNOtauxOccupationBase)
	 * Tests de la classe INNOtimeSheetPlanningCtrl (+INNOtauxOccupationBase)
	 * Tests de la classe INNOtimeSheetPlanningCtrl2 (+INNOtauxOccupationBase)
	 */
	private static testMethod void testTauxOccupationReel() {


		INNOtestBase.initRecords();
		Id missionId = INNOtestBase.missions[0].Id;
		
		User superviseur = [SELECT Id FROM User WHERE IsActive = true AND UserType = 'Standard' AND UserRole.DeveloperName = 'SCIENTIFIQUE_SUPERVISEUR' LIMIT 1][0];
		
		INNOequipeConsulting__c eq = new INNOequipeConsulting__c(MissionCIR__c = missionId, Utilisateur__c = superviseur.Id, Role__c = 'Superviseur', Actif__c = true);
		insert eq;
		
		Date planningStartDate = System.today().toStartOfWeek().addDays(-7);
		
		List<INNOtimeSheet__c> timeSheets = new List<INNOtimeSheet__c>{ new INNOtimeSheet__c(Mission_CIR__c = missionId, Utilisateur__c = superviseur.Id, Date__c = planningStartDate.addDays(0), Duree__c = 1, Phase__c = 'Audit', Theorique__c = false),
																			new INNOtimeSheet__c(Mission_CIR__c = missionId, Utilisateur__c = superviseur.Id, Date__c = planningStartDate.addDays(7), Duree__c = 1, Phase__c = 'Audit', Theorique__c = false),
																			new INNOtimeSheet__c(Mission_CIR__c = missionId, Utilisateur__c = superviseur.Id, Date__c = planningStartDate.addDays(8), Duree__c = 1, Phase__c = 'Audit', Theorique__c = true)};
		insert timeSheets;
		
		
		//RunAs SCIENTIFIQUE_SUPERVISEUR
		System.runAs(superviseur){
		
			Test.startTest();
			
			INNOtauxOccupationReelCtrl ctrl = new INNOtauxOccupationReelCtrl();
			ctrl.dummyEquipeManager.Utilisateur__c = superviseur.Id;
			ctrl.applyFilters();
			
			ctrl.getHeaderValues();
			ctrl.getThis();
			
			system.debug(ctrl.usersOccupancyRates[0].occupancyRates);
			
			System.assertEquals(40, ctrl.usersOccupancyRates[0].occupancyRates[0]);		//Il y a 2j de TimeSheet sur la 1ere semaine => 40%
			
			
			
			INNOtimeSheetPlanningCtrl2 ctrlPlanning2 = new INNOtimeSheetPlanningCtrl2();
			ctrlPlanning2.dummyEquipeManager.Utilisateur__c = superviseur.Id;
			ctrlPlanning2.applyFilters();
			
			//Le 1er jour du 1er consultant est à 1j
			List<INNOtimeSheetPlanningCtrl2.Consultant> consultants = (List<INNOtimeSheetPlanningCtrl2.Consultant>) JSON.deserialize(ctrlPlanning2.consultantsJSON, List<INNOtimeSheetPlanningCtrl2.Consultant>.class);
			List<INNOtimeSheetPlanningCtrl2.Month> months = (List<INNOtimeSheetPlanningCtrl2.Month>) JSON.deserialize(ctrlPlanning2.monthsJSON, List<INNOtimeSheetPlanningCtrl2.Month>.class);
			System.assertEquals(1, consultants[0].durationsByDate.get(months[0].days[0].d));
			
			ctrlPlanning2 = new INNOtimeSheetPlanningCtrl2();
			ctrlPlanning2.dummyEquipeConsultant.MissionCIR__c = missionId;
			ctrlPlanning2.applyFilters();
			
			ctrlPlanning2 = new INNOtimeSheetPlanningCtrl2();
			ctrlPlanning2.dummyEquipeConsultant.Utilisateur__c = superviseur.Id;
			ctrlPlanning2.applyFilters();
			
			Test.stopTest();
		}
		
	}
	
	
	public static testMethod void TestINNOtimeSheetCtrl(){
        
        INNOtestBase.initRecords();
		Id missionId = INNOtestBase.missions[0].Id;

        
        test.startTest();
        Pagereference p = new Pagereference('/apex/AppCIRtimeSheetEdit');
        test.setCurrentPageReference(p);
        
        
        INNOtimeSheetCtrl ctrl = new INNOtimeSheetCtrl();
        
        //Une seule mission où le user courant est actif
        system.assertEquals(1, ctrl.missions.size());
        
        /*
        *   Tests de changements de semaine
        */
        Date lundi = system.today().toStartOfWeek();
        
        system.assertEquals(lundi, ctrl.dates[0]);
        
        p.getParameters().put('way', 'lower');
        ctrl.changeWeek();
        system.assertEquals(lundi.addDays(-7), ctrl.dates[0]);
        
        p.getParameters().put('way', 'upper');
        ctrl.changeWeek();
        system.assertEquals(lundi, ctrl.dates[0]);
        
        p.getParameters().put('way', null);
        p.getParameters().put('day', String.valueOf(lundi.addDays(2)));
        ctrl.changeWeek();
        system.assertEquals(lundi, ctrl.dates[0]);

        system.assertEquals(Integer.valueOf(DateTime.newInstance( lundi, Time.newInstance(12,0,0,0) ).format('w')), ctrl.numeroSemaine);
        
        
        /*
        *   Tests du save
        */
        INNOtimeSheetCtrl.saveTimeSheet(missionId, String.valueOf(lundi) , 'Audit', '0.2');
        INNOtimeSheetCtrl.saveTimeSheet(missionId, String.valueOf(lundi) , 'Audit', '0.2');

        String d = ctrl.dates[0].day() + '/' + ctrl.dates[0].month() + '/' + ctrl.dates[0].year();
        p.getParameters().put('firstDayOfWeekToValidate', d);
        ctrl.validateWeek();
        
        INNOtimeSheet.fillingLastWeekTimeSheetReminder();
	}
	
	public static testMethod void TestINNOtimeSheetHandler(){
        
        INNOtestBase.initRecords();
		Id missionId = INNOtestBase.missions[0].Id;
        User superviseur = [SELECT Id FROM User WHERE IsActive = true AND UserType = 'Standard' AND UserRole.DeveloperName = 'SCIENTIFIQUE_SUPERVISEUR' LIMIT 1][0];
        Date planningStartDate = System.today().toStartOfWeek().addDays(-7);
        
        test.startTest();
        
        List<INNOtimeSheet__c> timeSheets = new List<INNOtimeSheet__c>{ new INNOtimeSheet__c(Mission_CIR__c = missionId, Utilisateur__c = superviseur.Id, Date__c = planningStartDate.addDays(0), Duree__c = 0.5, Phase__c = 'Audit', Theorique__c = false),
																			new INNOtimeSheet__c(Mission_CIR__c = missionId, Utilisateur__c = superviseur.Id, Date__c = planningStartDate.addDays(7), Duree__c = 1, Phase__c = 'Audit', Theorique__c = false),
																			new INNOtimeSheet__c(Mission_CIR__c = missionId, Utilisateur__c = superviseur.Id, Date__c = planningStartDate.addDays(8), Duree__c = 1, Phase__c = 'Audit', Theorique__c = true)};
		insert timeSheets;
		
        timeSheets[0].Duree__c = 1;
        update timeSheets[0];
        delete timeSheets[2];
        
        Test.stopTest();
	}

}