gac_sb/objects/INNOdepartement__c.object
<CustomObject>
    <label>Département</label>
    <nameField>
        <label>Département</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Départements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOsubvention__c.object
<CustomObject>
    <fields>
        <fullName>Date_versement__c</fullName>
        <label>Date de versement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Subventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Matricule__c</fullName>
        <label>Matricule</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Montant_option1__c</fullName>
        <label>Montant option 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_option2__c</fullName>
        <label>Montant option 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_option3__c</fullName>
        <label>Montant option 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Organisme__c</fullName>
        <label>Organisme</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projet</label>
        <referenceTo>INNOprojet__c</referenceTo>
        <relationshipName>Subventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salarie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Uniquement pour les subventions, à choisir parmi les salariés de la mission</description>
        <label>Salarié</label>
        <referenceTo>INNOdepensePersonnel__c</referenceTo>
        <relationshipName>Subventions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Subventions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Subvention et avance</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subventions et avances</pluralLabel>
    <recordTypes>
        <fullName>subvention</fullName>
        <active>true</active>
        <label>Subventions</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOsubventionListCtrl.cls
public with sharing class INNOsubventionListCtrl extends INNOmissionBaseCtrl {


	public String tab {get; set;}
	
	
	public List<INNOsubvention__c> subventions {get; set;}
	

	public INNOsubventionListCtrl(ApexPages.standardController stdCtrl){
		
		this.tab = ApexPages.currentPage().getParameters().get('tab');
		
		if(this.tab == null)
			this.tab = 'subvention';
		
		this.subventions = [SELECT Id, 
									Name, 
									Organisme__c, 
									Matricule__c, 
									Date_versement__c, 
									Salarie__c, 
									Departement__c, 
									Departement__r.Name, 
									Projet__c, 
									Montant_option1__c, 
									Montant_option2__c, 
									Montant_option3__c 
								FROM INNOsubvention__c 
								WHERE RecordType.DeveloperName = :this.tab 
									AND Valorisation__c = :this.valo.Id];
		
	}
	
	
}