gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Permet de rendre actif un utilisateur</description>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Rôle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Consultant scientifique</fullName>
                    <default>true</default>
                    <label>Consultant scientifique</label>
                </value>
                <value>
                    <fullName>Consultant fiscaliste</fullName>
                </value>
                <value>
                    <fullName>Consultant extérieur</fullName>
                </value>
                <value>
                    <fullName>Rédacteur scientifique</fullName>
                </value>
                <value>
                    <fullName>Redacteur scientifique RO</fullName>
                    <label>Rédacteur scientifique RO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/ApexSharingRecalc_INNOmission.cls
/**
 * Utilisé en Queueable dans le trigger
 * mais on prévoit également le Batchable pour faire d'éventuels "Apex Sharing Recalculation"
 */
global without sharing class ApexSharingRecalc_INNOmission implements Database.Batchable<sObject>, Queueable{
	
	private static final String equipeConsultingMissionRowCause = Schema.INNOmission__Share.RowCause.Equipe_Consulting__c;
	
	private Set<Id> updatedMissionsINNOids;
	

	global ApexSharingRecalc_INNOmission(){}
	
	
	global ApexSharingRecalc_INNOmission(Set<Id> updatedMissionsINNOids){
		this.updatedMissionsINNOids = updatedMissionsINNOids;
	}
	

	/**
	 * Pour le Batchable
	 */
		global Database.QueryLocator start(Database.BatchableContext BC){
			if(this.updatedMissionsINNOids != null)
				return Database.getQueryLocator([SELECT Id FROM INNOmission__c WHERE Id IN :this.updatedMissionsINNOids]);
			else
				return Database.getQueryLocator([SELECT Id FROM INNOmission__c]);
		}
		
		global void execute(Database.BatchableContext BC, List<INNOmission__c> scope){
			this.recomputeSharing(scope);
		}
		
		global void finish(Database.BatchableContext BC){}
	
	
	/**
	 * Pour le Queueable
	 */
		global void execute(QueueableContext SC) {
			if(this.updatedMissionsINNOids != null)
				this.recomputeSharing([SELECT Id FROM INNOmission__c WHERE Id IN :this.updatedMissionsINNOids]);
			else
				this.recomputeSharing([SELECT Id FROM INNOmission__c]);
		}
	
	
	
	
	private void recomputeSharing(List<INNOmission__c> missionsINNO){
			
		system.debug('Start: BATCH ApexSharingRecalc_INNOmission');
		
		List<INNOmission__Share> newMissionINNOShrs = new List<INNOmission__Share>();
		
		system.debug(missionsINNO.size() + ' missions INNO');
		
		for(INNOequipeConsulting__c eq : [SELECT Id, MissionCIR__c, Utilisateur__c, Role__c FROM INNOequipeConsulting__c WHERE MissionCIR__c IN :missionsINNO AND Utilisateur__r.IsActive = true AND Actif__c = true]){
			newMissionINNOShrs.add(new INNOmission__Share(ParentId = eq.MissionCIR__c, UserOrGroupId = eq.Utilisateur__c, AccessLevel = (eq.Role__c == 'Consultant extérieur' ? 'Read' : 'Edit'), RowCause = equipeConsultingMissionRowCause));
		}
		
		system.debug(newMissionINNOShrs.size() + ' newMissionINNOShrs');
		
		Database.delete([SELECT Id FROM INNOmission__Share WHERE ParentId IN :missionsINNO AND RowCause = :equipeConsultingMissionRowCause], false);
		
		Database.insert(newMissionINNOShrs, false);
			
		system.debug('End: BATCH ApexSharingRecalc_INNOmission');
	}
	
}