gac_sb/objects/INNOamortissement__c.object
<CustomObject>
    <fields>
        <fullName>Annuite_amortissement__c</fullName>
        <label>Annuité d&apos;amortissement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Amortissements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Methode_de_calcul__c</fullName>
        <description>Sert à définir la méthode de calcul du taux R&amp;D</description>
        <label>Méthode de calcul du taux R&amp;D</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manuelle</fullName>
                    <default>true</default>
                    <label>Manuelle</label>
                </value>
                <value>
                    <fullName>Moyenne des sommes</fullName>
                </value>
                <value>
                    <fullName>Somme des moyennes</fullName>
                </value>
                <value>
                    <fullName>Moyenne des sommes du département</fullName>
                </value>
                <value>
                    <fullName>Somme des moyennes du département</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Montant_RD_retenu_option1__c</fullName>
        <formula>Annuite_amortissement__c * Taux_RD_option1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant R&amp;D retenu option 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_RD_retenu_option2__c</fullName>
        <formula>Annuite_amortissement__c * Taux_RD_option2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant R&amp;D retenu option 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_RD_retenu_option3__c</fullName>
        <formula>Annuite_amortissement__c * Taux_RD_option3__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant R&amp;D retenu option 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Num_immobilisation__c</fullName>
        <label>N° d&apos;immobilisation</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projet</label>
        <referenceTo>INNOprojet__c</referenceTo>
        <relationshipName>Amortissements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taux_RD_option1__c</fullName>
        <label>Taux R&amp;D option 1</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Taux_RD_option2__c</fullName>
        <label>Taux R&amp;D option 2</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Taux_RD_option3__c</fullName>
        <label>Taux R&amp;D option 3</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Amortissements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Amortissement</label>
    <nameField>
        <label>Désignation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amortissements</pluralLabel>
    <recordTypes>
        <fullName>amortissement</fullName>
        <active>true</active>
        <label>Dotations aux amortissements</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOdepartement__c.object
<CustomObject>
    <fields>
        <fullName>Entite__c</fullName>
        <label>Entité</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DepartementsCIR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Département</label>
    <nameField>
        <label>Département</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Départements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOprojet__c.object
<CustomObject>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Champ invisible pour l&apos;utilisateur, permet de savoir si l&apos;enregistrement est un &quot;vrai&quot; projet ou si c&apos;est un enregistrement qui est la juste pour rattacher des dépenses de personnel aux veilles, PM de brevet ou normalisation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>projet</fullName>
                    <default>true</default>
                    <label>projet</label>
                </value>
                <value>
                    <fullName>veille</fullName>
                </value>
                <value>
                    <fullName>brevetPM</fullName>
                </value>
                <value>
                    <fullName>normalisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Projets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projet</label>
    <nameField>
        <label>Nom du projet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOamortissementListCtrl.cls
global with sharing class INNOamortissementListCtrl extends INNOmissionBaseCtrl{

    public transient ApexPages.StandardSetController setController;
    
    public String tab {get; set;}
    
    
    public transient List<INNOamortissement__c> amortissements {get; set;}

    /*
    *   Variables ci-dessous: Pour la page AppCIRamortissementTauxRD uniquement
    */
    public INNOamortissementUtils tauxRDcls {get; set;}
    public List<INNOdepartement__c> departements {get; set;}
    public List<INNOprojet__c> projets {get; set;}  //Pour les filtres de la partie methode de calcul du taux R&D
    public Map<String, Checkbox> tauxRDupdates {get; set;}  //Bug VF: ca ne fonctionne pas si on met un boolean directement à la place de la inner class "Checkbox"
    private static final Map<String, String> methodesLabelsToValues = new Map<String, String>{'Manuelle' => 'manuelle',
                                                                                            'Moyenne des sommes' => 'moyenneSommes',
                                                                                            'Somme des moyennes' => 'sommeMoyennes',
                                                                                            'Moyenne des sommes du département' => 'moyenneSommesDepartements',
                                                                                            'Somme des moyennes du département' => 'sommeMoyennesDepartements'};
    
    public INNOamortissementListCtrl(ApexPages.StandardController stdCtrl){
        
        this.tab = ApexPages.currentPage().getParameters().get('tab');
        
        if(this.tab == null)
            this.tab = 'amortissement';
        
        this.amortissements = [SELECT Id, 
                                    Name, 
                                    Num_immobilisation__c, 
                                    Departement__c, 
                                    Departement__r.Name, 
                                    Projet__c,
                                    Projet__r.Name,
                                    Annuite_amortissement__c,
                                    Methode_de_calcul__c, 
                                    Taux_RD_option1__c ,
                                    Taux_RD_option2__c ,
                                    Taux_RD_option3__c ,
                                    Montant_RD_retenu_option1__c, 
                                    Montant_RD_retenu_option2__c, 
                                    Montant_RD_retenu_option3__c 
                            FROM INNOamortissement__c 
                            WHERE Valorisation__c = :this.valo.Id 
                                AND RecordType.DeveloperName = :this.tab];
        
        
        /*
        *   Pour la page AppCIRamortissementTauxRD uniquement
        */
        if(ApexPages.currentPage().getUrl().startsWith('/apex/INNOamortissementTauxRD') && this.tab == 'amortissement'){    
            this.tauxRDcls = new INNOamortissementUtils(this.valo.Id);
            this.departements = [SELECT Id, Name FROM INNOdepartement__c WHERE Entite__c = :(Id) stdCtrl.getRecord().get('Entite__c') ORDER BY Name];
            this.projets = [SELECT Id, Name FROM INNOprojet__c WHERE Valorisation__c = :this.valo.Id AND Type__c = 'projet' ORDER BY Name];
            
            this.tauxRDupdates = new Map<String, Checkbox>();
            
            for(INNOamortissement__c amo : this.amortissements){
                for(String methodeLabel : methodesLabelsToValues.keyset()){
                    this.tauxRDupdates.put(amo.Id + '_' + methodesLabelsToValues.get(methodeLabel), new Checkbox(amo.Methode_de_calcul__c == methodeLabel));
                }
            }
        }
    }
    
    
    
    
        
    
    
    /**
    *   Sauvegarde en masse les methode de calcul des tauc R&D
    *   Pour la page AppCIRamortissementTauxRD uniquement
    *   @return PageReference vers la page de modification des taux R&D (on refresh la page pour que tous les recalculs soit faits)
    */
    public PageReference saveMethodeCalculTauxRD(){
        
        //La liste des dotations aux amortissements dont la methode de calcul à changé
        List<INNOamortissement__c> dotationToUpdate = new List<INNOamortissement__c>();
        
        system.debug(this.tauxRDupdates.get('a1x5E0000000s2gQAA_manuelle'));
        system.debug(this.tauxRDupdates.get('a1x5E0000000s2gQAA_moyenneSommes'));
        system.debug(this.tauxRDupdates.get('a1x5E0000000s2gQAA_sommeMoyennes'));
        
        
        //Boucle sur toutes les dotations aux amortissements
        for(INNOamortissement__c amo : [SELECT Id, Methode_de_calcul__c FROM INNOamortissement__c WHERE Valorisation__c = :this.valo.Id AND RecordType.DeveloperName = :this.tab]){
            
            if(amo.Id=='a1x5E0000000s2gQAA'){
                
                system.debug(amo);
                system.debug(methodesLabelsToValues.get(amo.Methode_de_calcul__c));
                system.debug(this.tauxRDupdates.get(amo.Id + '_' + methodesLabelsToValues.get(amo.Methode_de_calcul__c)));
            }
            
            //Si la methode de calcul a changé
            if( ! this.tauxRDupdates.get(amo.Id + '_' + methodesLabelsToValues.get(amo.Methode_de_calcul__c)).selected ){
                    system.debug(amo);
                        
                //Boucle sur toutes les methodes de calcul pour savoir laquelle est coché
                for(String methodeLabel : methodesLabelsToValues.keyset()){
                    
                    if ( this.tauxRDupdates.get( amo.Id + '_' + methodesLabelsToValues.get(methodeLabel) ).selected){
                        system.debug(amo);
                        amo.Methode_de_calcul__c = methodeLabel;
                        dotationToUpdate.add(amo);
                        break;
                    }
                }
            }
        }

        //Update des dotaions aux amortissements qui ont changées
        if(dotationToUpdate.size() > 0)
            update dotationToUpdate;
        
        system.debug(dotationToUpdate);
        PageReference retPage = new pageReference( '/apex/INNOamortissementTauxRD' );
        retPage.getParameters().put('valoId', this.valo.Id);
        retPage.getParameters().put('tab', this.tab);
        retPage.setRedirect(true);
        return retPage; 
    }
    
    
    
    
    /**
    *   Inner class pour palier au bug VF qui fait qu'on ne peut pas mettre directement un Boolean dans les checkbox...
    */
    public class Checkbox{
        
        public Boolean selected {get; set;}
        
        public Checkbox(Boolean selected){
            this.selected = selected;
        }
    }
    
    

}