gac_sb/objects/INNOcoutStandard__c.object
<CustomObject>
    <label>Coût standard INNO advance</label>
    <nameField>
        <displayFormat>CSinno-{000}</displayFormat>
        <label>Coût standard INNO advance 2</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coûts standards INNO advance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Cout_standard_INNO_advance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Coût standard INNO advance</label>
        <referenceTo>INNOcoutStandard__c</referenceTo>
        <relationshipName>Missions_CIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Initiale_echeance_DT__c</fullName>
        <inlineHelpText>Date contractuelle ou fixée par le manager. Date figée</inlineHelpText>
        <label>Date Initiale échéance DT</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_justification_recap__c</fullName>
        <inlineHelpText>Calculée automatiquement avec le MAX des Dates d&apos;échéance DT des valorisations associées</inlineHelpText>
        <label>Date fin justification</label>
        <summarizedField>INNOvalo__c.Date_echeance_DT__c</summarizedField>
        <summaryForeignKey>INNOvalo__c.MissionCIR__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>CASE( Phase__c , 
&apos;Inactif / en attente de renouvellement&apos;, &apos;Inactive&apos;, 
&apos;Inactif / en attente de lancement&apos;, &apos;Inactive&apos;, 
&apos;Terminée&apos;, IF(NombreCFenCours__c &gt; 0, &apos;Active&apos;, &apos;Terminée&apos;), 
&apos;Terminée - Dossier à 0&apos;, &apos;Terminée&apos;, 
&apos;Active&apos;)</formula>
        <label>Statut</label>
        <type>Text</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <recordTypes>
        <fullName>AS</fullName>
        <active>true</active>
        <label>AS</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/INNOmissionHandler.cls
/**
 * Class INNOmissionHandler
 *
 * Trigger Handler for the INNOmission__c	 SObject. This class implements the ITrigger
 * interface to help ensure the trigger code is bulkified and all in one place.
 */

public with sharing class INNOmissionHandler implements ITrigger {
	
	
	private Set<INNOmission__c> missiondToRetrieveCoutsStandards = new Set<INNOmission__c>();
	
	
	// Constructor
	public INNOmissionHandler(){
	}

	
	public void bulkBefore(){
	}
	
	public void bulkAfter(){
	}
		
	/**
	*/
	public void beforeInsert(SObject so){
		INNOmission__c m = (INNOmission__c) so;
		
		if(m.Cout_standard_INNO_advance__c == null)
			this.missiondToRetrieveCoutsStandards.add(m);
	}
	
	public void beforeUpdate(SObject oldSo, SObject so){
		INNOmission__c oldM = (INNOmission__c) oldSo;
		INNOmission__c m = (INNOmission__c) so;
		
		if(oldM.Statut__c != 'Active' && m.Statut__c == 'Active')
			this.missiondToRetrieveCoutsStandards.add(m);
			
		if(m.Date_Initiale_echeance_DT__c == null && m.Date_fin_justification_recap__c != null)
			m.Date_Initiale_echeance_DT__c = m.Date_fin_justification_recap__c;
	}
	
	public void beforeDelete(SObject so){	
	}
	
	public void afterInsert(SObject so){
	}
	
	public void afterUpdate(SObject oldSo, SObject so){
	}
	
	public void afterDelete(SObject so){
	}
	
	
	/**
	 * andFinally
	 *
	 * This method is called once all records have been processed by the trigger. Use this 
	 * method to accomplish any final operations such as creation or updates of other records.
	 */
	public void andFinally(){

		//Récupère les couts standards		
		this.retrieveCoutsStandards();
	}
	
	
	
	private void retrieveCoutsStandards(){
		
		if(!this.missiondToRetrieveCoutsStandards.isEmpty()){
		
			List<INNOcoutStandard__c> coutsStandards = [SELECT Id FROM INNOcoutStandard__c ORDER BY CreatedDate DESC LIMIT 1];

			if( ! coutsStandards.isEmpty() ){
				for(INNOmission__c m : this.missiondToRetrieveCoutsStandards)
					m.Cout_standard_INNO_advance__c = coutsStandards[0].Id;
			}
			
		}
			
	}
	

}