gac_sb/objects/INNOdepensePrestation__c.object
<CustomObject>
    <fields>
        <fullName>Montant_retenu_option1__c</fullName>
        <description>= montant * taux SAUF si c&apos;est un prestataire d&apos;organisme public (=2 * montant * taux)</description>
        <formula>IF( $RecordType.DeveloperName = &apos;prestataire&apos; &amp;&amp; ISPICKVAL(Type_organisme__c, &apos;Public&apos;),  
	2 * Montant_HT__c * Taux_option1__c , 
	Montant_HT__c * Taux_option1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant retenu option 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_retenu_option2__c</fullName>
        <description>= montant * taux SAUF si c&apos;est un prestataire d&apos;organisme public (=2 * montant * taux)</description>
        <formula>IF( $RecordType.DeveloperName = &apos;prestataire&apos; &amp;&amp; ISPICKVAL(Type_organisme__c, &apos;Public&apos;),  
	2 * Montant_HT__c * Taux_option2__c , 
	Montant_HT__c * Taux_option2__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant retenu option 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_retenu_option3__c</fullName>
        <description>= montant * taux SAUF si c&apos;est un prestataire d&apos;organisme public (=2 * montant * taux)</description>
        <formula>IF( $RecordType.DeveloperName = &apos;prestataire&apos; &amp;&amp; ISPICKVAL(Type_organisme__c, &apos;Public&apos;),  
	2 * Montant_HT__c * Taux_option3__c , 
	Montant_HT__c * Taux_option3__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Montant retenu option 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Num_piece__c</fullName>
        <label>N° pièce</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prestataire__c</fullName>
        <label>Prestataire</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_organisme__c</fullName>
        <label>Type d&apos;organisme</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Agréé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Depenses_de_prestation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dépense de prestation</label>
    <nameField>
        <label>Prestation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses de prestation</pluralLabel>
    <recordTypes>
        <fullName>brevetPM</fullName>
        <active>true</active>
        <label>Prises et maintenances de brevets</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOdepensePrestationListCtrl.cls
/**
*  Controller du composent Visualforce INNOdepensePrestationList
*/
public with sharing class INNOdepensePrestationListCtrl extends INNOmissionBaseCtrl{
	
	
	public String tab {get; set;}
	
	
	public transient List<INNOdepensePrestation__c> prestations {get; set;}
	
	
	public INNOdepensePrestationListCtrl(){
	
		this.tab = ApexPages.currentPage().getParameters().get('tab');
		
		if(this.tab == null)
			this.tab = 'brevetPM';
		  
		this.prestations = [SELECT Id, 
									Name, 
									Num_piece__c, 
									Prestataire__c, 
									Type_organisme__c, 
									Montant_retenu_option1__c, 
									Montant_retenu_option2__c, 
									Montant_retenu_option3__c 
								FROM INNOdepensePrestation__c 
								WHERE RecordType.DeveloperName = :this.tab 
									AND Valorisation__c = :this.valo.Id];
	
	}
	
	
	
	
    
}