gac_sb/objects/INNOequipeConsulting__c.object
<CustomObject>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Permet de rendre actif un utilisateur</description>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MissionCIR__c</fullName>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>EquipesConsulting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Rôle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Consultant scientifique</fullName>
                    <default>true</default>
                    <label>Consultant scientifique</label>
                </value>
                <value>
                    <fullName>Consultant fiscaliste</fullName>
                </value>
                <value>
                    <fullName>Consultant extérieur</fullName>
                </value>
                <value>
                    <fullName>Rédacteur scientifique</fullName>
                </value>
                <value>
                    <fullName>Redacteur scientifique RO</fullName>
                    <label>Rédacteur scientifique RO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EquipesConsulting2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipe consulting</label>
    <nameField>
        <displayFormat>EquipeConsulting-{000000}</displayFormat>
        <label>Nom de l&apos;équipe consulting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipes consulting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOtimeSheet__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duree__c</fullName>
        <description>La durée passé en jour (compris entre 0 et 1):
1 = toute la journée
0.5 = une demi-journée</description>
        <label>Durée</label>
        <precision>3</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mission_CIR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mission CIR</label>
        <referenceTo>INNOmission__c</referenceTo>
        <relationshipName>TimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passée</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Valorisation</fullName>
                </value>
                <value>
                    <fullName>Justification</fullName>
                </value>
                <value>
                    <fullName>Contrôle</fullName>
                </value>
                <value>
                    <fullName>Formation</fullName>
                </value>
                <value>
                    <fullName>Disponibilité</fullName>
                </value>
                <value>
                    <fullName>Avant-Vente / AO</fullName>
                </value>
                <value>
                    <fullName>AS/DI</fullName>
                </value>
                <value>
                    <fullName>CP / RTT</fullName>
                </value>
                <value>
                    <fullName>DUP</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>ASDI</fullName>
                    <isActive>false</isActive>
                    <label>ASDI</label>
                </value>
                <value>
                    <fullName>Administratif</fullName>
                    <isActive>false</isActive>
                    <label>Administratif</label>
                </value>
                <value>
                    <fullName>CP</fullName>
                    <isActive>false</isActive>
                    <label>CP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theorique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Théorique</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utilisateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utilisateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>INNOtimeSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TimeSheet CIR</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>TimeSheets INNO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheets CIR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/classes/INNOtimeSheet.cls
global without sharing class INNOtimeSheet {
	
    public INNOtimeSheet(INNOtimeSheetPlanningCtrl2 controller){}
    
	public static void fillingLastWeekTimeSheetReminder(){
		
		//Le role des consultants devant remplir leurs TimeSheet
		String TimeSheetUserRole = 'GAC_World_Wide';//'SCIENTIFIQUE_CONSULTANT'; 
		
		//Lundi dernier
		Date lastMonday = system.today().toStartOfWeek().addDays(-7);
	
	
		//Tous les utilisateurs devant remplir une TimeSheet
		Map<Id, User> timeSheetUsers = new Map<Id, User>([SELECT Id, Name, Email, ManagerId, Manager.Email FROM User WHERE IsActive = true AND UserRole.DeveloperName = :TimeSheetUserRole ]);
		
		//Boucle sur tous les consultants qui ont bien rempli 5 jours sur leur TimeSheet de la semaine précédente
		for(AggregateResult aggr : [SELECT SUM(Duree__c) total, Utilisateur__c  FROM INNOtimeSheet__c WHERE Date__c >= :lastMonday AND Date__c <= :lastMonday.addDays(4) AND Utilisateur__r.IsActive = true AND Utilisateur__r.UserRole.DeveloperName = :TimeSheetUserRole GROUP BY Utilisateur__c HAVING SUM(Duree__c) = 5]){
			
			//On supprime le consultant de timeSheetUsers car il a bien rempli sa TimeSheet, il ne nous intéresse donc plus
			timeSheetUsers.remove((Id) aggr.get('Utilisateur__c'));
		}

		
		List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
		Messaging.SingleEmailMessage mail;
		
		
		Id emailTemplateId = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'INNO_Rappel_remplissage_TimeSheet' LIMIT 1][0].Id;
		
		String addresses = '';
		
		for(User u : timeSheetUsers.values()){
			mail = new Messaging.SingleEmailMessage();
			
			mail.setTemplateID(emailTemplateId);
			mail.setUseSignature(false);
	    	mail.setSaveAsActivity(false);
	    	
			mail.setTargetObjectId(u.Id);
			if(u.Manager.Email != null)
				mail.setCcAddresses( new List<String>{u.Manager.Email} );
			
			mails.add(mail);
			
			addresses += u.Email + ', ';
		}
		
		system.debug('Tentative d\'envoi de ' + mails.size() + ' emails de rappel de remplissage de TimeSheet');
		system.debug('Destinataires: ' + addresses);
		
		Integer nbEmailSuccess = 0;
		
		for(Messaging.SendEmailResult result : Messaging.sendEmail(mails, false)){
			if(result.isSuccess())
				nbEmailSuccess ++;
			else{
				for(Messaging.SendEmailError error : result.getErrors()){
					system.debug('Erreur d\'envoi pour ' + error.getTargetObjectId() + ' : ' + error.getMessage());
				}
			}
		}
		
		system.debug('Emails correctement envoyés : ' + nbEmailSuccess);
	}
	
	
	
	public static Boolean saveTimeSheet(String missionId, String tsDate, String phase, String dureeStr, String userId){
		
        missionId = (missionId == 'general' ? null : missionId);
		Decimal duree = String.isBlank(dureeStr) ? 0 : decimal.valueOf(dureeStr);
        phase = INNOtimeSheetCtrl.PHASES_LABELS.get(phase);
		String[] dateSplit = tsDate.split('-');
        Date d = Date.newInstance(Integer.valueOf(dateSplit[0]), Integer.valueOf(dateSplit[1]), Integer.valueOf(dateSplit[2]));
        Boolean theorique = (d < System.today().toStartOfWeek() || d > System.today().toStartOfWeek().addDays(4));
		if(String.isBlank(userId))
			userId = UserInfo.getUserId();
		
		//Si on rempli la TS d'un autre utilisateur, on vérifi qu'on est Superviseur ou Manager sur la mission
		if(String.isNotBlank(missionId) && userId != UserInfo.getUserId()){
			List<INNOequipeConsulting__c> equipes = [SELECT Id FROM INNOequipeConsulting__c WHERE MissionCIR__c = :missionId AND Utilisateur__c = :UserInfo.getUserId() AND Actif__c = true AND (Role__c = 'Superviseur' OR Role__c = 'Manager')];
			if(equipes.isEmpty())
				return false;
		}
		
		INNOtimeSheet__c ts;
		try{

			List<INNOtimeSheet__c> tsList = [SELECT Id, Duree__c FROM INNOtimeSheet__c WHERE Utilisateur__c = :userId AND Mission_CIR__c = :missionId AND Date__c = :d AND Phase__c = :phase LIMIT 1];
			
			Savepoint sp = Database.setSavepoint();

			if(!tsList.isEmpty()){
				ts = tsList[0];
        
				if(duree == 0){
					Database.delete(ts);
				}
				else{
					ts.Duree__c = duree;
					ts.Theorique__c = theorique;
					update ts;
				}
			}
			else if(duree != 0){
				
				ts = new INNOtimeSheet__c(Mission_CIR__c = missionId, Utilisateur__c = userId, Date__c = d, Phase__c = phase, Duree__c = duree, Theorique__c = theorique, Passee__c = (d <= System.today()));
				insert ts;
			}
			
            Decimal totalTime = (Decimal) [SELECT SUM(Duree__c) sum FROM INNOtimeSheet__c WHERE Utilisateur__c = :userId AND Date__c = :d][0].get('sum');
            if(totalTime != null && totalTime > 1){
				Database.rollback(sp);
				throw new TriggerException();
            }

			return true;
		}
		catch(Exception e){
			return false;
		}
	}
	
}