gac_sb/objects/INNOamortissement__c.object
<CustomObject>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Amortissements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Forcer_recalcul_taux_RD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Utile pour les triggers, ne pas utiliser/afficher ailleurs</description>
        <label>Forcer le recalcul taux R&amp;D</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Methode_de_calcul__c</fullName>
        <description>Sert à définir la méthode de calcul du taux R&amp;D</description>
        <label>Méthode de calcul du taux R&amp;D</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manuelle</fullName>
                    <default>true</default>
                    <label>Manuelle</label>
                </value>
                <value>
                    <fullName>Moyenne des sommes</fullName>
                </value>
                <value>
                    <fullName>Somme des moyennes</fullName>
                </value>
                <value>
                    <fullName>Moyenne des sommes du département</fullName>
                </value>
                <value>
                    <fullName>Somme des moyennes du département</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Amortissements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Amortissement</label>
    <nameField>
        <label>Désignation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amortissements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOdepensePersonnel__c.object
<CustomObject>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Si décoché, permet de ne pas prendre en compte le salarié pour l&apos;ensemble des postes de dépense</description>
        <inlineHelpText>Si décoché, permet de ne pas prendre en compte le salarié pour l&apos;ensemble des postes de dépense</inlineHelpText>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Departement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Département</label>
        <referenceTo>INNOdepartement__c</referenceTo>
        <relationshipName>Depenses_de_personnel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option1__c</fullName>
        <label>Heures R&amp;D option 1</label>
        <summarizedField>INNOpersonnelToProjet__c.Heures_RD_option1__c</summarizedField>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryForeignKey>INNOpersonnelToProjet__c.Depense_de_personnel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option2__c</fullName>
        <label>Heures R&amp;D option 2</label>
        <summarizedField>INNOpersonnelToProjet__c.Heures_RD_option2__c</summarizedField>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryForeignKey>INNOpersonnelToProjet__c.Depense_de_personnel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option3__c</fullName>
        <label>Heures R&amp;D option 3</label>
        <summarizedField>INNOpersonnelToProjet__c.Heures_RD_option3__c</summarizedField>
        <summaryFilterItems>
            <field>INNOpersonnelToProjet__c.Type_projet__c</field>
            <operation>equals</operation>
            <value>projet</value>
        </summaryFilterItems>
        <summaryForeignKey>INNOpersonnelToProjet__c.Depense_de_personnel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Nom__c</fullName>
        <label>Nom</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prenom__c</fullName>
        <label>Prénom</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_heures_travaillees_option1__c</fullName>
        <label>Total heures travaillées option 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_heures_travaillees_option2__c</fullName>
        <label>Total heures travaillées option 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_heures_travaillees_option3__c</fullName>
        <label>Total heures travaillées option 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UniteTempsDepensesPersonnel__c</fullName>
        <label>Unité de temps</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Heures</fullName>
                </value>
                <value>
                    <fullName>Jours</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valorisation__c</fullName>
        <label>Valorisation</label>
        <referenceTo>INNOvalo__c</referenceTo>
        <relationshipName>Depenses_de_personnel</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dépense de personnel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses de personnel</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/INNOpersonnelToProjet__c.object
<CustomObject>
    <fields>
        <fullName>Depense_de_personnel__c</fullName>
        <label>Dépense de personnel</label>
        <referenceTo>INNOdepensePersonnel__c</referenceTo>
        <relationshipName>Depenses_de_personnel_to_projets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option1__c</fullName>
        <label>Heures R&amp;D option 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option2__c</fullName>
        <label>Heures R&amp;D option 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Heures_RD_option3__c</fullName>
        <label>Heures R&amp;D option 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UniteTempsDepensesPersonnel2__c</fullName>
        <label>Unité de temps 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Dépense de personnel to projet</label>
    <nameField>
        <displayFormat>PtP-{000000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dépenses de personnel to projets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/classes/INNOdepensePersonnelHandler.cls
/**
 * Class INNOdepensePersonnelHandler
 *
 * Trigger Handler for the INNOdepensePersonnel__c	 SObject. This class implements the ITrigger
 * interface to help ensure the trigger code is bulkified and all in one place.
 */

public with sharing class INNOdepensePersonnelHandler implements ITrigger {
	
	private static final Set<String> populateOptionFiscaleFields = new Set<String>{'Salaire_charge', 'Total_heures_travaillees', 'Salaire_brut_annuel'};

	//Contiendra tous les Id des valos dans lesquelles il faudra mettre à jour les dotations aux amortissements
	private Set<Id> valosIdsToUpdateAmortissement = new Set<Id>();
	
	//copie de l'unité de temps vers le CJO
	private Map<Id,List<INNOpersonnelToProjet__c>> ppsById = new Map<Id,List<INNOpersonnelToProjet__c>>();
	private List<INNOpersonnelToProjet__c> ppsToUpdate = new List<INNOpersonnelToProjet__c>();
	
	// Constructor
	public INNOdepensePersonnelHandler(){
	}

	
	public void bulkBefore(){
	}
	
	public void bulkAfter(){
	    
	    if(Trigger.isUpdate){
	        List<INNOpersonnelToProjet__c> pps = [SELECT Id, Depense_de_personnel__c FROM INNOpersonnelToProjet__c WHERE Depense_de_personnel__c IN :Trigger.new];
            for(INNOpersonnelToProjet__c pp : pps){
                if(!ppsById.containsKey(pp.Depense_de_personnel__c))
                    ppsById.put(pp.Depense_de_personnel__c, new List<INNOpersonnelToProjet__c>());
                ppsById.get(pp.Depense_de_personnel__c).add(pp);
            }
	    }
	}
		
	/**
	*/
	public void beforeInsert(SObject so){
		INNOdepensePersonnel__c personnel = (INNOdepensePersonnel__c) so;
		
		INNOmissionBaseCtrl.populateOptionsFiscales((sObject) personnel, populateOptionFiscaleFields);
		
		initDefaultValues(personnel);
	}
	
	public void beforeUpdate(SObject oldSo, SObject so){
		INNOdepensePersonnel__c oldPersonnel = (INNOdepensePersonnel__c) oldSo;
		INNOdepensePersonnel__c personnel = (INNOdepensePersonnel__c) so;
		
		initDefaultValues(personnel);
	}
	
	public void beforeDelete(SObject so){	
	}
	
	public void afterInsert(SObject so){
		INNOdepensePersonnel__c personnel = (INNOdepensePersonnel__c) so;
		
		if(personnel.Actif__c){												//SI on ajoute un personnel actif 
			valosIdsToUpdateAmortissement.add(personnel.Valorisation__c);	//ALORS il faudra faire un update des dotations aux amortissements de la valo
		}
	}
	
	public void afterUpdate(SObject oldSo, SObject so){
		INNOdepensePersonnel__c oldPersonnel = (INNOdepensePersonnel__c) oldSo;
		INNOdepensePersonnel__c personnel = (INNOdepensePersonnel__c) so;
		
		
		//Si un des champs suivant a changé: Actif, Département, les Heures R&D, le total des heures travaillées		
		if(oldPersonnel.Actif__c != personnel.Actif__c || oldPersonnel.Departement__c != personnel.Departement__c || oldPersonnel.Heures_RD_option1__c != personnel.Heures_RD_option1__c || oldPersonnel.Heures_RD_option2__c != personnel.Heures_RD_option2__c || oldPersonnel.Heures_RD_option3__c != personnel.Heures_RD_option3__c || oldPersonnel.Total_heures_travaillees_option1__c != personnel.Total_heures_travaillees_option1__c || oldPersonnel.Total_heures_travaillees_option2__c != personnel.Total_heures_travaillees_option2__c || oldPersonnel.Total_heures_travaillees_option3__c != personnel.Total_heures_travaillees_option3__c){
			valosIdsToUpdateAmortissement.add(personnel.Valorisation__c);	//ALORS il faudra faire un update des dotations aux amortissements de la valo
		}
				
		if(oldPersonnel.UniteTempsDepensesPersonnel__c != personnel.UniteTempsDepensesPersonnel__c){
		    setPPUnite(personnel);
		}
		
	}
	
	public void afterDelete(SObject so){
	}
	
	/**
	 * andFinally
	 *
	 * This method is called once all records have been processed by the trigger. Use this 
	 * method to accomplish any final operations such as creation or updates of other records.
	 */
	public void andFinally(){
		
		/**
		*	On effectue l'update des dotations aux amortissements si c'est nécéssaire
		*/
		if(valosIdsToUpdateAmortissement.size() > 0){
			//La liste des dotations aux amortissements qu'il faudra mettre à jour
			List<INNOamortissement__c> amortissementsToUpdate = [SELECT Id, Valorisation__c FROM INNOamortissement__c WHERE Valorisation__c IN :valosIdsToUpdateAmortissement AND Methode_de_calcul__c != 'Manuelle'];
			for(INNOamortissement__c amo : amortissementsToUpdate)
				amo.Forcer_recalcul_taux_RD__c = true;
			
			//Update les dotations aux amortissements nécéssaires	
			update amortissementsToUpdate;
		}
		
		if(this.ppsToUpdate.size() > 0){
			update this.ppsToUpdate;
		}
		
	}
	
	
	
	private void initDefaultValues(INNOdepensePersonnel__c personnel){
		personnel.Name = personnel.Prenom__c + ' ' + personnel.Nom__c;
		
		//Si les champs Heures_XXXX_optionY__c sont null, on y met 0
		for(String f : new Set<String>{'RD','veille','normalisation','brevetPM'}){
			for(Integer i = 1; i < 4; i++){
				if(personnel.get('Heures_' + f + '_option' + String.valueOf(i) + '__c') == null)
					personnel.put('Heures_' + f + '_option' + String.valueOf(i) + '__c', 0);
			}
		}
	}
	
	private void setPPUnite(INNOdepensePersonnel__c personnel){
		
		if(this.ppsById.containsKey(personnel.Id)){
		    for(INNOpersonnelToProjet__c pp : this.ppsById.get(personnel.Id)){
		        pp.UniteTempsDepensesPersonnel2__c = personnel.UniteTempsDepensesPersonnel__c;
		        this.ppsToUpdate.add(pp);
		    }
		}          
	}
}