gac_sb/objects/INNOmission__c.object
<CustomObject>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>MissionsCIR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactif / en attente de renouvellement</fullName>
                </value>
                <value>
                    <fullName>Inactif / en attente de lancement</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>Valorisation</fullName>
                </value>
                <value>
                    <fullName>Justification</fullName>
                </value>
                <value>
                    <fullName>Terminée</fullName>
                </value>
                <value>
                    <fullName>Terminée - Dossier à 0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Taux_CIR__c</fullName>
        <label>Taux CIR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Mission CIR</label>
    <nameField>
        <label>Nom de la mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions CIR</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/INNOmissionCtrl.cls
public with sharing class INNOmissionCtrl extends INNOmissionBaseCtrl{

    
    //Le controller standard de la mission
    private ApexPages.standardController stdCtrl;
    
    
      
    public PageReference checkParams(){
  
        if( this.stdCtrl.getId() != null && ApexPages.currentPage().getParameters().get('missionId') == null){
        	PageReference retPage = new PageReference('/apex/INNOmissionView');
	        retPage.getParameters().put('id', this.stdCtrl.getId());
	        retPage.getParameters().put('missionId', this.stdCtrl.getId());
	        retPage.setRedirect(true);
        	return retPage;
        }
        
        return null;
    }
    

    /**
    *   Constructeur
    */
    public INNOmissionCtrl(ApexPages.standardController stdCtrl){
        
        this.mission = (INNOmission__c) stdCtrl.getRecord();

        
        this.stdCtrl = stdCtrl;

    	if(ApexPages.currentPage().getParameters().get('sharingRecalc') == '1')
    		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Le partage de la mission aux équipes consulting peut prendre quelques minutes...'));
    }
    
    
    	
    public INNOcontrat getContrat(){
		return new INNOcontrat(this.mission.Contrat__c);
	}
    
    
    public List<INNOmission__c> getMissionsSoeurs(){
    	return [SELECT Id, Name, Taux_CIR__c, Phase__c FROM INNOmission__c WHERE Contrat__c = :this.mission.Contrat__c AND Id != :this.stdCtrl.getId()];
    }
    
    
    
    
    
    
}