gac_sb/objects/Mission__c.object
<CustomObject>
    <description>SF CONSULTING - Cet objet contient toutes les informations des missions (infos spécifiques des BU, année concernée, CA facturé, encaissé, prev., etc...)</description>
    <fields>
        <fullName>Compte__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Missions</relationshipLabel>
        <relationshipName>Missions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mission</label>
    <nameField>
        <label>Mission</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/objects/Note_De_Frais__c.object
<CustomObject>
    <fields>
        <fullName>Compte__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>uniquement pour les nNote de frais détail non attachée à un évènement</description>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Details_note_de_frais</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contrat__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Notes de frais</relationshipLabel>
        <relationshipName>Notes_de_frais</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Des_Frais__c</fullName>
        <label>Date des frais</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>help description</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Evenement_Id__c</fullName>
        <description>pas de lookup possible vers un évenement pour le moment</description>
        <label>Evenement Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mission</label>
        <referenceTo>Mission__c</referenceTo>
        <relationshipLabel>Notes de frais</relationshipLabel>
        <relationshipName>Notes_de_frais</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Objet_attache_libelle__c</fullName>
        <formula>if( Mission__c != null,
Mission__r.Name,
IF(Opportunite__c != null,
Opportunite__r.Name,
IF(Contrat__c != null,
  Contrat__r.ContractNumber  ,
IF(Mission_CIR__c != null,
Mission_CIR__r.Name,
IF(Compte__c != null,
Compte__r.Name,
&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Objet attaché (libellé)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Objet_attache_type__c</fullName>
        <formula>if( Mission__c != null, 
&apos;Mission&apos;, 
IF(Opportunite__c != null, 
&apos;Opportunité&apos;, 
IF(Contrat__c != null, 
&apos;Contrat&apos;, 
IF(Mission_CIR__c != null, 
&apos;Mission InnoAdvance&apos;, 
IF(Compte__c != null, 
&apos;Compte&apos;, 
&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Objet attaché (type)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunité</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Notes de frais</relationshipLabel>
        <relationshipName>Notes_de_frais</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recap_Note_De_Frais__c</fullName>
        <label>Récap notes de frais</label>
        <referenceTo>Note_De_Frais_Recap__c</referenceTo>
        <relationshipLabel>Notes de frais</relationshipLabel>
        <relationshipName>Details_note_de_frais</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total note de frais</label>
        <summarizedField>Note_De_Frais_Depense__c.Total__c</summarizedField>
        <summaryForeignKey>Note_De_Frais_Depense__c.Note_De_Frais__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Note de frais</label>
    <nameField>
        <displayFormat>NDF-{000000}</displayFormat>
        <label>Num Note De Frais</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes de frais</pluralLabel>
    <recordTypes>
        <fullName>Evenement</fullName>
        <active>true</active>
        <label>Evènement</label>
    </recordTypes>
    <recordTypes>
        <fullName>Libre</fullName>
        <active>true</active>
        <label>Libre</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Note_De_Frais_Depense__c.object
<CustomObject>
    <description>AppNDF : dépense (type taxi, carburant) associée à une note de frais, qui est un ensemble de dépenses associées à un évènement par exemple</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Indemnites_Kilometriques__c</fullName>
        <label>Indémnités kilométriques</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_HT__c</fullName>
        <label>Montant HT</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_TTC__c</fullName>
        <inlineHelpText>help montant</inlineHelpText>
        <label>Montant TTC</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Montant_TVA__c</fullName>
        <label>Montant TVA</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nature_Depense_Categorie__c</fullName>
        <label>Nature dépense catégorie</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nature_Depense__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>help!</inlineHelpText>
        <label>Nature dépense</label>
        <referenceTo>Note_De_Frais_Nature_Depense__c</referenceTo>
        <relationshipLabel>Dépenses note de frais</relationshipLabel>
        <relationshipName>Depenses_note_de_frais</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nombre_De_Kilometres__c</fullName>
        <inlineHelpText>Indiquer le nombre de kilomètres effectués avec votre voiture personnelle au titre d&apos;un déplacement professionnel. 
L&apos;utilisation de votre véhicule personnel doit avoir été autorisé par votre responsable.</inlineHelpText>
        <label>Nombre de kilomètres</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Note_De_Frais__c</fullName>
        <label>Note de frais</label>
        <referenceTo>Note_De_Frais__c</referenceTo>
        <relationshipLabel>Dépenses note de frais</relationshipLabel>
        <relationshipName>Depenses_note_de_frais</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Num_PJ__c</fullName>
        <inlineHelpText>Chacune des pièces justificatives doit être numérotée et annexée à la note de frais</inlineHelpText>
        <label>Num PJ</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StatutClientBR__c</fullName>
        <label>Statut Client - BR</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>En attente</fullName>
                </value>
                <value>
                    <fullName>Envoyé</fullName>
                </value>
                <value>
                    <fullName>Payé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Taux_Indemnites__c</fullName>
        <formula>IF( AND(Nombre_De_Kilometres__c &gt; 0, Indemnites_Kilometriques__c  &gt;0),Indemnites_Kilometriques__c  /Nombre_De_Kilometres__c ,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Taux Indemnités</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>Indemnites_Kilometriques__c + Montant_HT__c +  Montant_TVA__c +  Montant_TTC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Dépense note de frais</label>
    <nameField>
        <displayFormat>NDF-D-{00000}</displayFormat>
        <label>Num Dépense</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dépenses note de frais</pluralLabel>
    <recordTypes>
        <fullName>Autre_Frais</fullName>
        <active>true</active>
        <label>Autre Frais</label>
    </recordTypes>
    <recordTypes>
        <fullName>Frais_Kilometrique</fullName>
        <active>true</active>
        <label>Frais kilométrique</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Note_De_Frais_Nature_Depense__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HT</fullName>
                </value>
                <value>
                    <fullName>TTC</fullName>
                </value>
                <value>
                    <fullName>Frais kilométrique</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Nature dépense</label>
    <nameField>
        <label>Libellé</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Natures dépense</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/Note_De_Frais_Recap__c.object
<CustomObject>
    <description>AppNDF : récapitulatif mensuelle de toutes les notes de frais (et dépenses notes de frais) d&apos;un collaborateur pour un mois donné</description>
    <fields>
        <fullName>Collaborateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collaborateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Collaborateur_Notes_De_Frais</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total remboursé</label>
        <summarizedField>Note_De_Frais__c.Total__c</summarizedField>
        <summaryForeignKey>Note_De_Frais__c.Recap_Note_De_Frais__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Récap notes de frais</label>
    <nameField>
        <displayFormat>NDF-R-{00000}</displayFormat>
        <label>Num Récap</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Récap notes de frais</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/AppNDFrecapFullComponent.cls
public without sharing class AppNDFrecapFullComponent {

  private Boolean bInit = false;
  //public Id idNDF { get; set; }
    public Note_De_Frais_Recap__c oNDFrecap = new Note_De_Frais_Recap__c();
    
    public Map<String, List<Note_De_Frais_Depense__c>> mpNDFdepense {
    get{
      if(!bInit && this.oNDFrecap != null)
        this.initVar();
        
      return this.mpNDFdepense;
    }
    set;
  }
  public List<Note_De_Frais_Depense__History> lsNDFdepenseHistory {
    get{
      if(!bInit && this.oNDFrecap != null)
        this.initVar();
        
      return this.lsNDFdepenseHistory;
    }
    set;
  }
  public List<Note_De_Frais__c> lsNDFevent {
    get{
      if(!bInit && this.oNDFrecap != null)
        this.initVar();
        
      return this.lsNDFevent;
    }
    set;
  }
    public List<Note_De_Frais__c> lsNDFlibre {
    get{
      if(!bInit && this.oNDFrecap != null)
        this.initVar();
        
      return this.lsNDFlibre;
    }
    set;
  }
    public Map<Id, String> mpEvent {
    get{
      if(!bInit && this.oNDFrecap != null)
        this.initVar();
        
      return this.mpEvent;
    }
    set;
  }
    public Integer iLsDepenseSize {
    get{
      return this.mpNDFdepense.get('Autre_Frais').size();
    }
    set;
  }
  public Integer iLsFraisKiloSize {
    get{
      return this.mpNDFdepense.get('Frais_Kilometrique').size();
    }
    set;
  }
  
  public AppNDFrecapFullComponent(){}
  
  public void initVar(){

    this.bInit = true;

    this.mpNDFdepense = new Map<String, List<Note_De_Frais_Depense__c>>{
      'Autre_Frais' => new List<Note_De_Frais_Depense__c>(),
      'Frais_Kilometrique' => new List<Note_De_Frais_Depense__c>()};
    
    this.mpEvent = new Map<Id, String>();
    Map<Id, Event> mpTemp = new Map<Id, Event>();
    Set<Id> setId = new Set<Id>();
    
    List<Note_De_Frais_Depense__c> lsNDFdepense = [
        Select
            
          	n.Total__c, 
			n.RecordTypeId,
			n.RecordType.DeveloperName,
			n.RecordType.Name,
			n.Num_PJ__c,
			n.Note_De_Frais__c,

			n.Note_De_Frais__r.Name,
			n.Note_De_Frais__r.Description__c,
			n.Note_De_Frais__r.Evenement_Id__c,
			n.Note_De_Frais__r.CreatedDate,
			n.Note_De_Frais__r.RecordType.DeveloperName,
			n.Note_De_Frais__r.Date_Des_Frais__c,
			n.Note_De_Frais__r.Mission__c,
			n.Note_De_Frais__r.Opportunite__c,
			n.Note_De_Frais__r.Compte__c,
			n.Note_De_Frais__r.Contrat__c,
			n.Note_De_Frais__r.Objet_attache_type__c,
			n.Note_De_Frais__r.Objet_attache_libelle__c,
			n.Nombre_De_Kilometres__c,
			n.Nature_Depense__c,
			n.Nature_Depense__r.Type__c,
			n.Nature_Depense__r.Name,
			n.Nature_Depense_Categorie__c, 
			n.Name,
			n.Montant_TVA__c,
			n.Montant_TTC__c,
			n.Montant_HT__c, 
			n.Indemnites_Kilometriques__c,
			n.Taux_Indemnites__c,
			n.Id,
        	n.StatutClientBR__c,
			n.Description__c
        From Note_De_Frais_Depense__c n
        Where n.Note_De_Frais__r.Recap_Note_De_Frais__c =: this.oNDFrecap.Id
        order by n.Note_De_Frais__r.CreatedDate];
        
    for(Note_De_Frais_Depense__c oNDFdepense : lsNDFdepense){
      if(oNDFdepense.Note_De_Frais__r.Evenement_Id__c != null && !setId.contains(oNDFdepense.Note_De_Frais__r.Evenement_Id__c)){
        setId.add(oNDFdepense.Note_De_Frais__r.Evenement_Id__c);
    //    mpTemp.put(oNDFdepense.Note_De_Frais__r.Evenement_Id__c, new Event());
      }
    }
    
    for(Event e : [
                        Select
                            e.WhatId,
                            e.What.Name,
                            e.Subject,
                            e.Id,
                            e.IsDeleted,
                            e.ActivityDate,
                            e.AccountId
                        From Event e
                        Where e.Id in : setId]){
            mpTemp.put(e.Id, e);       
        }
        
    DateTime dt;
        String sEv;
    for(Note_De_Frais_Depense__c oNDFdepense : lsNDFdepense){
      
      if(oNDFdepense.RecordType.DeveloperName == 'Frais_Kilometrique')
        this.mpNDFdepense.get('Frais_Kilometrique').add(oNDFdepense);
      
      if(oNDFdepense.RecordType.DeveloperName == 'Autre_Frais')
        this.mpNDFdepense.get('Autre_Frais').add(oNDFdepense);
      
      if(oNDFdepense.Note_De_Frais__r.RecordType.DeveloperName == 'Libre'){
        dt = Datetime.newInstance(oNDFdepense.Note_De_Frais__r.Date_Des_Frais__c.year(),oNDFdepense.Note_De_Frais__r.Date_Des_Frais__c.month(),oNDFdepense.Note_De_Frais__r.Date_Des_Frais__c.day(),0,0,0);
        this.mpEvent.put(oNDFdepense.Id, System.Label.Libre_Frais_en_date_du_date.replace( '__date__',  dt.format('dd/MM/yyyy') ) );
      }
      
      if(oNDFdepense.Note_De_Frais__r.RecordType.DeveloperName == 'Evenement'){
        if(mpTemp.get(oNDFdepense.Note_De_Frais__r.Evenement_Id__c) != null){
          sEv = mpTemp.get(oNDFdepense.Note_De_Frais__r.Evenement_Id__c).Subject + ' - ';
          if(mpTemp.get(oNDFdepense.Note_De_Frais__r.Evenement_Id__c).WhatId != null)
            sEv += mpTemp.get(oNDFdepense.Note_De_Frais__r.Evenement_Id__c).What.Name + ' - ';
                  dt = Datetime.newInstance(mpTemp.get(oNDFdepense.Note_De_Frais__r.Evenement_Id__c).ActivityDate.year(),mpTemp.get(oNDFdepense.Note_De_Frais__r.Evenement_Id__c).ActivityDate.month(),mpTemp.get(oNDFdepense.Note_De_Frais__r.Evenement_Id__c).ActivityDate.day(),0,0,0);
                  sEv += dt.format('dd/MM/yyyy');
          this.mpEvent.put(oNDFdepense.Id,sEv);
        }else{
          this.mpEvent.put(oNDFdepense.Id,'évènement introuvable');
        }
      }
    }
    
    
    // on récupère les histories
    set<Id> setIdDepense = new set<Id>();
    for(Note_De_Frais_Depense__c d : this.mpNDFdepense.get('Autre_Frais')){
      setIdDepense.add(d.Id);
    }
    
    this.lsNDFdepenseHistory = new List<Note_De_Frais_Depense__History>();
    List<Note_De_Frais_Depense__c> lsNDF = [Select (Select Id, Division, IsDeleted, ParentId, Parent.Name, Parent.Nature_Depense__r.Name, CreatedBy.Name, CreatedById, CreatedDate, Field, OldValue, NewValue From Histories where Field != 'created' order by CreatedDate) From Note_De_Frais_Depense__c n where n.Id in : setIdDepense];
         
        for(Note_De_Frais_Depense__c nd : lsNDF){
          for(Note_De_Frais_Depense__History ndh : nd.Histories){
            if(ndh.CreatedById != this.oNDFrecap.Collaborateur__c)
              this.lsNDFdepenseHistory.add(ndh);
          }
        }
  }
  

  // ---------------------------------//
  // --------- getter setter ---------//
  // ---------------------------------//
  
  public Note_De_Frais_Recap__c getONDFrecap(){
      return this.oNDFrecap;
    }
    
    public void setONDFrecap(Note_De_Frais_Recap__c oRec){
      this.bInit = false;
      this.oNDFrecap = oRec;
    }
    
  
}