gac_sb/objects/Note_De_Frais__c.object
<CustomObject>
    <fields>
        <fullName>Date_Des_Frais__c</fullName>
        <label>Date des frais</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evenement_Id__c</fullName>
        <description>pas de lookup possible vers un évenement pour le moment</description>
        <label>Evenement Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <label>Pays</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recap_Note_De_Frais__c</fullName>
        <label>Récap notes de frais</label>
        <referenceTo>Note_De_Frais_Recap__c</referenceTo>
        <relationshipLabel>Notes de frais</relationshipLabel>
        <relationshipName>Details_note_de_frais</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Note de frais</label>
    <nameField>
        <displayFormat>NDF-{000000}</displayFormat>
        <label>Num Note De Frais</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes de frais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Note_De_Frais_Depense__c.object
<CustomObject>
    <description>AppNDF : dépense (type taxi, carburant) associée à une note de frais, qui est un ensemble de dépenses associées à un évènement par exemple</description>
    <fields>
        <fullName>Montant_TTC__c</fullName>
        <inlineHelpText>help montant</inlineHelpText>
        <label>Montant TTC</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nature_Depense__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>help!</inlineHelpText>
        <label>Nature dépense</label>
        <referenceTo>Note_De_Frais_Nature_Depense__c</referenceTo>
        <relationshipLabel>Dépenses note de frais</relationshipLabel>
        <relationshipName>Depenses_note_de_frais</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Note_De_Frais__c</fullName>
        <label>Note de frais</label>
        <referenceTo>Note_De_Frais__c</referenceTo>
        <relationshipLabel>Dépenses note de frais</relationshipLabel>
        <relationshipName>Depenses_note_de_frais</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Dépense note de frais</label>
    <nameField>
        <displayFormat>NDF-D-{00000}</displayFormat>
        <label>Num Dépense</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dépenses note de frais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

gac_sb/objects/Note_De_Frais_Nature_Depense__c.object
<CustomObject>
    <fields>
        <fullName>Actif__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Actif</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Aide__c</fullName>
        <label>Aide</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Categorie__c</fullName>
        <label>Catégorie</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Autres (TVA non récupérable)</fullName>
                </value>
                <value>
                    <fullName>Autres (TVA récupérable)</fullName>
                </value>
                <value>
                    <fullName>Avion</fullName>
                </value>
                <value>
                    <fullName>Carburant</fullName>
                </value>
                <value>
                    <fullName>Déjeuner</fullName>
                </value>
                <value>
                    <fullName>Dîner</fullName>
                </value>
                <value>
                    <fullName>Frais kilométrique</fullName>
                </value>
                <value>
                    <fullName>Hotêl (nuitée)</fullName>
                </value>
                <value>
                    <fullName>Location véhicule</fullName>
                </value>
                <value>
                    <fullName>Parking / Métro / Bus</fullName>
                </value>
                <value>
                    <fullName>Péage</fullName>
                </value>
                <value>
                    <fullName>Petit Déjeuner</fullName>
                </value>
                <value>
                    <fullName>Poste</fullName>
                </value>
                <value>
                    <fullName>Repas avec invités tiers</fullName>
                </value>
                <value>
                    <fullName>Taxi</fullName>
                </value>
                <value>
                    <fullName>Train</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <label>Pays</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Brésil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HT</fullName>
                </value>
                <value>
                    <fullName>TTC</fullName>
                </value>
                <value>
                    <fullName>Frais kilométrique</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Nature dépense</label>
    <nameField>
        <label>Libellé</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Natures dépense</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gac_sb/objects/Note_De_Frais_Recap__c.object
<CustomObject>
    <description>AppNDF : récapitulatif mensuelle de toutes les notes de frais (et dépenses notes de frais) d&apos;un collaborateur pour un mois donné</description>
    <fields>
        <fullName>Collaborateur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collaborateur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Collaborateur_Notes_De_Frais</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Debut_De_Periode__c</fullName>
        <label>Date début de période</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_fin_de_periode__c</fullName>
        <label>Date fin de période</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <label>Pays</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Récap notes de frais</label>
    <nameField>
        <displayFormat>NDF-R-{00000}</displayFormat>
        <label>Num Récap</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Récap notes de frais</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

gac_sb/classes/AppNDFtestBase.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
 
@isTest
public class AppNDFtestBase {

    public static List<Account> lsAccounts;
    public static List<Event> lsEvents;
    public static Note_De_Frais_Recap__c oNDFrecap;
    public static List<Note_De_Frais__c> lsNDF;
    public static List<Note_De_Frais_Depense__c> lsNDFdepense;
    
    static Map<String,Id> recordTypes;
    static List<Note_De_Frais_Nature_Depense__c> lsNatures;
    static Set<Id> setAccountsIds;
    static Set<Id> setEventsIds;
    
    static void refreshAccount(){
        lsAccounts = [select Id,Name
                    from Account WHERE Name like 'TestNDF %' order by name ASC];
                    
        setAccountsIds = new Set<Id>();
        for(Account a:lsAccounts){
            setAccountsIds.add(a.Id);
        }
    }
    
    public static void Init(){

        initRecordTypes();
        initNatures();
        
        
        Account[] Accs = new Account[]{
            new Account(Name = 'TestNDF 1',Siret__c='12343678900001', BillingStreet = '1 avenue de la cristallerie', BillingCity = 'SEVRES' , BillingPostalCode = '92370', BillingCountry = 'FRANCE',Industry = 'Santé',Activity__c='Biotech, biologie')
        };
        
        insert Accs;
        refreshAccount();
        
        initEvents();
        
    }
    
    public static Note_De_Frais_Nature_Depense__c getNature(String sType){
        Note_De_Frais_Nature_Depense__c n;
        if(sType == 'TTC')
            n = lsNatures.get(0);
        
        if(sType == 'HT')
            n = lsNatures.get(1);
        
        if(sType == 'Frais')
            n = lsNatures.get(2);
            
        return n;
    }
    
    static void initNatures(){
        lsNatures = new Note_De_Frais_Nature_Depense__c[]{
            new Note_De_Frais_Nature_Depense__c(
                Type__c = 'TTC',
                Categorie__c = 'Train',
                Name = 'Train',
                Aide__c = 'Help',
                Pays__c = 'France',
                Actif__c = true),
            new Note_De_Frais_Nature_Depense__c(
                Type__c = 'HT',
                Name = 'Avion',
                Categorie__c = 'Avion',
                Aide__c = 'Help',
                Pays__c = 'France',
                Actif__c = true),
            new Note_De_Frais_Nature_Depense__c(
                Type__c = 'Frais Kilométrique',
                Name = 'Frais Kilométrique',
                Categorie__c = 'Frais Kilométrique',
                Pays__c = 'France',
                Aide__c = 'Help',
                Actif__c = true)
        };
        
        insert lsNatures;
        
    }
    
    
    static void initRecordTypes(){
        recordTypes = new Map<String,Id>();
        for(RecordType rtype : [SELECT Id, SobjectType, DeveloperName FROM RecordType WHERE SobjectType='Event' or sObjectType = 'Note_De_Frais_Depense__c' or sObjectType = 'Note_De_Frais__c']){
            recordTypes.put(rtype.SobjectType + '_' + rtype.DeveloperName, rtype.Id);
        }
    }
    
    static void initEvents(){
        Event[] Evts = new Event[]{
                new Event(
                    Subject = 'Test 1',
                    RecordTypeId = recordTypes.get('Event_RDV_Commercial') ,
                    WhatId = lsAccounts[0].Id,
                    startDateTime = datetime.now()-5,
                    endDateTime = datetime.now(),
                    objet_evenement__c = 'RDV Commercial',
                    nature_evenement__c = 'RDV Physique')
        };
        
        insert Evts;
        refreshEvents();
    }

    static void refreshEvents(){
        lsEvents = [select Id, Subject, WhatId, AccountId, What.Type
                    from Event WHERE Subject like 'Test%' order by Subject ASC];
                    
        setEventsIds = new Set<Id>();
        for(Event e:lsEvents){
            setEventsIds.add(e.Id);
        }
    }
    
    public static void initRecap(){
        
        oNDFrecap = new Note_De_Frais_Recap__c(
            Date_fin_de_periode__c = date.today() - 15,
            Date_Debut_De_Periode__c = date.today() + 15,
            Collaborateur__c = UserInfo.getUserId()
        );
        
        insert oNDFrecap;
    }
    
    public static void initNDF(){
        
        lsNDF = new List<Note_De_Frais__c> {
            new Note_De_Frais__c(
                RecordTypeId = recordTypes.get('Note_De_Frais__c_Libre'),
                Recap_Note_De_Frais__c = oNDFrecap.Id,
                Date_Des_Frais__c = date.today()),
            new Note_De_Frais__c(
                RecordTypeId = recordTypes.get('Note_De_Frais__c_Evenement'),
                Recap_Note_De_Frais__c = oNDFrecap.Id,
                Evenement_Id__c = lsEvents[0].Id)
        };
        
        insert lsNDF;
    }
    
    public static void initNDFdepense(){
        system.debug(recordTypes);
        lsNDFdepense = new List<Note_De_Frais_Depense__c> {
            
            new Note_De_Frais_Depense__c(
                RecordTypeId = recordTypes.get('Note_De_Frais_Depense__c_Autre_Frais'),
                Note_De_Frais__c = lsNDF[0].Id,
                Nature_Depense__c = getNature('TTC').Id,
                Montant_TTC__c = 10
                ),
            new Note_De_Frais_Depense__c(
                RecordTypeId = recordTypes.get('Note_De_Frais_Depense__c_Autre_Frais'),
                Note_De_Frais__c = lsNDF[1].Id,
                Nature_Depense__c = getNature('TTC').Id,
                Montant_TTC__c = 10
                )
        };
        
        insert lsNDFdepense;
    }
}